/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package management

// ApplicationProfileDefinitionSpec struct for ApplicationProfileDefinitionSpec
type ApplicationProfileDefinitionSpec struct {
	// JSON Schema draft \\#7
	Schema map[string]interface{} `json:"schema"`
}
