/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package management

// LlmConnectionSpecAnthropicConnectionConfigApiKey Reference to a Secret resource containing the Anthropic API key.
type LlmConnectionSpecAnthropicConnectionConfigApiKey struct {
	// Secret name to be used as a reference.
	Name string `json:"name,omitempty"`
	// Key to be used from the referenced secret.
	Key string `json:"key,omitempty"`
}
