/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package management

// AssetMappingOverridesReplace Sets AssetResource properties with what is defined here. (management.v1.AssetMapping)
type AssetMappingOverridesReplace struct {
	Spec AssetMappingOverridesReplaceSpec `json:"spec,omitempty"`
}
