/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package management

// LlmConnectionSpecOpenAiConnectionConfig Connection config for OpenAI (or OpenAI-compatible endpoints).
type LlmConnectionSpecOpenAiConnectionConfig struct {
	ProviderType string `json:"providerType"`
	// Base URL (defaults to https://api.openai.com/v1 if omitted).
	BaseUrl string                                        `json:"baseUrl,omitempty"`
	ApiKey  LlmConnectionSpecOpenAiConnectionConfigApiKey `json:"apiKey"`
	// OpenAI organization ID (optional).
	OrganizationId string `json:"organizationId,omitempty"`
	// List of OpenAI models users are allowed to use with this connection (e.g. gpt-4o, gpt-4o-mini).
	AllowedModels []LlmProviderSpecOpenAiModels `json:"allowedModels"`
	// GENERATE: The following code has been modified after code generation
	Temperature float64 `json:"temperature,omitempty"`
	// GENERATE: The following code has been modified after code generation
	TopP float64 `json:"topP,omitempty"`
	// GENERATE: The following code has been modified after code generation
	FrequencyPenalty float64 `json:"frequencyPenalty,omitempty"`
	// GENERATE: The following code has been modified after code generation
	PresencePenalty float64 `json:"presencePenalty,omitempty"`
}
