/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package management

// LlmProviderSpecMistral Mistral AI.
type LlmProviderSpecMistral struct {
	ProviderType string `json:"providerType"`
	// List of models provided by Mistral (e.g. mistral-large-latest, mistral-small-latest).
	Models []LlmProviderSpecMistralModels `json:"models"`
}
