/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package management

// ApiServiceComplianceLintingStatus Provides the current linting job state and the final result.
type ApiServiceComplianceLintingStatus struct {
	// The state of the compliance job.
	State              string `json:"state,omitempty"`
	ApiSpecLintingJob  string `json:"apiSpecLintingJob,omitempty"`
	ApiServiceRevision string `json:"apiServiceRevision,omitempty"`
	// Ruleset logical name.
	Ruleset string `json:"ruleset,omitempty"`
	// File name of the APISpecLintingRuleset.
	RulesetFileName string                                  `json:"rulesetFileName,omitempty"`
	Result          ApiServiceComplianceLintingStatusResult `json:"result,omitempty"`
}
