/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package management

// LlmProviderSpecAwsBedrockModels struct for LlmProviderSpecAwsBedrockModels
type LlmProviderSpecAwsBedrockModels struct {
	// AWS Bedrock model ID (e.g. anthropic.claude-3-5-sonnet-20241022-v2:0, amazon.titan-text-express-v1).
	Name string `json:"name"`
}
