/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package management

// DataplaneSpecMistral The configuration for connecting to Mistral as an LLM provider dataplane
type DataplaneSpecMistral struct {
	Type string `json:"type,omitempty"`
	// The Mistral API base URL. Defaults to the standard Mistral API endpoint when not set.
	BaseUrl string `json:"baseUrl,omitempty"`
	// The Mistral workspace ID to scope API usage to.
	WorkspaceId string `json:"workspaceId,omitempty"`
	// The Mistral regional inference zone to report usage for. Defaults to global when not set.
	ApiZone string `json:"apiZone,omitempty"`
}
