/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package management

// ApiRuntimeRulesetSpec  (management.v1.APIRuntimeRuleset)
type ApiRuntimeRulesetSpec struct {
	Definition ApiRuntimeRulesetSpecDefinition `json:"definition,omitempty"`
	// Description of the API runtime ruleset.
	Description string `json:"description,omitempty"`
}
