/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package management

// LlmConnectionSpecOpenAiConnectionConfigAllowedModels struct for LlmConnectionSpecOpenAiConnectionConfigAllowedModels
type LlmConnectionSpecOpenAiConnectionConfigAllowedModels struct {
	// OpenAI model name (e.g. gpt-4o, gpt-4o-mini).
	Name string `json:"name"`
}
