/*
 * This file is automatically generated
 */

package v1alpha1

import (
	"encoding/json"

	apiv1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/api/v1"
)

var (
	_AmplifyConfigGVK = apiv1.GroupVersionKind{
		GroupKind: apiv1.GroupKind{
			Group: "management",
			Kind:  "AmplifyConfig",
		},
		APIVersion: "v1alpha1",
	}

	AmplifyConfigScopes = []string{"Environment"}
)

const AmplifyConfigResourceName = "ampconfigs"

func AmplifyConfigGVK() apiv1.GroupVersionKind {
	return _AmplifyConfigGVK
}

func init() {
	apiv1.RegisterGVK(_AmplifyConfigGVK, AmplifyConfigScopes[0], AmplifyConfigResourceName)
}

// AmplifyConfig Resource
type AmplifyConfig struct {
	apiv1.ResourceMeta

	Owner *apiv1.Owner `json:"owner"`

	Spec AmplifyConfigSpec `json:"spec"`
}

// FromInstance converts a ResourceInstance to a AmplifyConfig
func (res *AmplifyConfig) FromInstance(ri *apiv1.ResourceInstance) error {
	if ri == nil {
		res = nil
		return nil
	}

	var err error
	rawResource := ri.GetRawResource()
	if rawResource == nil {
		rawResource, err = json.Marshal(ri)
		if err != nil {
			return err
		}
	}

	err = json.Unmarshal(rawResource, res)
	return err
}

// AmplifyConfigFromInstanceArray converts a []*ResourceInstance to a []*AmplifyConfig
func AmplifyConfigFromInstanceArray(fromArray []*apiv1.ResourceInstance) ([]*AmplifyConfig, error) {
	newArray := make([]*AmplifyConfig, 0)
	for _, item := range fromArray {
		res := &AmplifyConfig{}
		err := res.FromInstance(item)
		if err != nil {
			return make([]*AmplifyConfig, 0), err
		}
		newArray = append(newArray, res)
	}

	return newArray, nil
}

// AsInstance converts a AmplifyConfig to a ResourceInstance
func (res *AmplifyConfig) AsInstance() (*apiv1.ResourceInstance, error) {
	meta := res.ResourceMeta
	meta.GroupVersionKind = AmplifyConfigGVK()
	res.ResourceMeta = meta

	m, err := json.Marshal(res)
	if err != nil {
		return nil, err
	}

	instance := apiv1.ResourceInstance{}
	err = json.Unmarshal(m, &instance)
	if err != nil {
		return nil, err
	}

	return &instance, nil
}
