/*
 * This file is automatically generated
 */

package v1alpha1

import (
	"encoding/json"

	apiv1 "git.ecd.axway.org/apigov/apic_agents_sdk/pkg/apic/apiserver/models/api/v1"
)

var (
	_APIServiceRevisionGVK = apiv1.GroupVersionKind{
		GroupKind: apiv1.GroupKind{
			Group: "management",
			Kind:  "APIServiceRevision",
		},
		APIVersion: "v1alpha1",
	}
)

const (
	APIServiceRevisionScope = "Environment"

	APIServiceRevisionResource = "apiservicerevisions"
)

func APIServiceRevisionGVK() apiv1.GroupVersionKind {
	return _APIServiceRevisionGVK
}

func init() {
	apiv1.RegisterGVK(_APIServiceRevisionGVK, APIServiceRevisionScope, APIServiceRevisionResource)
}

// APIServiceRevision Resource
type APIServiceRevision struct {
	apiv1.ResourceMeta

	Spec ApiServiceRevisionSpec `json:"spec"`
}

// FromInstance converts a ResourceInstance to a APIServiceRevision
func (res *APIServiceRevision) FromInstance(ri *apiv1.ResourceInstance) error {
	m, err := json.Marshal(ri.Spec)
	if err != nil {
		return err
	}

	spec := &ApiServiceRevisionSpec{}
	err = json.Unmarshal(m, spec)
	if err != nil {
		return err
	}

	*res = APIServiceRevision{ResourceMeta: ri.ResourceMeta, Spec: *spec}

	return err
}

// AsInstance converts a APIServiceRevision to a ResourceInstance
func (res *APIServiceRevision) AsInstance() (*apiv1.ResourceInstance, error) {
	m, err := json.Marshal(res.Spec)
	if err != nil {
		return nil, err
	}

	spec := map[string]interface{}{}
	err = json.Unmarshal(m, &spec)
	if err != nil {
		return nil, err
	}

	return &apiv1.ResourceInstance{ResourceMeta: res.ResourceMeta, Spec: spec}, nil
}
