/*
 * This file is automatically generated
 */

package management

import (
	"encoding/json"

	apiv1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/api/v1"

	"github.com/Axway/agent-sdk/pkg/util/log"
)

var (
	APIServiceCtx log.ContextField = "apiService"

	_APIServiceGVK = apiv1.GroupVersionKind{
		GroupKind: apiv1.GroupKind{
			Group: "management",
			Kind:  "APIService",
		},
		APIVersion: "v1alpha1",
	}

	APIServiceScopes = []string{"Environment"}
)

const (
	APIServiceResourceName                           = "apiservices"
	ApiServiceAgentdetailsSubResourceName            = "agentdetails"
	ApiServiceAppinfoSubResourceName                 = "appinfo"
	ApiServiceComplianceSubResourceName              = "compliance"
	ApiServiceComplianceruntimeresultSubResourceName = "complianceruntimeresult"
	ApiServiceDetailsSubResourceName                 = "details"
	ApiServiceProfileSubResourceName                 = "profile"
	ApiServiceReferencesSubResourceName              = "references"
	ApiServiceSourceSubResourceName                  = "source"
	ApiServiceStatusSubResourceName                  = "status"
)

func APIServiceGVK() apiv1.GroupVersionKind {
	return _APIServiceGVK
}

func init() {
	apiv1.RegisterGVK(_APIServiceGVK, APIServiceScopes[0], APIServiceResourceName)
	log.RegisterContextField(APIServiceCtx)
}

// APIService Resource
type APIService struct {
	apiv1.ResourceMeta
	// GENERATE: The following code has been modified after code generation
	//
	//	Agentdetails ApiServiceAgentdetails `json:"agentdetails"`
	Agentdetails *ApiServiceAgentdetails `json:"agentdetails,omitempty"`
	// GENERATE: The following code has been modified after code generation
	//
	//	Appinfo      ApiServiceAppinfo       `json:"appinfo"`
	Appinfo *ApiServiceAppinfo `json:"appinfo,omitempty"`
	// GENERATE: The following code has been modified after code generation
	//
	//	Compliance              ApiServiceCompliance   `json:"compliance"`
	Compliance              *ApiServiceCompliance `json:"compliance,omitempty"`
	Complianceruntimeresult interface{}           `json:"complianceruntimeresult"`
	Details                 ApiServiceDetails     `json:"details"`
	Owner                   *apiv1.Owner          `json:"owner"`
	// GENERATE: The following code has been modified after code generation
	//
	//	Profile                 ApiServiceProfile     `json:"profile"`
	Profile    *ApiServiceProfile   `json:"profile,omitempty"`
	References ApiServiceReferences `json:"references"`
	// GENERATE: The following code has been modified after code generation
	//
	//	Source                  ApiServiceSource      `json:"source"`
	Source *ApiServiceSource `json:"source,omitempty"`
	Spec   ApiServiceSpec    `json:"spec"`
	// Status ApiServiceStatus  `json:"status"`
	Status *apiv1.ResourceStatus `json:"status"`
}

// NewAPIService creates an empty *APIService
func NewAPIService(name, scopeName string) *APIService {
	return &APIService{
		ResourceMeta: apiv1.ResourceMeta{
			Name:             name,
			GroupVersionKind: _APIServiceGVK,
			Metadata: apiv1.Metadata{
				Scope: apiv1.MetadataScope{
					Name: scopeName,
					Kind: APIServiceScopes[0],
				},
			},
		},
	}
}

// APIServiceFromInstanceArray converts a []*ResourceInstance to a []*APIService
func APIServiceFromInstanceArray(fromArray []*apiv1.ResourceInstance) ([]*APIService, error) {
	newArray := make([]*APIService, 0)
	for _, item := range fromArray {
		res := &APIService{}
		err := res.FromInstance(item)
		if err != nil {
			return make([]*APIService, 0), err
		}
		newArray = append(newArray, res)
	}

	return newArray, nil
}

// AsInstance converts a APIService to a ResourceInstance
func (res *APIService) AsInstance() (*apiv1.ResourceInstance, error) {
	meta := res.ResourceMeta
	meta.GroupVersionKind = APIServiceGVK()
	res.ResourceMeta = meta

	m, err := json.Marshal(res)
	if err != nil {
		return nil, err
	}

	instance := apiv1.ResourceInstance{}
	err = json.Unmarshal(m, &instance)
	if err != nil {
		return nil, err
	}
	for key, val := range res.SubResourceHashes {
		instance.SubResourceHashes[key] = val
	}
	return &instance, nil
}

// FromInstance converts a ResourceInstance to a APIService
func (res *APIService) FromInstance(ri *apiv1.ResourceInstance) error {
	if ri == nil {
		res = nil
		return nil
	}
	var err error
	rawResource := ri.GetRawResource()
	if rawResource == nil {
		rawResource, err = json.Marshal(ri)
		if err != nil {
			return err
		}
	}
	err = json.Unmarshal(rawResource, res)
	if err != nil {
		return err
	}
	for key, val := range ri.SubResourceHashes {
		res.SubResourceHashes[key] = val
	}
	return err
}

// MarshalJSON custom marshaller to handle sub resources
func (res *APIService) MarshalJSON() ([]byte, error) {
	m, err := json.Marshal(&res.ResourceMeta)
	if err != nil {
		return nil, err
	}

	var out map[string]interface{}
	err = json.Unmarshal(m, &out)
	if err != nil {
		return nil, err
	}

	out["agentdetails"] = res.Agentdetails
	out["appinfo"] = res.Appinfo
	out["compliance"] = res.Compliance
	out["complianceruntimeresult"] = res.Complianceruntimeresult
	out["details"] = res.Details
	out["owner"] = res.Owner
	out["profile"] = res.Profile
	out["references"] = res.References
	out["source"] = res.Source
	out["spec"] = res.Spec
	out["status"] = res.Status

	return json.Marshal(out)
}

// UnmarshalJSON custom unmarshaller to handle sub resources
func (res *APIService) UnmarshalJSON(data []byte) error {
	var err error

	aux := &apiv1.ResourceInstance{}
	err = json.Unmarshal(data, aux)
	if err != nil {
		return err
	}

	res.ResourceMeta = aux.ResourceMeta
	res.Owner = aux.Owner

	// ResourceInstance holds the spec as a map[string]interface{}.
	// Convert it to bytes, then convert to the spec type for the resource.
	sr, err := json.Marshal(aux.Spec)
	if err != nil {
		return err
	}

	err = json.Unmarshal(sr, &res.Spec)
	if err != nil {
		return err
	}

	// marshalling subresource Agentdetails
	if v, ok := aux.SubResources["agentdetails"]; ok {
		sr, err = json.Marshal(v)
		if err != nil {
			return err
		}

		delete(aux.SubResources, "agentdetails")
		err = json.Unmarshal(sr, &res.Agentdetails)
		if err != nil {
			return err
		}
	}

	// marshalling subresource Appinfo
	if v, ok := aux.SubResources["appinfo"]; ok {
		sr, err = json.Marshal(v)
		if err != nil {
			return err
		}

		delete(aux.SubResources, "appinfo")
		err = json.Unmarshal(sr, &res.Appinfo)
		if err != nil {
			return err
		}
	}

	// marshalling subresource Compliance
	if v, ok := aux.SubResources["compliance"]; ok {
		sr, err = json.Marshal(v)
		if err != nil {
			return err
		}

		delete(aux.SubResources, "compliance")
		err = json.Unmarshal(sr, &res.Compliance)
		if err != nil {
			return err
		}
	}

	// marshalling subresource Complianceruntimeresult
	if v, ok := aux.SubResources["complianceruntimeresult"]; ok {
		sr, err = json.Marshal(v)
		if err != nil {
			return err
		}

		delete(aux.SubResources, "complianceruntimeresult")
		err = json.Unmarshal(sr, &res.Complianceruntimeresult)
		if err != nil {
			return err
		}
	}

	// marshalling subresource Details
	if v, ok := aux.SubResources["details"]; ok {
		sr, err = json.Marshal(v)
		if err != nil {
			return err
		}

		delete(aux.SubResources, "details")
		err = json.Unmarshal(sr, &res.Details)
		if err != nil {
			return err
		}
	}

	// marshalling subresource Profile
	if v, ok := aux.SubResources["profile"]; ok {
		sr, err = json.Marshal(v)
		if err != nil {
			return err
		}

		delete(aux.SubResources, "profile")
		err = json.Unmarshal(sr, &res.Profile)
		if err != nil {
			return err
		}
	}

	// marshalling subresource References
	if v, ok := aux.SubResources["references"]; ok {
		sr, err = json.Marshal(v)
		if err != nil {
			return err
		}

		delete(aux.SubResources, "references")
		err = json.Unmarshal(sr, &res.References)
		if err != nil {
			return err
		}
	}

	// marshalling subresource Source
	if v, ok := aux.SubResources["source"]; ok {
		sr, err = json.Marshal(v)
		if err != nil {
			return err
		}

		delete(aux.SubResources, "source")
		err = json.Unmarshal(sr, &res.Source)
		if err != nil {
			return err
		}
	}

	// marshalling subresource Status
	if v, ok := aux.SubResources["status"]; ok {
		sr, err = json.Marshal(v)
		if err != nil {
			return err
		}

		delete(aux.SubResources, "status")
		// err = json.Unmarshal(sr, &res.Status)
		res.Status = &apiv1.ResourceStatus{}
		err = json.Unmarshal(sr, res.Status)
		if err != nil {
			return err
		}
	}

	return nil
}

// PluralName returns the plural name of the resource
func (res *APIService) PluralName() string {
	return APIServiceResourceName
}
