/*
 * This file is automatically generated
 */

package management

import (
	"encoding/json"

	apiv1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/api/v1"

	"github.com/Axway/agent-sdk/pkg/util/log"
)

var (
	ComplianceRuntimeResultCtx log.ContextField = "complianceRuntimeResult"

	_ComplianceRuntimeResultGVK = apiv1.GroupVersionKind{
		GroupKind: apiv1.GroupKind{
			Group: "management",
			Kind:  "ComplianceRuntimeResult",
		},
		APIVersion: "v1alpha1",
	}

	ComplianceRuntimeResultScopes = []string{"Environment"}
)

const (
	ComplianceRuntimeResultResourceName = "complianceruntimeresults"
)

func ComplianceRuntimeResultGVK() apiv1.GroupVersionKind {
	return _ComplianceRuntimeResultGVK
}

func init() {
	apiv1.RegisterGVK(_ComplianceRuntimeResultGVK, ComplianceRuntimeResultScopes[0], ComplianceRuntimeResultResourceName)
	log.RegisterContextField(ComplianceRuntimeResultCtx)
}

// ComplianceRuntimeResult Resource
type ComplianceRuntimeResult struct {
	apiv1.ResourceMeta
	Owner *apiv1.Owner                `json:"owner"`
	Spec  ComplianceRuntimeResultSpec `json:"spec"`
}

// NewComplianceRuntimeResult creates an empty *ComplianceRuntimeResult
func NewComplianceRuntimeResult(name, scopeName string) *ComplianceRuntimeResult {
	return &ComplianceRuntimeResult{
		ResourceMeta: apiv1.ResourceMeta{
			Name:             name,
			GroupVersionKind: _ComplianceRuntimeResultGVK,
			Metadata: apiv1.Metadata{
				Scope: apiv1.MetadataScope{
					Name: scopeName,
					Kind: ComplianceRuntimeResultScopes[0],
				},
			},
		},
	}
}

// ComplianceRuntimeResultFromInstanceArray converts a []*ResourceInstance to a []*ComplianceRuntimeResult
func ComplianceRuntimeResultFromInstanceArray(fromArray []*apiv1.ResourceInstance) ([]*ComplianceRuntimeResult, error) {
	newArray := make([]*ComplianceRuntimeResult, 0)
	for _, item := range fromArray {
		res := &ComplianceRuntimeResult{}
		err := res.FromInstance(item)
		if err != nil {
			return make([]*ComplianceRuntimeResult, 0), err
		}
		newArray = append(newArray, res)
	}

	return newArray, nil
}

// AsInstance converts a ComplianceRuntimeResult to a ResourceInstance
func (res *ComplianceRuntimeResult) AsInstance() (*apiv1.ResourceInstance, error) {
	meta := res.ResourceMeta
	meta.GroupVersionKind = ComplianceRuntimeResultGVK()
	res.ResourceMeta = meta

	m, err := json.Marshal(res)
	if err != nil {
		return nil, err
	}

	instance := apiv1.ResourceInstance{}
	err = json.Unmarshal(m, &instance)
	if err != nil {
		return nil, err
	}
	instance.SubResourceHashes = res.SubResourceHashes
	return &instance, nil
}

// FromInstance converts a ResourceInstance to a ComplianceRuntimeResult
func (res *ComplianceRuntimeResult) FromInstance(ri *apiv1.ResourceInstance) error {
	if ri == nil {
		res = nil
		return nil
	}
	var err error
	rawResource := ri.GetRawResource()
	if rawResource == nil {
		rawResource, err = json.Marshal(ri)
		if err != nil {
			return err
		}
	}
	err = json.Unmarshal(rawResource, res)
	if err != nil {
		return err
	}
	res.SubResourceHashes = ri.SubResourceHashes
	return err
}

// MarshalJSON custom marshaller to handle sub resources
func (res *ComplianceRuntimeResult) MarshalJSON() ([]byte, error) {
	m, err := json.Marshal(&res.ResourceMeta)
	if err != nil {
		return nil, err
	}

	var out map[string]interface{}
	err = json.Unmarshal(m, &out)
	if err != nil {
		return nil, err
	}

	out["owner"] = res.Owner
	out["spec"] = res.Spec

	return json.Marshal(out)
}

// UnmarshalJSON custom unmarshaller to handle sub resources
func (res *ComplianceRuntimeResult) UnmarshalJSON(data []byte) error {
	var err error

	aux := &apiv1.ResourceInstance{}
	err = json.Unmarshal(data, aux)
	if err != nil {
		return err
	}

	res.ResourceMeta = aux.ResourceMeta
	res.Owner = aux.Owner

	// ResourceInstance holds the spec as a map[string]interface{}.
	// Convert it to bytes, then convert to the spec type for the resource.
	sr, err := json.Marshal(aux.Spec)
	if err != nil {
		return err
	}

	err = json.Unmarshal(sr, &res.Spec)
	if err != nil {
		return err
	}

	return nil
}

// PluralName returns the plural name of the resource
func (res *ComplianceRuntimeResult) PluralName() string {
	return ComplianceRuntimeResultResourceName
}
