/*
 * This file is automatically generated
 */

package management

import (
	"encoding/json"

	apiv1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/api/v1"

	"github.com/Axway/agent-sdk/pkg/util/log"
)

var (
	ComplianceAgentCtx log.ContextField = "complianceAgent"

	_ComplianceAgentGVK = apiv1.GroupVersionKind{
		GroupKind: apiv1.GroupKind{
			Group: "management",
			Kind:  "ComplianceAgent",
		},
		APIVersion: "v1alpha1",
	}

	ComplianceAgentScopes = []string{"Environment"}
)

const (
	ComplianceAgentResourceName              = "complianceagents"
	ComplianceAgentAgentstateSubResourceName = "agentstate"
	ComplianceAgentDataplaneSubResourceName  = "dataplane"
	ComplianceAgentStatusSubResourceName     = "status"
)

func ComplianceAgentGVK() apiv1.GroupVersionKind {
	return _ComplianceAgentGVK
}

func init() {
	apiv1.RegisterGVK(_ComplianceAgentGVK, ComplianceAgentScopes[0], ComplianceAgentResourceName)
	log.RegisterContextField(ComplianceAgentCtx)
}

// ComplianceAgent Resource
type ComplianceAgent struct {
	apiv1.ResourceMeta
	Agentstate ComplianceAgentAgentstate `json:"agentstate"`
	Dataplane  ComplianceAgentDataplane  `json:"dataplane"`
	Owner      *apiv1.Owner              `json:"owner"`
	Spec       ComplianceAgentSpec       `json:"spec"`
	// Status     ComplianceAgentStatus     `json:"status"`
	Status *apiv1.ResourceStatus `json:"status"`
}

// NewComplianceAgent creates an empty *ComplianceAgent
func NewComplianceAgent(name, scopeName string) *ComplianceAgent {
	return &ComplianceAgent{
		ResourceMeta: apiv1.ResourceMeta{
			Name:             name,
			GroupVersionKind: _ComplianceAgentGVK,
			Metadata: apiv1.Metadata{
				Scope: apiv1.MetadataScope{
					Name: scopeName,
					Kind: ComplianceAgentScopes[0],
				},
			},
		},
	}
}

// ComplianceAgentFromInstanceArray converts a []*ResourceInstance to a []*ComplianceAgent
func ComplianceAgentFromInstanceArray(fromArray []*apiv1.ResourceInstance) ([]*ComplianceAgent, error) {
	newArray := make([]*ComplianceAgent, 0)
	for _, item := range fromArray {
		res := &ComplianceAgent{}
		err := res.FromInstance(item)
		if err != nil {
			return make([]*ComplianceAgent, 0), err
		}
		newArray = append(newArray, res)
	}

	return newArray, nil
}

// AsInstance converts a ComplianceAgent to a ResourceInstance
func (res *ComplianceAgent) AsInstance() (*apiv1.ResourceInstance, error) {
	meta := res.ResourceMeta
	meta.GroupVersionKind = ComplianceAgentGVK()
	res.ResourceMeta = meta

	m, err := json.Marshal(res)
	if err != nil {
		return nil, err
	}

	instance := apiv1.ResourceInstance{}
	err = json.Unmarshal(m, &instance)
	if err != nil {
		return nil, err
	}
	instance.SubResourceHashes = res.SubResourceHashes
	return &instance, nil
}

// FromInstance converts a ResourceInstance to a ComplianceAgent
func (res *ComplianceAgent) FromInstance(ri *apiv1.ResourceInstance) error {
	if ri == nil {
		res = nil
		return nil
	}
	var err error
	rawResource := ri.GetRawResource()
	if rawResource == nil {
		rawResource, err = json.Marshal(ri)
		if err != nil {
			return err
		}
	}
	err = json.Unmarshal(rawResource, res)
	if err != nil {
		return err
	}
	res.SubResourceHashes = ri.SubResourceHashes
	return err
}

// MarshalJSON custom marshaller to handle sub resources
func (res *ComplianceAgent) MarshalJSON() ([]byte, error) {
	m, err := json.Marshal(&res.ResourceMeta)
	if err != nil {
		return nil, err
	}

	var out map[string]interface{}
	err = json.Unmarshal(m, &out)
	if err != nil {
		return nil, err
	}

	out["agentstate"] = res.Agentstate
	out["dataplane"] = res.Dataplane
	out["owner"] = res.Owner
	out["spec"] = res.Spec
	out["status"] = res.Status

	return json.Marshal(out)
}

// UnmarshalJSON custom unmarshaller to handle sub resources
func (res *ComplianceAgent) UnmarshalJSON(data []byte) error {
	var err error

	aux := &apiv1.ResourceInstance{}
	err = json.Unmarshal(data, aux)
	if err != nil {
		return err
	}

	res.ResourceMeta = aux.ResourceMeta
	res.Owner = aux.Owner

	// ResourceInstance holds the spec as a map[string]interface{}.
	// Convert it to bytes, then convert to the spec type for the resource.
	sr, err := json.Marshal(aux.Spec)
	if err != nil {
		return err
	}

	err = json.Unmarshal(sr, &res.Spec)
	if err != nil {
		return err
	}

	// marshalling subresource Agentstate
	if v, ok := aux.SubResources["agentstate"]; ok {
		sr, err = json.Marshal(v)
		if err != nil {
			return err
		}

		delete(aux.SubResources, "agentstate")
		err = json.Unmarshal(sr, &res.Agentstate)
		if err != nil {
			return err
		}
	}

	// marshalling subresource Dataplane
	if v, ok := aux.SubResources["dataplane"]; ok {
		sr, err = json.Marshal(v)
		if err != nil {
			return err
		}

		delete(aux.SubResources, "dataplane")
		err = json.Unmarshal(sr, &res.Dataplane)
		if err != nil {
			return err
		}
	}

	// marshalling subresource Status
	if v, ok := aux.SubResources["status"]; ok {
		sr, err = json.Marshal(v)
		if err != nil {
			return err
		}

		delete(aux.SubResources, "status")
		// err = json.Unmarshal(sr, &res.Status)
		res.Status = &apiv1.ResourceStatus{}
		err = json.Unmarshal(sr, res.Status)
		if err != nil {
			return err
		}
	}

	return nil
}

// PluralName returns the plural name of the resource
func (res *ComplianceAgent) PluralName() string {
	return ComplianceAgentResourceName
}
