/*
 * This file is automatically generated
 */

package v1alpha1

import (
	"encoding/json"
	v1 "git.ecd.axway.int/apigov/apic_agents_sdk/pkg/apic/apiserver/models/api/v1"
)

var (
	_ConsumerInstanceGVK = v1.GroupVersionKind{
		GroupKind: v1.GroupKind{
			Group: "management",
			Kind:  "ConsumerInstance",
		},
		ApiVersion: "v1alpha1",
	}
)

const (
	ConsumerInstanceScope = "Environment"

	ConsumerInstanceResource = "consumerinstances"
)

func ConsumerInstanceGVK() v1.GroupVersionKind {
	return _ConsumerInstanceGVK
}

func init() {
	v1.RegisterGVK(_ConsumerInstanceGVK, ConsumerInstanceScope, ConsumerInstanceResource)
}

type ConsumerInstance struct {
	v1.ResourceMeta

	Spec ConsumerInstanceSpec `json:"true"`

	Status ConsumerInstanceStatus `json:"true"`
}

func (res *ConsumerInstance) FromInstance(ri *v1.ResourceInstance) error {
	// TODO this needs to be better
	m, err := json.Marshal(ri.Spec)
	if err != nil {
		return err
	}

	spec := &ConsumerInstanceSpec{}
	err = json.Unmarshal(m, spec)
	if err != nil {
		return err
	}

	*res = ConsumerInstance{ResourceMeta: ri.ResourceMeta, Spec: *spec}

	return err
}

func (res *ConsumerInstance) AsInstance() (*v1.ResourceInstance, error) {
	m, err := json.Marshal(res.Spec)
	if err != nil {
		return nil, err
	}

	spec := map[string]interface{}{}
	err = json.Unmarshal(m, &spec)
	if err != nil {
		return nil, err
	}

	return &v1.ResourceInstance{ResourceMeta: res.ResourceMeta, Spec: spec}, nil
}
