/*
 * This file is automatically generated
 */

package v1alpha1

import (
	"encoding/json"

	apiv1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/api/v1"
)

var (
	_CorsRuleGVK = apiv1.GroupVersionKind{
		GroupKind: apiv1.GroupKind{
			Group: "management",
			Kind:  "CorsRule",
		},
		APIVersion: "v1alpha1",
	}

	CorsRuleScopes = []string{"VirtualAPI", "VirtualAPIRelease"}
)

const CorsRuleResourceName = "corsrules"

func CorsRuleGVK() apiv1.GroupVersionKind {
	return _CorsRuleGVK
}

func init() {
	apiv1.RegisterGVK(_CorsRuleGVK, CorsRuleScopes[0], CorsRuleResourceName)
}

// CorsRule Resource
type CorsRule struct {
	apiv1.ResourceMeta

	Owner *apiv1.Owner `json:"owner"`

	Spec CorsRuleSpec `json:"spec"`
}

// FromInstance converts a ResourceInstance to a CorsRule
func (res *CorsRule) FromInstance(ri *apiv1.ResourceInstance) error {
	if ri == nil {
		res = nil
		return nil
	}

	var err error
	rawResource := ri.GetRawResource()
	if rawResource == nil {
		rawResource, err = json.Marshal(ri)
		if err != nil {
			return err
		}
	}

	err = json.Unmarshal(rawResource, res)
	return err
}

// CorsRuleFromInstanceArray converts a []*ResourceInstance to a []*CorsRule
func CorsRuleFromInstanceArray(fromArray []*apiv1.ResourceInstance) ([]*CorsRule, error) {
	newArray := make([]*CorsRule, 0)
	for _, item := range fromArray {
		res := &CorsRule{}
		err := res.FromInstance(item)
		if err != nil {
			return make([]*CorsRule, 0), err
		}
		newArray = append(newArray, res)
	}

	return newArray, nil
}

// AsInstance converts a CorsRule to a ResourceInstance
func (res *CorsRule) AsInstance() (*apiv1.ResourceInstance, error) {
	meta := res.ResourceMeta
	meta.GroupVersionKind = CorsRuleGVK()
	res.ResourceMeta = meta

	m, err := json.Marshal(res)
	if err != nil {
		return nil, err
	}

	instance := apiv1.ResourceInstance{}
	err = json.Unmarshal(m, &instance)
	if err != nil {
		return nil, err
	}

	return &instance, nil
}
