/*
 * This file is automatically generated
 */

package v1alpha1

import (
	"encoding/json"

	apiv1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/api/v1"
)

var (
	_DiscoveryAgentGVK = apiv1.GroupVersionKind{
		GroupKind: apiv1.GroupKind{
			Group: "management",
			Kind:  "DiscoveryAgent",
		},
		APIVersion: "v1alpha1",
	}

	DiscoveryAgentScopes = []string{"Environment"}
)

const DiscoveryAgentResourceName = "discoveryagents"

func DiscoveryAgentGVK() apiv1.GroupVersionKind {
	return _DiscoveryAgentGVK
}

func init() {
	apiv1.RegisterGVK(_DiscoveryAgentGVK, DiscoveryAgentScopes[0], DiscoveryAgentResourceName)
}

// DiscoveryAgent Resource
type DiscoveryAgent struct {
	apiv1.ResourceMeta
	Owner  *apiv1.Owner         `json:"owner"`
	Spec   DiscoveryAgentSpec   `json:"spec"`
	Status DiscoveryAgentStatus `json:"status"`
}

// FromInstance converts a ResourceInstance to a DiscoveryAgent
func (res *DiscoveryAgent) FromInstance(ri *apiv1.ResourceInstance) error {
	if ri == nil {
		res = nil
		return nil
	}

	var err error
	rawResource := ri.GetRawResource()
	if rawResource == nil {
		rawResource, err = json.Marshal(ri)
		if err != nil {
			return err
		}
	}

	err = json.Unmarshal(rawResource, res)
	return err
}

// DiscoveryAgentFromInstanceArray converts a []*ResourceInstance to a []*DiscoveryAgent
func DiscoveryAgentFromInstanceArray(fromArray []*apiv1.ResourceInstance) ([]*DiscoveryAgent, error) {
	newArray := make([]*DiscoveryAgent, 0)
	for _, item := range fromArray {
		res := &DiscoveryAgent{}
		err := res.FromInstance(item)
		if err != nil {
			return make([]*DiscoveryAgent, 0), err
		}
		newArray = append(newArray, res)
	}

	return newArray, nil
}

// AsInstance converts a DiscoveryAgent to a ResourceInstance
func (res *DiscoveryAgent) AsInstance() (*apiv1.ResourceInstance, error) {
	meta := res.ResourceMeta
	meta.GroupVersionKind = DiscoveryAgentGVK()
	res.ResourceMeta = meta

	m, err := json.Marshal(res)
	if err != nil {
		return nil, err
	}

	instance := apiv1.ResourceInstance{}
	err = json.Unmarshal(m, &instance)
	if err != nil {
		return nil, err
	}

	return &instance, nil
}

// MarshalJSON custom marshaller to handle sub resources
func (res *DiscoveryAgent) MarshalJSON() ([]byte, error) {
	m, err := json.Marshal(&res.ResourceMeta)
	if err != nil {
		return nil, err
	}

	var out map[string]interface{}
	err = json.Unmarshal(m, &out)
	if err != nil {
		return nil, err
	}

	out["owner"] = res.Owner
	out["spec"] = res.Spec
	out["status"] = res.Status

	return json.Marshal(out)
}

// UnmarshalJSON custom unmarshaler to handle sub resources
func (res *DiscoveryAgent) UnmarshalJSON(data []byte) error {
	var err error

	// Create an alias for unmarshalling to avoid a circular UnmarshalJSON call
	type Alias DiscoveryAgent
	aux := &struct{ *Alias }{
		Alias: (*Alias)(res),
	}

	err = json.Unmarshal(data, &aux)
	if err != nil {
		return err
	}

	// The only field that will properly unmarshal will be the ResourceMeta field.
	// This is because ResourceMeta is embedded on all resources, and when UnmarshalJSON is called on the Alias,
	// the ResourceMeta UnmarshalJSON will be called instead of the default UnmarshalJSON, which would handle all fields.
	// The rest of the fields need to be unmarshalled manually.
	res.ResourceMeta = aux.ResourceMeta

	// unmarshall all fields into a map
	out := map[string]interface{}{}

	err = json.Unmarshal(data, &out)
	if err != nil {
		return err
	}

	// unmarshall the owner field
	if out["owner"] != nil {
		res.Owner = &apiv1.Owner{}
		bts, err := json.Marshal(out["owner"])
		if err != nil {
			return err
		}
		err = json.Unmarshal(bts, res.Owner)
		if err != nil {
			return err
		}
	}

	// unmarshall the spec field
	if out["spec"] != nil {
		bts, err := json.Marshal(out["spec"])
		if err != nil {
			return err
		}
		err = json.Unmarshal(bts, &res.Spec)
		if err != nil {
			return err
		}
	}

	return nil
}
