/*
 * This file is automatically generated
 */

package v1alpha1

import (
	"encoding/json"

	apiv1 "git.ecd.axway.org/apigov/apic_agents_sdk/pkg/apic/apiserver/models/api/v1"
)

var (
	_EdgeTraceabilityAgentGVK = apiv1.GroupVersionKind{
		GroupKind: apiv1.GroupKind{
			Group: "management",
			Kind:  "EdgeTraceabilityAgent",
		},
		APIVersion: "v1alpha1",
	}
)

const (
	EdgeTraceabilityAgentScope = "Environment"

	EdgeTraceabilityAgentResource = "edgetraceabilityagents"
)

func EdgeTraceabilityAgentGVK() apiv1.GroupVersionKind {
	return _EdgeTraceabilityAgentGVK
}

func init() {
	apiv1.RegisterGVK(_EdgeTraceabilityAgentGVK, EdgeTraceabilityAgentScope, EdgeTraceabilityAgentResource)
}

// EdgeTraceabilityAgent Resource
type EdgeTraceabilityAgent struct {
	apiv1.ResourceMeta

	Spec EdgeTraceabilityAgentSpec `json:"spec"`

	Status EdgeTraceabilityAgentStatus `json:"status"`
}

// FromInstance converts a ResourceInstance to a EdgeTraceabilityAgent
func (res *EdgeTraceabilityAgent) FromInstance(ri *apiv1.ResourceInstance) error {
	m, err := json.Marshal(ri.Spec)
	if err != nil {
		return err
	}

	spec := &EdgeTraceabilityAgentSpec{}
	err = json.Unmarshal(m, spec)
	if err != nil {
		return err
	}

	*res = EdgeTraceabilityAgent{ResourceMeta: ri.ResourceMeta, Spec: *spec}

	return err
}

// AsInstance converts a EdgeTraceabilityAgent to a ResourceInstance
func (res *EdgeTraceabilityAgent) AsInstance() (*apiv1.ResourceInstance, error) {
	m, err := json.Marshal(res.Spec)
	if err != nil {
		return nil, err
	}

	spec := map[string]interface{}{}
	err = json.Unmarshal(m, &spec)
	if err != nil {
		return nil, err
	}

	return &apiv1.ResourceInstance{ResourceMeta: res.ResourceMeta, Spec: spec}, nil
}
