/*
 * This file is automatically generated
 */

package v1alpha1

import (
	"encoding/json"

	apiv1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/api/v1"
)

var (
	_IntegrationGVK = apiv1.GroupVersionKind{
		GroupKind: apiv1.GroupKind{
			Group: "management",
			Kind:  "Integration",
		},
		APIVersion: "v1alpha1",
	}

	IntegrationScopes = []string{""}
)

const IntegrationResourceName = "integrations"

func IntegrationGVK() apiv1.GroupVersionKind {
	return _IntegrationGVK
}

func init() {
	apiv1.RegisterGVK(_IntegrationGVK, IntegrationScopes[0], IntegrationResourceName)
}

// Integration Resource
type Integration struct {
	apiv1.ResourceMeta

	Owner *apiv1.Owner `json:"owner"`

	Spec IntegrationSpec `json:"spec"`
}

// FromInstance converts a ResourceInstance to a Integration
func (res *Integration) FromInstance(ri *apiv1.ResourceInstance) error {
	if ri == nil {
		res = nil
		return nil
	}

	var err error
	rawResource := ri.GetRawResource()
	if rawResource == nil {
		rawResource, err = json.Marshal(ri)
		if err != nil {
			return err
		}
	}

	err = json.Unmarshal(rawResource, res)
	return err
}

// IntegrationFromInstanceArray converts a []*ResourceInstance to a []*Integration
func IntegrationFromInstanceArray(fromArray []*apiv1.ResourceInstance) ([]*Integration, error) {
	newArray := make([]*Integration, 0)
	for _, item := range fromArray {
		res := &Integration{}
		err := res.FromInstance(item)
		if err != nil {
			return make([]*Integration, 0), err
		}
		newArray = append(newArray, res)
	}

	return newArray, nil
}

// AsInstance converts a Integration to a ResourceInstance
func (res *Integration) AsInstance() (*apiv1.ResourceInstance, error) {
	meta := res.ResourceMeta
	meta.GroupVersionKind = IntegrationGVK()
	res.ResourceMeta = meta

	m, err := json.Marshal(res)
	if err != nil {
		return nil, err
	}

	instance := apiv1.ResourceInstance{}
	err = json.Unmarshal(m, &instance)
	if err != nil {
		return nil, err
	}

	return &instance, nil
}
