/*
 * This file is automatically generated
 */

package v1alpha1

import (
	"encoding/json"

	apiv1 "git.ecd.axway.int/apigov/apic_agents_sdk/pkg/apic/apiserver/models/api/v1"
)

var (
	_K8SClusterGVK = apiv1.GroupVersionKind{
		GroupKind: apiv1.GroupKind{
			Group: "management",
			Kind:  "K8SCluster",
		},
		ApiVersion: "v1alpha1",
	}
)

const (
	K8SClusterScope = ""

	K8SClusterResource = "k8sclusters"
)

func K8SClusterGVK() apiv1.GroupVersionKind {
	return _K8SClusterGVK
}

func init() {
	apiv1.RegisterGVK(_K8SClusterGVK, K8SClusterScope, K8SClusterResource)
}

type K8SCluster struct {
	apiv1.ResourceMeta

	Spec K8SClusterSpec `json:"spec"`
}

func (res *K8SCluster) FromInstance(ri *apiv1.ResourceInstance) error {
	// TODO this needs to be better
	m, err := json.Marshal(ri.Spec)
	if err != nil {
		return err
	}

	spec := &K8SClusterSpec{}
	err = json.Unmarshal(m, spec)
	if err != nil {
		return err
	}

	*res = K8SCluster{ResourceMeta: ri.ResourceMeta, Spec: *spec}

	return err
}

func (res *K8SCluster) AsInstance() (*apiv1.ResourceInstance, error) {
	m, err := json.Marshal(res.Spec)
	if err != nil {
		return nil, err
	}

	spec := map[string]interface{}{}
	err = json.Unmarshal(m, &spec)
	if err != nil {
		return nil, err
	}

	return &apiv1.ResourceInstance{ResourceMeta: res.ResourceMeta, Spec: spec}, nil
}
