/*
 * This file is automatically generated
 */

package v1alpha1

import (
	"encoding/json"

	apiv1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/api/v1"
)

var (
	_MeshDiscoveryGVK = apiv1.GroupVersionKind{
		GroupKind: apiv1.GroupKind{
			Group: "management",
			Kind:  "MeshDiscovery",
		},
		APIVersion: "v1alpha1",
	}
)

const (
	MeshDiscoveryScope = "Mesh"

	MeshDiscoveryResourceName = "meshdiscoveries"
)

func MeshDiscoveryGVK() apiv1.GroupVersionKind {
	return _MeshDiscoveryGVK
}

func init() {
	apiv1.RegisterGVK(_MeshDiscoveryGVK, MeshDiscoveryScope, MeshDiscoveryResourceName)
}

// MeshDiscovery Resource
type MeshDiscovery struct {
	apiv1.ResourceMeta

	Owner interface{} `json:"owner"`

	Spec MeshDiscoverySpec `json:"spec"`
}

// FromInstance converts a ResourceInstance to a MeshDiscovery
func (res *MeshDiscovery) FromInstance(ri *apiv1.ResourceInstance) error {
	if ri == nil {
		res = nil
		return nil
	}

	err := json.Unmarshal(ri.RawResource, res)
	return err
}

// MeshDiscoveryFromInstanceArray converts a []*ResourceInstance to a []*MeshDiscovery
func MeshDiscoveryFromInstanceArray(fromArray []*apiv1.ResourceInstance) ([]*MeshDiscovery, error) {
	newArray := make([]*MeshDiscovery, 0)
	for _, item := range fromArray {
		res := &MeshDiscovery{}
		err := res.FromInstance(item)
		if err != nil {
			return make([]*MeshDiscovery, 0), err
		}
		newArray = append(newArray, res)
	}

	return newArray, nil
}

// AsInstance converts a MeshDiscovery to a ResourceInstance
func (res *MeshDiscovery) AsInstance() (*apiv1.ResourceInstance, error) {
	m, err := json.Marshal(res.Spec)
	if err != nil {
		return nil, err
	}

	spec := map[string]interface{}{}
	err = json.Unmarshal(m, &spec)
	if err != nil {
		return nil, err
	}

	meta := res.ResourceMeta
	meta.GroupVersionKind = MeshDiscoveryGVK()

	return &apiv1.ResourceInstance{ResourceMeta: meta, Spec: spec}, nil
}
