/*
 * This file is automatically generated
 */

package v1alpha1

import (
	"encoding/json"

	apiv1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/api/v1"
)

var (
	_MeshGVK = apiv1.GroupVersionKind{
		GroupKind: apiv1.GroupKind{
			Group: "management",
			Kind:  "Mesh",
		},
		APIVersion: "v1alpha1",
	}

	MeshScopes = []string{""}
)

const MeshResourceName = "meshes"

func MeshGVK() apiv1.GroupVersionKind {
	return _MeshGVK
}

func init() {
	apiv1.RegisterGVK(_MeshGVK, MeshScopes[0], MeshResourceName)
}

// Mesh Resource
type Mesh struct {
	apiv1.ResourceMeta

	Owner *apiv1.Owner `json:"owner"`

	Spec interface{} `json:"spec"`
}

// FromInstance converts a ResourceInstance to a Mesh
func (res *Mesh) FromInstance(ri *apiv1.ResourceInstance) error {
	if ri == nil {
		res = nil
		return nil
	}

	var err error
	rawResource := ri.GetRawResource()
	if rawResource == nil {
		rawResource, err = json.Marshal(ri)
		if err != nil {
			return err
		}
	}

	err = json.Unmarshal(rawResource, res)
	return err
}

// MeshFromInstanceArray converts a []*ResourceInstance to a []*Mesh
func MeshFromInstanceArray(fromArray []*apiv1.ResourceInstance) ([]*Mesh, error) {
	newArray := make([]*Mesh, 0)
	for _, item := range fromArray {
		res := &Mesh{}
		err := res.FromInstance(item)
		if err != nil {
			return make([]*Mesh, 0), err
		}
		newArray = append(newArray, res)
	}

	return newArray, nil
}

// AsInstance converts a Mesh to a ResourceInstance
func (res *Mesh) AsInstance() (*apiv1.ResourceInstance, error) {
	meta := res.ResourceMeta
	meta.GroupVersionKind = MeshGVK()
	res.ResourceMeta = meta

	m, err := json.Marshal(res)
	if err != nil {
		return nil, err
	}

	instance := apiv1.ResourceInstance{}
	err = json.Unmarshal(m, &instance)
	if err != nil {
		return nil, err
	}

	return &instance, nil
}
