/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package management

// TraceabilityAgentSpecConfigRedactionQueryArgumentSanitize  (management.v1alpha1.TraceabilityAgent)
type TraceabilityAgentSpecConfigRedactionQueryArgumentSanitize struct {
	KeyMatch   string `json:"keyMatch,omitempty"`
	ValueMatch string `json:"valueMatch,omitempty"`
}
