/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package management

// DataplaneSpecTraceable The configuration common to all Traceable agents that use this dataplane
type DataplaneSpecTraceable struct {
	Type string `json:"type,omitempty"`
	// The Traceable region that this dataplane refers to
	Region string `json:"region"`
	// Used to run conformance analysis of specs found in central environment against endpoints found in Traceable environment
	Environments []DataplaneSpecTraceableEnvironments `json:"environments"`
}
