/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package management

// DataplaneSpecAwsCognito struct for DataplaneSpecAwsCognito
type DataplaneSpecAwsCognito struct {
	// The Cognito user pool ID.
	UserPoolId string `json:"userPoolId"`
	// The AWS region of the Cognito user pool. Defaults to the agent region if omitted.
	Region string `json:"region,omitempty"`
}
