/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package management

import (
	// GENERATE: The following code has been modified after code generation
	//
	//	"time"
	time "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/api/v1"
)

// TraceabilityAgentAgentstateSamplingEndpoints  (management.v1alpha1.TraceabilityAgent)
type TraceabilityAgentAgentstateSamplingEndpoints struct {
	// The time that the agent will stop sampling for this endpoint``
	EndTime time.Time `json:"endTime,omitempty"`
	// The base path of the endpoint that the agent will sample
	BasePath string `json:"basePath,omitempty"`
	// If true, the agent will only sample error transactions for this endpoint
	OnlyErrors bool `json:"onlyErrors,omitempty"`
}
