/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package management

// AssetMappingOverridesFilter  (management.v1alpha1.AssetMapping)
type AssetMappingOverridesFilter struct {
	// GENERATE: The following code has been modified after code generation
	Definition interface{} `json:"definition,omitempty"`
}
