/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package management

// AccessRequestReferencesAssetRequest struct for AccessRequestReferencesAssetRequest
type AccessRequestReferencesAssetRequest struct {
	Kind string `json:"kind"`
	Name string `json:"name,omitempty"`
}
