/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package management

// IdentityProviderSecretSpecClientSecret The configuration for client/secret based authentication with Identity provider
type IdentityProviderSecretSpecClientSecret struct {
	Type string `json:"type"`
	// The client/secret authentication method to be used to acquire token from Identity provider
	AuthMethod string `json:"authMethod,omitempty"`
	// The list of client scope to be used for dynamic client registration
	ClientScopes []string `json:"clientScopes,omitempty"`
	// The identifier of the client to be used for client/secret based authentication to acquire token from Identity provider
	ClientId string `json:"clientId"`
	// The secret of the client to be used for client/secret based authentication to acquire token from Identity provider
	ClientSecret string `json:"clientSecret"`
}
