/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package management

// ApiServiceAgentdetails  (management.v1alpha1.APIService)
type ApiServiceAgentdetails struct {
	// Remote API ID for the API Service.
	RemoteAPIID string `json:"remoteAPIID,omitempty"`
}
