/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1alpha1

// AwsDiscoveryAgentSpec struct for AwsDiscoveryAgentSpec
type AwsDiscoveryAgentSpec struct {
	// The name of the AWS dataplane associated to this agent
	Dataplane string `json:"dataplane"`
	// The name of the Discovery Agent associated to this agent
	DiscoveryAgent string                    `json:"discoveryAgent,omitempty"`
	Config         DiscoveryAgentSpecConfig  `json:"config"`
	Logging        DiscoveryAgentSpecLogging `json:"logging,omitempty"`
}
