/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package management

// AssetMappingTemplateSpecApiService  (management.v1alpha1.AssetMappingTemplate)
type AssetMappingTemplateSpecApiService struct {
	// The name of the API Service.
	Name string `json:"name,omitempty"`
	// Attributes used to filter the APIServiceRevisions for the API Service on which the template applies. (management.v1alpha1.AssetMappingTemplate)
	Attributes         map[string]string                          `json:"attributes,omitempty"`
	ApiServiceRevision AssetMappingTemplateSpecApiServiceRevision `json:"apiServiceRevision,omitempty"`
}
