/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1alpha1

// CredentialRequest the model 'CredentialRequest'
type CredentialRequest string

// List of CredentialRequest
const (
	// GENERATE: The following code has been modified after code generation
	CredentialRequestPROVISION CredentialRequest = "provision"
	// GENERATE: The following code has been modified after code generation
	CredentialRequestRENEW CredentialRequest = "renew"
)
