/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package management

// WatchTopicSpec struct for WatchTopicSpec
type WatchTopicSpec struct {
	// Description of the WatchTopic
	Description string                  `json:"description,omitempty"`
	Filters     []WatchTopicSpecFilters `json:"filters"`
}
