/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package management

// ApiServiceRevisionSpec  (management.v1alpha1.APIServiceRevision)
type ApiServiceRevisionSpec struct {
	ApiService string                           `json:"apiService"`
	Definition ApiServiceRevisionSpecDefinition `json:"definition,omitempty"`
}
