/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package management

// DataplaneSpecAwsAgentcore Configuration specific to the agentcore-gateway mode.
type DataplaneSpecAwsAgentcore struct {
	// Number of items per page when listing agentcore resources.
	PageSize int32 `json:"pageSize,omitempty"`
	// Log group prefix for agentcore-gateway vendored logs.
	LogGroupPrefix string `json:"logGroupPrefix,omitempty"`
	// If true, IAM authentication is enabled for agentcore-gateway requests.
	IamAuthEnabled bool `json:"iamAuthEnabled,omitempty"`
}
