/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package management

// ApiServiceInstanceSource struct for ApiServiceInstanceSource
type ApiServiceInstanceSource struct {
	DataplaneType ApiServiceSourceDataplaneType `json:"dataplaneType,omitempty"`
	// GENERATE: The following code has been modified after code generation
	//
	//	References    ApiServiceInstanceSourceReferences `json:"references,omitempty"`
	References *ApiServiceInstanceSourceReferences `json:"references,omitempty"`
	// GENERATE: The following code has been modified after code generation
	//
	//	Compliance ApiServiceInstanceSourceCompliance  `json:"compliance,omitempty"`
	Compliance *ApiServiceInstanceSourceCompliance `json:"compliance,omitempty"`
}
