/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1alpha1

// DeploymentReferences struct for DeploymentReferences
type DeploymentReferences struct {
	// Reference to the API Service that got created from this deployment.
	ApiService string `json:"apiService,omitempty"`
	// Reference to the Virtual API Service that is bound to this deployment.
	VirtualAPI string `json:"virtualAPI,omitempty"`
}
