/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1alpha1

// ExternalSecretSpecTlsData Data for TLS.
type ExternalSecretSpecTlsData struct {
	Kind string `json:"kind"`
	// Alias for the private key in the secret.
	PrivateKeyAlias string `json:"privateKeyAlias"`
	// Alias for the certificate in the secret.
	CertificateAlias string `json:"certificateAlias"`
}
