/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package management

// VirtualServiceSpecAmplifyjwtauthrule Amplify Gateway JWT authentication.
type VirtualServiceSpecAmplifyjwtauthrule struct {
	Kind string `json:"kind"`
	Name string `json:"name"`
	// Parameter not required meaning auth credentials are not forwarded to the backend by default. If set to true, auth credentials are forwarded.
	ForwardAuthCredentials bool `json:"forwardAuthCredentials,omitempty"`
}
