/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package management

// VirtualServiceSpec struct for VirtualServiceSpec
type VirtualServiceSpec struct {
	// The path prefix to match. Example /api/v1
	Prefix string `json:"prefix"`
	Cors   string `json:"cors,omitempty"`
	// GENERATE: The following code has been modified after code generation
	Auth interface{} `json:"auth"`
	// GENERATE: The following code has been modified after code generation
	Route []interface{} `json:"route"`
}
