/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package management

// ManagedApplicationSpec struct for ManagedApplicationSpec
type ManagedApplicationSpec struct {
	Security ManagedApplicationSpecSecurity `json:"security,omitempty"`
}
