/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package management

// IdentityProviderSpecClientSecret The client secret config
type IdentityProviderSpecClientSecret struct {
	Type string `json:"type"`
	// The client id
	AuthMethod string `json:"authMethod,omitempty"`
	// The client scope agent will use for dynamic client registration
	ClientScope string `json:"clientScope,omitempty"`
	// The client id
	ClientId string `json:"clientId"`
	// The client secret
	ClientSecret string `json:"clientSecret"`
}
