/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1alpha1

// MeshDiscoverySpec struct for MeshDiscoverySpec
type MeshDiscoverySpec struct {
	Selectors      map[string]interface{} `json:"selectors,omitempty"`
	EnvironmentRef string                 `json:"environmentRef,omitempty"`
}
