/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package management

// K8SResourceSpec  (management.v1alpha1.K8SResource)
type K8SResourceSpec struct {
	ResourceDiscovery string                           `json:"resourceDiscovery,omitempty"`
	ResourceVersion   string                           `json:"resourceVersion,omitempty"`
	Uid               string                           `json:"uid,omitempty"`
	OwnerReferences   []K8SResourceSpecOwnerReferences `json:"ownerReferences,omitempty"`
	//  (management.v1alpha1.K8SResource)
	ResourceSpec map[string]interface{} `json:"resourceSpec,omitempty"`
	//  (management.v1alpha1.K8SResource)
	ResourceStatus map[string]interface{} `json:"resourceStatus,omitempty"`
}
