/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package management

// VirtualServiceSpecRatelimitrule The rate limit rule reference.
type VirtualServiceSpecRatelimitrule struct {
	// The rate limit rule name.
	RateLimit string `json:"rateLimit"`
}
