/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package management

// CredentialState Current state of the Credential. (management.v1alpha1.Credential)
type CredentialState struct {
	Name string `json:"name"`
	// Additional info on the state.
	Reason string `json:"reason,omitempty"`
}
