/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package management

// DataplaneSecurity struct for DataplaneSecurity
type DataplaneSecurity struct {
	// public key to be used to encrypt the access data linked to this dataplane.
	EncryptionKey       string `json:"encryptionKey"`
	EncryptionAlgorithm string `json:"encryptionAlgorithm,omitempty"`
	EncryptionHash      string `json:"encryptionHash,omitempty"`
}
