/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package management

import (
	// GENERATE: The following code has been modified after code generation
	//
	//	"time"
	time "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/api/v1"
)

// TraceabilityAgentAgentstateSampling  (management.v1alpha1.TraceabilityAgent)
type TraceabilityAgentAgentstateSampling struct {
	// When
	Enabled bool `json:"enabled,omitempty"`
	// The last time the sampling for this agent was enabled
	LastExecution time.Time `json:"lastExecution,omitempty"`
	// The time that the agent will stop sampling
	EndTime time.Time `json:"endTime,omitempty"`
	// The upper limit of transactions, in a 1 minute period, the agent may sample
	Limit int32 `json:"limit,omitempty"`
}
