/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1alpha1

// ExternalSecretSpec Specification a custom secret provider installed on the data-plane.
type ExternalSecretSpec struct {
	// The secret provider type.
	Provider string `json:"provider,omitempty"`
	// The kind of custom secret provider. This is meant to help the data-plane extension to pickup the right implementation to fetch the secret.
	Kind string `json:"kind"`
	// A free-form object to describe the custom secret configuration that will be consumed by the data-plane when resolving the secret.
	CustomConfig map[string]map[string]interface{} `json:"customConfig,omitempty"`
}
