/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package management

// ApiServiceSourceCompliance  (management.v1alpha1.APIService)
type ApiServiceSourceCompliance struct {
	// GENERATE: The following code has been modified after code generation
	Runtime ApiServiceSourceRuntimeStatus `json:"runtime,omitempty"`
}
