/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package management

// VirtualServiceSpecPassthroughauthrule Passthrough auth rule.
type VirtualServiceSpecPassthroughauthrule struct {
	Kind string `json:"kind"`
}
