/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package management

// VirtualHostSpec  (management.v1alpha1.VirtualHost)
type VirtualHostSpec struct {
	// The fully qualifield domain name as described in RFC 1035
	Domain string `json:"domain"`
	// GENERATE: The following code has been modified after code generation
	Secret interface{} `json:"secret"`
}
