/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package management

// ApiServiceInstanceSourceCompliance struct for ApiServiceInstanceSourceCompliance
type ApiServiceInstanceSourceCompliance struct {
	Runtime ApiServiceInstanceSourceRuntimeStatus `json:"runtime,omitempty"`
}
