/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package management

// DataplaneSpecAkamai The configuration common to all Akamai agents that use this dataplane
type DataplaneSpecAkamai struct {
	Type string `json:"type,omitempty"`
	// The Akamai client ID for authentication
	Clientid string `json:"clientid"`
	// The Akamai API endpoint URL
	Url string `json:"url"`
	// Used to run conformance analysis of specs found in central environment against endpoints found in Akamai environment
	Environments []DataplaneSpecAkamaiEnvironments `json:"environments"`
}
