/*
 * API Server specification.
 *
 * API Server specification for Amplify Central.
 *
 * API version: 0.13.0
 * Contact: support@axway.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1alpha1

// ManagementV1alpha1EnvironmentSpec struct for ManagementV1alpha1EnvironmentSpec
type ManagementV1alpha1EnvironmentSpec struct {
	Description string                                `json:"description,omitempty"`
	Variables   map[string]string                     `json:"variables,omitempty"`
	Icon        ManagementV1alpha1EnvironmentSpecIcon `json:"icon,omitempty"`
}
