/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package management

// ManagedApplicationMarketplaceResourceOwnerOrganization Organization details.
type ManagedApplicationMarketplaceResourceOwnerOrganization struct {
	// Id of the organization.
	Id string `json:"id"`
}
