/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1alpha1

// ExternalSecretSpecTlsValidationData Data for TLS certificate validation.
type ExternalSecretSpecTlsValidationData struct {
	Kind string `json:"kind"`
	// Alias for the trusted certificate authority in the secret.
	TrustedCAAlias string `json:"trustedCAAlias"`
}
