/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package management

// AssetMappingSpecInputs The list of the inputs provided to the template. (management.v1alpha1.AssetMapping)
type AssetMappingSpecInputs struct {
	ApiService         string `json:"apiService"`
	ApiServiceRevision string `json:"apiServiceRevision,omitempty"`
	ApiServiceInstance string `json:"apiServiceInstance,omitempty"`
	// name of the stage
	Stage string `json:"stage,omitempty"`
	// list of categories for the asset.
	Categories []string `json:"categories,omitempty"`
	// title for generated asset resource.
	AssetResourceTitle string `json:"assetResourceTitle,omitempty"`
}
