/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package management

// AccessRequestDefinitionSpecProvisionPolicies Defines the policies applied on the AccessRequests generated using this definition.
type AccessRequestDefinitionSpecProvisionPolicies struct {
	// Defines on if AccessRequests using this definition can be moved from their current Subscription to a new one. This update implies that quotas and references are updated depending on the new Subscription's plan.
	Transferable bool `json:"transferable,omitempty"`
}
