/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package management

// ManagedApplicationMarketplace Details about the marketplace Application. (management.v1alpha1.ManagedApplication)
type ManagedApplicationMarketplace struct {
	// The name of the Marketplace.
	Name     string                                `json:"name"`
	Resource ManagedApplicationMarketplaceResource `json:"resource"`
}
