/*
 * API Server specification.
 *
 * API Server specification for Amplify Central.
 *
 * API version: 0.13.0
 * Contact: support@axway.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1alpha1

// ManagementV1alpha1ConsumerSubscriptionDefinitionSpec struct for ManagementV1alpha1ConsumerSubscriptionDefinitionSpec
type ManagementV1alpha1ConsumerSubscriptionDefinitionSpec struct {
	// List of Webhook kind resource names that dictates what webhooks will be invoked on subscription changes.
	Webhooks []string                                                   `json:"webhooks,omitempty"`
	Schema   ManagementV1alpha1ConsumerSubscriptionDefinitionSpecSchema `json:"schema,omitempty"`
}
