/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package management

// ApiServiceRevisionCompliance  (management.v1alpha1.APIServiceRevision)
type ApiServiceRevisionCompliance struct {
	// GENERATE: The following code has been modified after code generation
	Design ApiServiceRevisionComplianceLintingStatus `json:"design,omitempty"`
	// GENERATE: The following code has been modified after code generation
	Security ApiServiceRevisionComplianceLintingStatus `json:"security,omitempty"`
}
