/*
 * This file is automatically generated
 */

package v1alpha1

import (
	"encoding/json"

	apiv1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/api/v1"
)

var (
	_ResourceHookGVK = apiv1.GroupVersionKind{
		GroupKind: apiv1.GroupKind{
			Group: "management",
			Kind:  "ResourceHook",
		},
		APIVersion: "v1alpha1",
	}
)

const (
	ResourceHookScope = "Integration"

	ResourceHookResourceName = "resourcehooks"
)

func ResourceHookGVK() apiv1.GroupVersionKind {
	return _ResourceHookGVK
}

func init() {
	apiv1.RegisterGVK(_ResourceHookGVK, ResourceHookScope, ResourceHookResourceName)
}

// ResourceHook Resource
type ResourceHook struct {
	apiv1.ResourceMeta

	Owner interface{} `json:"owner"`

	Spec ResourceHookSpec `json:"spec"`
}

// FromInstance converts a ResourceInstance to a ResourceHook
func (res *ResourceHook) FromInstance(ri *apiv1.ResourceInstance) error {
	if ri == nil {
		res = nil
		return nil
	}

	err := json.Unmarshal(ri.RawResource, res)
	return err
}

// ResourceHookFromInstanceArray converts a []*ResourceInstance to a []*ResourceHook
func ResourceHookFromInstanceArray(fromArray []*apiv1.ResourceInstance) ([]*ResourceHook, error) {
	newArray := make([]*ResourceHook, 0)
	for _, item := range fromArray {
		res := &ResourceHook{}
		err := res.FromInstance(item)
		if err != nil {
			return make([]*ResourceHook, 0), err
		}
		newArray = append(newArray, res)
	}

	return newArray, nil
}

// AsInstance converts a ResourceHook to a ResourceInstance
func (res *ResourceHook) AsInstance() (*apiv1.ResourceInstance, error) {
	m, err := json.Marshal(res.Spec)
	if err != nil {
		return nil, err
	}

	spec := map[string]interface{}{}
	err = json.Unmarshal(m, &spec)
	if err != nil {
		return nil, err
	}

	meta := res.ResourceMeta
	meta.GroupVersionKind = ResourceHookGVK()

	return &apiv1.ResourceInstance{ResourceMeta: meta, Spec: spec}, nil
}
