openapi: 3.0.3
info:
  title: AMPLIFY Central internal Auth API v0.1
  version: '1.26.0-SNAPSHOT'
  contact:
    name: Axway Support
    email: support@axway.com
  license:
    name: Copyright Axway 2021. All rights reserved.
  description: APIs to validate platform tokens and retrieve principals permissions.
  x-api-id: 93507d43-4c79-5a47-9061-15cc83db5f52
  x-audience: axway-internal
tags:
  - name: auth
    description: APIs for Central Authnz.
security:
  - token: []
servers: []


components:
  parameters:
    TenantHeader:
      name: X-Axway-Tenant-Id
      in: header
      schema:
        type: string
        maxLength: 36
      required: true
      description: The platform Organization ID.
    TransactionIdHeader:
      name: X-Axway-Transaction-Id
      in: header
      schema:
        type: string
      required: false
      description: The transaction id for the API call.
  responses:
    BadRequest:
      description: Failed to validate request parameters.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Unauthorized:
      description: Unauthorized. A valid authorization header was not provided with the request to authenticate.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    InternalServerError:
      description: Unexpected internal server error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
  securitySchemes:
    token:
      type: http
      scheme: bearer
      description: Authenticated platform bearer token.
  schemas:
    AccessInfo:
      title: Authenticated principal details
      type: object
      properties:
        subject:
          type: object
          properties:
            id:
              type: string
              description: Platform subject ID.
          required:
            - id
        organization:
          type: object
          properties:
            id:
              type: string
              description: Platform Organization ID.
            instanceId:
              type: string
              description: Central Listener Instance ID.
          required:
            - id
        permissions:
          type: object
          properties:
            global:
              description: Global Organization permissions, not restricted under a scope type.
              type: object
              properties:
                values:
                  type: array
                  description: The values for the permission strings.
                  items:
                    type: string
              required:
                - values
            scoped:
              description: Permission list scoped to specific entity types.
              type: array
              items:
                type: object
                properties:
                  type:
                    description: The entity type that defines the scope of the permissions list.
                    type: string
                    enum:
                      - TEAM
                  id:
                    description: The identifier for the scope entity.
                    type: string
                  values:
                    type: array
                    description: The values for the permission strings.
                    items:
                      type: string
                required:
                  - type
                  - id
                  - values
      required:
        - subject
        - organization
        - permissions
    ErrorResponse:
      title: ErrorResponse
      description: Detail for standard error responses.
      type: object
      additionalProperties: true
      properties:
        errors:
          type: array
          items:
            type: object
            additionalProperties: true
            properties:
              status:
                type: integer
              title:
                type: string
              detail:
                type: string
              meta:
                type: object
                additionalProperties: true
                properties:
                  tenantId:
                    type: string
paths:
  "/accessInfo":
    get:
      operationId: getAccessInfo
      summary: Get the current principal access information.
      tags:
        - auth
      description: |
        Get the current principal permissions.
      parameters:
        - $ref: '#/components/parameters/TenantHeader'
        - $ref: '#/components/parameters/TransactionIdHeader'

      responses:
        200:
          description: |
            The current principal's teams and permissions.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessInfo'
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        500:
          $ref: '#/components/responses/InternalServerError'

