/*
 * Amplify Unified Catalog APIs
 *
 * APIs for Amplify Unified Catalog
 *
 * API version: 1.43.0
 * Contact: support@axway.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package unifiedcatalog
// InlineResponse500 struct for InlineResponse500
type InlineResponse500 struct {
	Errors []InlineResponse500Errors `json:"errors,omitempty"`
}
