// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: apicentral.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Owner_Type int32

const (
	Owner_TEAM Owner_Type = 0
)

// Enum value maps for Owner_Type.
var (
	Owner_Type_name = map[int32]string{
		0: "TEAM",
	}
	Owner_Type_value = map[string]int32{
		"TEAM": 0,
	}
)

func (x Owner_Type) Enum() *Owner_Type {
	p := new(Owner_Type)
	*p = x
	return p
}

func (x Owner_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Owner_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_apicentral_proto_enumTypes[0].Descriptor()
}

func (Owner_Type) Type() protoreflect.EnumType {
	return &file_apicentral_proto_enumTypes[0]
}

func (x Owner_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Owner_Type.Descriptor instead.
func (Owner_Type) EnumDescriptor() ([]byte, []int) {
	return file_apicentral_proto_rawDescGZIP(), []int{2, 0}
}

type Reference_Type int32

const (
	Reference_SOFT Reference_Type = 0
	Reference_HARD Reference_Type = 1
)

// Enum value maps for Reference_Type.
var (
	Reference_Type_name = map[int32]string{
		0: "SOFT",
		1: "HARD",
	}
	Reference_Type_value = map[string]int32{
		"SOFT": 0,
		"HARD": 1,
	}
)

func (x Reference_Type) Enum() *Reference_Type {
	p := new(Reference_Type)
	*p = x
	return p
}

func (x Reference_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Reference_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_apicentral_proto_enumTypes[1].Descriptor()
}

func (Reference_Type) Type() protoreflect.EnumType {
	return &file_apicentral_proto_enumTypes[1]
}

func (x Reference_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Reference_Type.Descriptor instead.
func (Reference_Type) EnumDescriptor() ([]byte, []int) {
	return file_apicentral_proto_rawDescGZIP(), []int{3, 0}
}

// API Server generic resource structure.
type ResourceInstance struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Defines the group from which the resource belongs to. The server infers this from the endpoint the client submits the request to.
	Group string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	// Resource kind
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// Name of the resource
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// Metadata.
	Metadata      *Metadata         `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Attributes    map[string]string `protobuf:"bytes,6,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceInstance) Reset() {
	*x = ResourceInstance{}
	mi := &file_apicentral_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceInstance) ProtoMessage() {}

func (x *ResourceInstance) ProtoReflect() protoreflect.Message {
	mi := &file_apicentral_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceInstance.ProtoReflect.Descriptor instead.
func (*ResourceInstance) Descriptor() ([]byte, []int) {
	return file_apicentral_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceInstance) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ResourceInstance) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ResourceInstance) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceInstance) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ResourceInstance) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// Metadata that all server resources have. Data is generated by the server.
type Metadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Internal id of the resource.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The scope where this resource was defined.
	Scope *Metadata_ScopeKind `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	// The URL representing this resource object.
	SelfLink string `protobuf:"bytes,6,opt,name=selfLink,proto3" json:"selfLink,omitempty"`
	// resource references
	References    []*Reference `protobuf:"bytes,7,rep,name=references,proto3" json:"references,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_apicentral_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_apicentral_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_apicentral_proto_rawDescGZIP(), []int{1}
}

func (x *Metadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Metadata) GetScope() *Metadata_ScopeKind {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *Metadata) GetSelfLink() string {
	if x != nil {
		return x.SelfLink
	}
	return ""
}

func (x *Metadata) GetReferences() []*Reference {
	if x != nil {
		return x.References
	}
	return nil
}

// Owner of the resource.
type Owner struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id of the owner of the resource.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The type of the owner. Defaults to team if not present.
	Type          Owner_Type `protobuf:"varint,2,opt,name=type,proto3,enum=central.events.v1.datamodel.Owner_Type" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Owner) Reset() {
	*x = Owner{}
	mi := &file_apicentral_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Owner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Owner) ProtoMessage() {}

func (x *Owner) ProtoReflect() protoreflect.Message {
	mi := &file_apicentral_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Owner.ProtoReflect.Descriptor instead.
func (*Owner) Descriptor() ([]byte, []int) {
	return file_apicentral_proto_rawDescGZIP(), []int{2}
}

func (x *Owner) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Owner) GetType() Owner_Type {
	if x != nil {
		return x.Type
	}
	return Owner_TEAM
}

// Reference resource
type Reference struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique id generated by the server.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The kind of the referenced resource.
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// The name of the referenced resource.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// The kind of the referenced resource scope.
	ScopeKind string `protobuf:"bytes,4,opt,name=scopeKind,proto3" json:"scopeKind,omitempty"`
	// The name of the referenced resource scope.
	ScopeName string `protobuf:"bytes,5,opt,name=scopeName,proto3" json:"scopeName,omitempty"`
	// The URL representing the referenced resource.
	SelfLink string `protobuf:"bytes,6,opt,name=selfLink,proto3" json:"selfLink,omitempty"`
	// Defines the type of the reference: * soft - spec property that has this reference will get nulled out if the referenced resource gets removed. * hard - dictates that the current resource will get removed when the referenced resource gets removed.
	Type          Reference_Type `protobuf:"varint,7,opt,name=type,proto3,enum=central.events.v1.datamodel.Reference_Type" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reference) Reset() {
	*x = Reference{}
	mi := &file_apicentral_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reference) ProtoMessage() {}

func (x *Reference) ProtoReflect() protoreflect.Message {
	mi := &file_apicentral_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reference.ProtoReflect.Descriptor instead.
func (*Reference) Descriptor() ([]byte, []int) {
	return file_apicentral_proto_rawDescGZIP(), []int{3}
}

func (x *Reference) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Reference) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Reference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Reference) GetScopeKind() string {
	if x != nil {
		return x.ScopeKind
	}
	return ""
}

func (x *Reference) GetScopeName() string {
	if x != nil {
		return x.ScopeName
	}
	return ""
}

func (x *Reference) GetSelfLink() string {
	if x != nil {
		return x.SelfLink
	}
	return ""
}

func (x *Reference) GetType() Reference_Type {
	if x != nil {
		return x.Type
	}
	return Reference_SOFT
}

type Metadata_ScopeKind struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Internal id of the scope resource where the resource is defined.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The kind of the scope resource where the resource is defined.
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// The name of the scope where the resource is defined.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// The URL to access the scope resource.
	SelfLink      string `protobuf:"bytes,4,opt,name=selfLink,proto3" json:"selfLink,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata_ScopeKind) Reset() {
	*x = Metadata_ScopeKind{}
	mi := &file_apicentral_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata_ScopeKind) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata_ScopeKind) ProtoMessage() {}

func (x *Metadata_ScopeKind) ProtoReflect() protoreflect.Message {
	mi := &file_apicentral_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata_ScopeKind.ProtoReflect.Descriptor instead.
func (*Metadata_ScopeKind) Descriptor() ([]byte, []int) {
	return file_apicentral_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Metadata_ScopeKind) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Metadata_ScopeKind) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Metadata_ScopeKind) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metadata_ScopeKind) GetSelfLink() string {
	if x != nil {
		return x.SelfLink
	}
	return ""
}

var File_apicentral_proto protoreflect.FileDescriptor

const file_apicentral_proto_rawDesc = "" +
	"\n" +
	"\x10apicentral.proto\x12\x1bcentral.events.v1.datamodel\"\xb1\x02\n" +
	"\x10ResourceInstance\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12A\n" +
	"\bmetadata\x18\x05 \x01(\v2%.central.events.v1.datamodel.MetadataR\bmetadata\x12]\n" +
	"\n" +
	"attributes\x18\x06 \x03(\v2=.central.events.v1.datamodel.ResourceInstance.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa6\x02\n" +
	"\bMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12E\n" +
	"\x05scope\x18\x02 \x01(\v2/.central.events.v1.datamodel.Metadata.ScopeKindR\x05scope\x12\x1a\n" +
	"\bselfLink\x18\x06 \x01(\tR\bselfLink\x12F\n" +
	"\n" +
	"references\x18\a \x03(\v2&.central.events.v1.datamodel.ReferenceR\n" +
	"references\x1a_\n" +
	"\tScopeKind\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bselfLink\x18\x04 \x01(\tR\bselfLink\"f\n" +
	"\x05Owner\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12;\n" +
	"\x04type\x18\x02 \x01(\x0e2'.central.events.v1.datamodel.Owner.TypeR\x04type\"\x10\n" +
	"\x04Type\x12\b\n" +
	"\x04TEAM\x10\x00\"\xf8\x01\n" +
	"\tReference\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1c\n" +
	"\tscopeKind\x18\x04 \x01(\tR\tscopeKind\x12\x1c\n" +
	"\tscopeName\x18\x05 \x01(\tR\tscopeName\x12\x1a\n" +
	"\bselfLink\x18\x06 \x01(\tR\bselfLink\x12?\n" +
	"\x04type\x18\a \x01(\x0e2+.central.events.v1.datamodel.Reference.TypeR\x04type\"\x1a\n" +
	"\x04Type\x12\b\n" +
	"\x04SOFT\x10\x00\x12\b\n" +
	"\x04HARD\x10\x01B\x18Z\x16pkg/watchmanager/protob\x06proto3"

var (
	file_apicentral_proto_rawDescOnce sync.Once
	file_apicentral_proto_rawDescData []byte
)

func file_apicentral_proto_rawDescGZIP() []byte {
	file_apicentral_proto_rawDescOnce.Do(func() {
		file_apicentral_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apicentral_proto_rawDesc), len(file_apicentral_proto_rawDesc)))
	})
	return file_apicentral_proto_rawDescData
}

var file_apicentral_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_apicentral_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_apicentral_proto_goTypes = []any{
	(Owner_Type)(0),            // 0: central.events.v1.datamodel.Owner.Type
	(Reference_Type)(0),        // 1: central.events.v1.datamodel.Reference.Type
	(*ResourceInstance)(nil),   // 2: central.events.v1.datamodel.ResourceInstance
	(*Metadata)(nil),           // 3: central.events.v1.datamodel.Metadata
	(*Owner)(nil),              // 4: central.events.v1.datamodel.Owner
	(*Reference)(nil),          // 5: central.events.v1.datamodel.Reference
	nil,                        // 6: central.events.v1.datamodel.ResourceInstance.AttributesEntry
	(*Metadata_ScopeKind)(nil), // 7: central.events.v1.datamodel.Metadata.ScopeKind
}
var file_apicentral_proto_depIdxs = []int32{
	3, // 0: central.events.v1.datamodel.ResourceInstance.metadata:type_name -> central.events.v1.datamodel.Metadata
	6, // 1: central.events.v1.datamodel.ResourceInstance.attributes:type_name -> central.events.v1.datamodel.ResourceInstance.AttributesEntry
	7, // 2: central.events.v1.datamodel.Metadata.scope:type_name -> central.events.v1.datamodel.Metadata.ScopeKind
	5, // 3: central.events.v1.datamodel.Metadata.references:type_name -> central.events.v1.datamodel.Reference
	0, // 4: central.events.v1.datamodel.Owner.type:type_name -> central.events.v1.datamodel.Owner.Type
	1, // 5: central.events.v1.datamodel.Reference.type:type_name -> central.events.v1.datamodel.Reference.Type
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_apicentral_proto_init() }
func file_apicentral_proto_init() {
	if File_apicentral_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apicentral_proto_rawDesc), len(file_apicentral_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apicentral_proto_goTypes,
		DependencyIndexes: file_apicentral_proto_depIdxs,
		EnumInfos:         file_apicentral_proto_enumTypes,
		MessageInfos:      file_apicentral_proto_msgTypes,
	}.Build()
	File_apicentral_proto = out.File
	file_apicentral_proto_goTypes = nil
	file_apicentral_proto_depIdxs = nil
}
