/*
 * This file is automatically generated
 */

package management

import (
	"fmt"

	v1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/clients/api/v1"
	apiv1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/api/v1"
	m "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/management/v1"
)

type GuardrailMergeFunc func(*m.Guardrail, *m.Guardrail) (*m.Guardrail, error)

// GuardrailMerge builds a merge option for an update operation
func GuardrailMerge(f GuardrailMergeFunc) v1.UpdateOption {
	return v1.Merge(func(prev, new apiv1.Interface) (apiv1.Interface, error) {
		p, n := &m.Guardrail{}, &m.Guardrail{}

		switch t := prev.(type) {
		case *m.Guardrail:
			p = t
		case *apiv1.ResourceInstance:
			err := p.FromInstance(t)
			if err != nil {
				return nil, fmt.Errorf("merge: failed to unserialise prev resource: %w", err)
			}
		default:
			return nil, fmt.Errorf("merge: failed to unserialise prev resource, unxexpected resource type: %T", t)
		}

		switch t := new.(type) {
		case *m.Guardrail:
			n = t
		case *apiv1.ResourceInstance:
			err := n.FromInstance(t)
			if err != nil {
				return nil, fmt.Errorf("merge: failed to unserialize new resource: %w", err)
			}
		default:
			return nil, fmt.Errorf("merge: failed to unserialise new resource, unxexpected resource type: %T", t)
		}

		return f(p, n)
	})
}

// GuardrailClient - rest client for Guardrail resources that have a defined resource scope
type GuardrailClient struct {
	client v1.Scoped
}

// UnscopedGuardrailClient - rest client for Guardrail resources that do not have a defined scope
type UnscopedGuardrailClient struct {
	client v1.Unscoped
}

// NewGuardrailClient - creates a client that is not scoped to any resource
func NewGuardrailClient(c v1.Base) (*UnscopedGuardrailClient, error) {

	client, err := c.ForKind(m.GuardrailGVK())
	if err != nil {
		return nil, err
	}

	return &UnscopedGuardrailClient{client}, nil

}

// WithScope - sets the resource scope for the client
func (c *UnscopedGuardrailClient) WithScope(scope string) *GuardrailClient {
	return &GuardrailClient{
		c.client.WithScope(scope),
	}
}

// Get - gets a resource by name
func (c *UnscopedGuardrailClient) Get(name string) (*m.Guardrail, error) {
	ri, err := c.client.Get(name)
	if err != nil {
		return nil, err
	}

	service := &m.Guardrail{}
	service.FromInstance(ri)

	return service, nil
}

// Update - updates a resource
func (c *UnscopedGuardrailClient) Update(res *m.Guardrail, opts ...v1.UpdateOption) (*m.Guardrail, error) {
	ri, err := res.AsInstance()
	if err != nil {
		return nil, err
	}
	resource, err := c.client.Update(ri, opts...)
	if err != nil {
		return nil, err
	}

	updated := &m.Guardrail{}

	// Updates the resource in place
	err = updated.FromInstance(resource)
	if err != nil {
		return nil, err
	}

	return updated, nil
}

// List - gets a list of resources
func (c *GuardrailClient) List(options ...v1.ListOptions) ([]*m.Guardrail, error) {
	riList, err := c.client.List(options...)
	if err != nil {
		return nil, err
	}

	result := make([]*m.Guardrail, len(riList))

	for i := range riList {
		result[i] = &m.Guardrail{}
		err := result[i].FromInstance(riList[i])
		if err != nil {
			return nil, err
		}
	}

	return result, nil
}

// Get - gets a resource by name
func (c *GuardrailClient) Get(name string) (*m.Guardrail, error) {
	ri, err := c.client.Get(name)
	if err != nil {
		return nil, err
	}

	service := &m.Guardrail{}
	service.FromInstance(ri)

	return service, nil
}

// Delete - deletes a resource
func (c *GuardrailClient) Delete(res *m.Guardrail) error {
	ri, err := res.AsInstance()

	if err != nil {
		return err
	}

	return c.client.Delete(ri)
}

// Create - creates a resource
func (c *GuardrailClient) Create(res *m.Guardrail, opts ...v1.CreateOption) (*m.Guardrail, error) {
	ri, err := res.AsInstance()

	if err != nil {
		return nil, err
	}

	cri, err := c.client.Create(ri, opts...)
	if err != nil {
		return nil, err
	}

	created := &m.Guardrail{}

	err = created.FromInstance(cri)
	if err != nil {
		return nil, err
	}

	return created, err
}

// Update - updates a resource
func (c *GuardrailClient) Update(res *m.Guardrail, opts ...v1.UpdateOption) (*m.Guardrail, error) {
	ri, err := res.AsInstance()
	if err != nil {
		return nil, err
	}
	resource, err := c.client.Update(ri, opts...)
	if err != nil {
		return nil, err
	}

	updated := &m.Guardrail{}

	// Updates the resource in place
	err = updated.FromInstance(resource)
	if err != nil {
		return nil, err
	}

	return updated, nil
}
