/*
 * This file is automatically generated
 */

package management

import (
	"fmt"

	v1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/clients/api/v1"
	apiv1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/api/v1"
	m "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/management/v1"
)

type LLMConnectionMergeFunc func(*m.LLMConnection, *m.LLMConnection) (*m.LLMConnection, error)

// LLMConnectionMerge builds a merge option for an update operation
func LLMConnectionMerge(f LLMConnectionMergeFunc) v1.UpdateOption {
	return v1.Merge(func(prev, new apiv1.Interface) (apiv1.Interface, error) {
		p, n := &m.LLMConnection{}, &m.LLMConnection{}

		switch t := prev.(type) {
		case *m.LLMConnection:
			p = t
		case *apiv1.ResourceInstance:
			err := p.FromInstance(t)
			if err != nil {
				return nil, fmt.Errorf("merge: failed to unserialise prev resource: %w", err)
			}
		default:
			return nil, fmt.Errorf("merge: failed to unserialise prev resource, unxexpected resource type: %T", t)
		}

		switch t := new.(type) {
		case *m.LLMConnection:
			n = t
		case *apiv1.ResourceInstance:
			err := n.FromInstance(t)
			if err != nil {
				return nil, fmt.Errorf("merge: failed to unserialize new resource: %w", err)
			}
		default:
			return nil, fmt.Errorf("merge: failed to unserialise new resource, unxexpected resource type: %T", t)
		}

		return f(p, n)
	})
}

// LLMConnectionClient - rest client for LLMConnection resources that have a defined resource scope
type LLMConnectionClient struct {
	client v1.Scoped
}

// UnscopedLLMConnectionClient - rest client for LLMConnection resources that do not have a defined scope
type UnscopedLLMConnectionClient struct {
	client v1.Unscoped
}

// NewLLMConnectionClient - creates a client that is not scoped to any resource
func NewLLMConnectionClient(c v1.Base) (*UnscopedLLMConnectionClient, error) {

	client, err := c.ForKind(m.LLMConnectionGVK())
	if err != nil {
		return nil, err
	}

	return &UnscopedLLMConnectionClient{client}, nil

}

// WithScope - sets the resource scope for the client
func (c *UnscopedLLMConnectionClient) WithScope(scope string) *LLMConnectionClient {
	return &LLMConnectionClient{
		c.client.WithScope(scope),
	}
}

// Get - gets a resource by name
func (c *UnscopedLLMConnectionClient) Get(name string) (*m.LLMConnection, error) {
	ri, err := c.client.Get(name)
	if err != nil {
		return nil, err
	}

	service := &m.LLMConnection{}
	service.FromInstance(ri)

	return service, nil
}

// Update - updates a resource
func (c *UnscopedLLMConnectionClient) Update(res *m.LLMConnection, opts ...v1.UpdateOption) (*m.LLMConnection, error) {
	ri, err := res.AsInstance()
	if err != nil {
		return nil, err
	}
	resource, err := c.client.Update(ri, opts...)
	if err != nil {
		return nil, err
	}

	updated := &m.LLMConnection{}

	// Updates the resource in place
	err = updated.FromInstance(resource)
	if err != nil {
		return nil, err
	}

	return updated, nil
}

// List - gets a list of resources
func (c *LLMConnectionClient) List(options ...v1.ListOptions) ([]*m.LLMConnection, error) {
	riList, err := c.client.List(options...)
	if err != nil {
		return nil, err
	}

	result := make([]*m.LLMConnection, len(riList))

	for i := range riList {
		result[i] = &m.LLMConnection{}
		err := result[i].FromInstance(riList[i])
		if err != nil {
			return nil, err
		}
	}

	return result, nil
}

// Get - gets a resource by name
func (c *LLMConnectionClient) Get(name string) (*m.LLMConnection, error) {
	ri, err := c.client.Get(name)
	if err != nil {
		return nil, err
	}

	service := &m.LLMConnection{}
	service.FromInstance(ri)

	return service, nil
}

// Delete - deletes a resource
func (c *LLMConnectionClient) Delete(res *m.LLMConnection) error {
	ri, err := res.AsInstance()

	if err != nil {
		return err
	}

	return c.client.Delete(ri)
}

// Create - creates a resource
func (c *LLMConnectionClient) Create(res *m.LLMConnection, opts ...v1.CreateOption) (*m.LLMConnection, error) {
	ri, err := res.AsInstance()

	if err != nil {
		return nil, err
	}

	cri, err := c.client.Create(ri, opts...)
	if err != nil {
		return nil, err
	}

	created := &m.LLMConnection{}

	err = created.FromInstance(cri)
	if err != nil {
		return nil, err
	}

	return created, err
}

// Update - updates a resource
func (c *LLMConnectionClient) Update(res *m.LLMConnection, opts ...v1.UpdateOption) (*m.LLMConnection, error) {
	ri, err := res.AsInstance()
	if err != nil {
		return nil, err
	}
	resource, err := c.client.Update(ri, opts...)
	if err != nil {
		return nil, err
	}

	updated := &m.LLMConnection{}

	// Updates the resource in place
	err = updated.FromInstance(resource)
	if err != nil {
		return nil, err
	}

	return updated, nil
}
