/*
 * API Server specification.
 *
 * API Server specification for Amplify Central.
 *
 * API version: 0.13.0
 * Contact: support@axway.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1

import (
	"time"
)

// v1.ApiV1AuditMetadata Read-only metadata for the record.
type ApiV1AuditMetadata struct {
	// The creation time.
	CreateTimestamp time.Time `json:"createTimestamp,omitempty"`
	// Id of the user that created the entity.
	CreateUserId string `json:"createUserId,omitempty"`
	// The last modification time.
	ModifyTimestamp time.Time `json:"modifyTimestamp,omitempty"`
	// Id of the user that last modified the entity.
	ModifyUserId string `json:"modifyUserId,omitempty"`
}
