/*
 * This file is automatically generated
 */

package v1alpha1

import (
	v1 "git.ecd.axway.org/apigov/apic_agents_sdk/pkg/apic/apiserver/clients/api/v1"
	"git.ecd.axway.org/apigov/apic_agents_sdk/pkg/apic/apiserver/models/mesh/v1alpha1"
)

// ResourceDiscoveryClient -
type ResourceDiscoveryClient struct {
	client v1.Scoped
}

// NewResourceDiscoveryClient -

func NewResourceDiscoveryClient(c v1.Base) (*ResourceDiscoveryClient, error) {

	client, err := c.ForKind(v1alpha1.ResourceDiscoveryGVK())
	if err != nil {
		return nil, err
	}

	return &ResourceDiscoveryClient{client}, nil

}

// List -
func (c *ResourceDiscoveryClient) List(options ...v1.ListOptions) ([]*v1alpha1.ResourceDiscovery, error) {
	riList, err := c.client.List(options...)
	if err != nil {
		return nil, err
	}

	result := make([]*v1alpha1.ResourceDiscovery, len(riList))

	for i := range riList {
		result[i] = &v1alpha1.ResourceDiscovery{}
		err := result[i].FromInstance(riList[i])
		if err != nil {
			return nil, err
		}
	}

	return result, nil
}

// Get -
func (c *ResourceDiscoveryClient) Get(name string) (*v1alpha1.ResourceDiscovery, error) {
	ri, err := c.client.Get(name)
	if err != nil {
		return nil, err
	}

	service := &v1alpha1.ResourceDiscovery{}
	service.FromInstance(ri)

	return service, nil
}

// Delete -
func (c *ResourceDiscoveryClient) Delete(res *v1alpha1.ResourceDiscovery) error {
	ri, err := res.AsInstance()

	if err != nil {
		return err
	}

	return c.client.Delete(ri)
}

// Create -
func (c *ResourceDiscoveryClient) Create(res *v1alpha1.ResourceDiscovery, opts ...v1.CreateOption) (*v1alpha1.ResourceDiscovery, error) {
	ri, err := res.AsInstance()

	if err != nil {
		return nil, err
	}

	cri, err := c.client.Create(ri, opts...)
	if err != nil {
		return nil, err
	}

	created := &v1alpha1.ResourceDiscovery{}

	err = created.FromInstance(cri)
	if err != nil {
		return nil, err
	}

	return created, err
}

// Update -
func (c *ResourceDiscoveryClient) Update(res *v1alpha1.ResourceDiscovery, opts ...v1.UpdateOption) (*v1alpha1.ResourceDiscovery, error) {
	ri, err := res.AsInstance()
	if err != nil {
		return nil, err
	}
	resource, err := c.client.Update(ri, opts...)
	if err != nil {
		return nil, err
	}

	updated := &v1alpha1.ResourceDiscovery{}

	// Updates the resource in place
	err = updated.FromInstance(resource)
	if err != nil {
		return nil, err
	}

	return updated, nil
}
