/*
 * This file is automatically generated
 */

package catalog

import (
	"fmt"

	v1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/clients/api/v1"
	apiv1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/api/v1"
	m "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/catalog/v1alpha1"
)

type AssistedSearchMergeFunc func(*m.AssistedSearch, *m.AssistedSearch) (*m.AssistedSearch, error)

// AssistedSearchMerge builds a merge option for an update operation
func AssistedSearchMerge(f AssistedSearchMergeFunc) v1.UpdateOption {
	return v1.Merge(func(prev, new apiv1.Interface) (apiv1.Interface, error) {
		p, n := &m.AssistedSearch{}, &m.AssistedSearch{}

		switch t := prev.(type) {
		case *m.AssistedSearch:
			p = t
		case *apiv1.ResourceInstance:
			err := p.FromInstance(t)
			if err != nil {
				return nil, fmt.Errorf("merge: failed to unserialise prev resource: %w", err)
			}
		default:
			return nil, fmt.Errorf("merge: failed to unserialise prev resource, unxexpected resource type: %T", t)
		}

		switch t := new.(type) {
		case *m.AssistedSearch:
			n = t
		case *apiv1.ResourceInstance:
			err := n.FromInstance(t)
			if err != nil {
				return nil, fmt.Errorf("merge: failed to unserialize new resource: %w", err)
			}
		default:
			return nil, fmt.Errorf("merge: failed to unserialise new resource, unxexpected resource type: %T", t)
		}

		return f(p, n)
	})
}

// AssistedSearchClient - rest client for AssistedSearch resources that have a defined resource scope
type AssistedSearchClient struct {
	client v1.Scoped
}

// UnscopedAssistedSearchClient - rest client for AssistedSearch resources that do not have a defined scope
type UnscopedAssistedSearchClient struct {
	client v1.Unscoped
}

// NewAssistedSearchClient - creates a client that is not scoped to any resource
func NewAssistedSearchClient(c v1.Base) (*UnscopedAssistedSearchClient, error) {

	client, err := c.ForKind(m.AssistedSearchGVK())
	if err != nil {
		return nil, err
	}

	return &UnscopedAssistedSearchClient{client}, nil

}

// WithScope - sets the resource scope for the client
func (c *UnscopedAssistedSearchClient) WithScope(scope string) *AssistedSearchClient {
	return &AssistedSearchClient{
		c.client.WithScope(scope),
	}
}

// Get - gets a resource by name
func (c *UnscopedAssistedSearchClient) Get(name string) (*m.AssistedSearch, error) {
	ri, err := c.client.Get(name)
	if err != nil {
		return nil, err
	}

	service := &m.AssistedSearch{}
	service.FromInstance(ri)

	return service, nil
}

// Update - updates a resource
func (c *UnscopedAssistedSearchClient) Update(res *m.AssistedSearch, opts ...v1.UpdateOption) (*m.AssistedSearch, error) {
	ri, err := res.AsInstance()
	if err != nil {
		return nil, err
	}
	resource, err := c.client.Update(ri, opts...)
	if err != nil {
		return nil, err
	}

	updated := &m.AssistedSearch{}

	// Updates the resource in place
	err = updated.FromInstance(resource)
	if err != nil {
		return nil, err
	}

	return updated, nil
}

// List - gets a list of resources
func (c *AssistedSearchClient) List(options ...v1.ListOptions) ([]*m.AssistedSearch, error) {
	riList, err := c.client.List(options...)
	if err != nil {
		return nil, err
	}

	result := make([]*m.AssistedSearch, len(riList))

	for i := range riList {
		result[i] = &m.AssistedSearch{}
		err := result[i].FromInstance(riList[i])
		if err != nil {
			return nil, err
		}
	}

	return result, nil
}

// Get - gets a resource by name
func (c *AssistedSearchClient) Get(name string) (*m.AssistedSearch, error) {
	ri, err := c.client.Get(name)
	if err != nil {
		return nil, err
	}

	service := &m.AssistedSearch{}
	service.FromInstance(ri)

	return service, nil
}

// Delete - deletes a resource
func (c *AssistedSearchClient) Delete(res *m.AssistedSearch) error {
	ri, err := res.AsInstance()

	if err != nil {
		return err
	}

	return c.client.Delete(ri)
}

// Create - creates a resource
func (c *AssistedSearchClient) Create(res *m.AssistedSearch, opts ...v1.CreateOption) (*m.AssistedSearch, error) {
	ri, err := res.AsInstance()

	if err != nil {
		return nil, err
	}

	cri, err := c.client.Create(ri, opts...)
	if err != nil {
		return nil, err
	}

	created := &m.AssistedSearch{}

	err = created.FromInstance(cri)
	if err != nil {
		return nil, err
	}

	return created, err
}

// Update - updates a resource
func (c *AssistedSearchClient) Update(res *m.AssistedSearch, opts ...v1.UpdateOption) (*m.AssistedSearch, error) {
	ri, err := res.AsInstance()
	if err != nil {
		return nil, err
	}
	resource, err := c.client.Update(ri, opts...)
	if err != nil {
		return nil, err
	}

	updated := &m.AssistedSearch{}

	// Updates the resource in place
	err = updated.FromInstance(resource)
	if err != nil {
		return nil, err
	}

	return updated, nil
}
