/*
 * This file is automatically generated
 */

package catalog

import (
	"fmt"

	v1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/clients/api/v1"
	apiv1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/api/v1"
	m "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/catalog/v1alpha1"
)

type AuthorizationProfileMergeFunc func(*m.AuthorizationProfile, *m.AuthorizationProfile) (*m.AuthorizationProfile, error)

// AuthorizationProfileMerge builds a merge option for an update operation
func AuthorizationProfileMerge(f AuthorizationProfileMergeFunc) v1.UpdateOption {
	return v1.Merge(func(prev, new apiv1.Interface) (apiv1.Interface, error) {
		p, n := &m.AuthorizationProfile{}, &m.AuthorizationProfile{}

		switch t := prev.(type) {
		case *m.AuthorizationProfile:
			p = t
		case *apiv1.ResourceInstance:
			err := p.FromInstance(t)
			if err != nil {
				return nil, fmt.Errorf("merge: failed to unserialise prev resource: %w", err)
			}
		default:
			return nil, fmt.Errorf("merge: failed to unserialise prev resource, unxexpected resource type: %T", t)
		}

		switch t := new.(type) {
		case *m.AuthorizationProfile:
			n = t
		case *apiv1.ResourceInstance:
			err := n.FromInstance(t)
			if err != nil {
				return nil, fmt.Errorf("merge: failed to unserialize new resource: %w", err)
			}
		default:
			return nil, fmt.Errorf("merge: failed to unserialise new resource, unxexpected resource type: %T", t)
		}

		return f(p, n)
	})
}

// AuthorizationProfileClient - rest client for AuthorizationProfile resources that have a defined resource scope
type AuthorizationProfileClient struct {
	client v1.Scoped
}

// NewAuthorizationProfileClient - creates a client scoped to a particular resource
func NewAuthorizationProfileClient(c v1.Base) (*AuthorizationProfileClient, error) {

	client, err := c.ForKind(m.AuthorizationProfileGVK())
	if err != nil {
		return nil, err
	}

	return &AuthorizationProfileClient{client}, nil

}

// List - gets a list of resources
func (c *AuthorizationProfileClient) List(options ...v1.ListOptions) ([]*m.AuthorizationProfile, error) {
	riList, err := c.client.List(options...)
	if err != nil {
		return nil, err
	}

	result := make([]*m.AuthorizationProfile, len(riList))

	for i := range riList {
		result[i] = &m.AuthorizationProfile{}
		err := result[i].FromInstance(riList[i])
		if err != nil {
			return nil, err
		}
	}

	return result, nil
}

// Get - gets a resource by name
func (c *AuthorizationProfileClient) Get(name string) (*m.AuthorizationProfile, error) {
	ri, err := c.client.Get(name)
	if err != nil {
		return nil, err
	}

	service := &m.AuthorizationProfile{}
	service.FromInstance(ri)

	return service, nil
}

// Delete - deletes a resource
func (c *AuthorizationProfileClient) Delete(res *m.AuthorizationProfile) error {
	ri, err := res.AsInstance()

	if err != nil {
		return err
	}

	return c.client.Delete(ri)
}

// Create - creates a resource
func (c *AuthorizationProfileClient) Create(res *m.AuthorizationProfile, opts ...v1.CreateOption) (*m.AuthorizationProfile, error) {
	ri, err := res.AsInstance()

	if err != nil {
		return nil, err
	}

	cri, err := c.client.Create(ri, opts...)
	if err != nil {
		return nil, err
	}

	created := &m.AuthorizationProfile{}

	err = created.FromInstance(cri)
	if err != nil {
		return nil, err
	}

	return created, err
}

// Update - updates a resource
func (c *AuthorizationProfileClient) Update(res *m.AuthorizationProfile, opts ...v1.UpdateOption) (*m.AuthorizationProfile, error) {
	ri, err := res.AsInstance()
	if err != nil {
		return nil, err
	}
	resource, err := c.client.Update(ri, opts...)
	if err != nil {
		return nil, err
	}

	updated := &m.AuthorizationProfile{}

	// Updates the resource in place
	err = updated.FromInstance(resource)
	if err != nil {
		return nil, err
	}

	return updated, nil
}
