/*
 * This file is automatically generated
 */

package v1alpha1

import (
	"fmt"

	v1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/clients/api/v1"
	apiv1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/api/v1"
	m "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/catalog/v1alpha1"
)

type ProductPlanUnitMergeFunc func(*m.ProductPlanUnit, *m.ProductPlanUnit) (*m.ProductPlanUnit, error)

// ProductPlanUnitMerge builds a merge option for an update operation
func ProductPlanUnitMerge(f ProductPlanUnitMergeFunc) v1.UpdateOption {
	return v1.Merge(func(prev, new apiv1.Interface) (apiv1.Interface, error) {
		p, n := &m.ProductPlanUnit{}, &m.ProductPlanUnit{}

		switch t := prev.(type) {
		case *m.ProductPlanUnit:
			p = t
		case *apiv1.ResourceInstance:
			err := p.FromInstance(t)
			if err != nil {
				return nil, fmt.Errorf("merge: failed to unserialise prev resource: %w", err)
			}
		default:
			return nil, fmt.Errorf("merge: failed to unserialise prev resource, unxexpected resource type: %T", t)
		}

		switch t := new.(type) {
		case *m.ProductPlanUnit:
			n = t
		case *apiv1.ResourceInstance:
			err := n.FromInstance(t)
			if err != nil {
				return nil, fmt.Errorf("merge: failed to unserialize new resource: %w", err)
			}
		default:
			return nil, fmt.Errorf("merge: failed to unserialise new resource, unxexpected resource type: %T", t)
		}

		return f(p, n)
	})
}

// ProductPlanUnitClient - rest client for ProductPlanUnit resources that have a defined resource scope
type ProductPlanUnitClient struct {
	client v1.Scoped
}

// NewProductPlanUnitClient - creates a client scoped to a particular resource
func NewProductPlanUnitClient(c v1.Base) (*ProductPlanUnitClient, error) {

	client, err := c.ForKind(m.ProductPlanUnitGVK())
	if err != nil {
		return nil, err
	}

	return &ProductPlanUnitClient{client}, nil

}

// List - gets a list of resources
func (c *ProductPlanUnitClient) List(options ...v1.ListOptions) ([]*m.ProductPlanUnit, error) {
	riList, err := c.client.List(options...)
	if err != nil {
		return nil, err
	}

	result := make([]*m.ProductPlanUnit, len(riList))

	for i := range riList {
		result[i] = &m.ProductPlanUnit{}
		err := result[i].FromInstance(riList[i])
		if err != nil {
			return nil, err
		}
	}

	return result, nil
}

// Get - gets a resource by name
func (c *ProductPlanUnitClient) Get(name string) (*m.ProductPlanUnit, error) {
	ri, err := c.client.Get(name)
	if err != nil {
		return nil, err
	}

	service := &m.ProductPlanUnit{}
	service.FromInstance(ri)

	return service, nil
}

// Delete - deletes a resource
func (c *ProductPlanUnitClient) Delete(res *m.ProductPlanUnit) error {
	ri, err := res.AsInstance()

	if err != nil {
		return err
	}

	return c.client.Delete(ri)
}

// Create - creates a resource
func (c *ProductPlanUnitClient) Create(res *m.ProductPlanUnit, opts ...v1.CreateOption) (*m.ProductPlanUnit, error) {
	ri, err := res.AsInstance()

	if err != nil {
		return nil, err
	}

	cri, err := c.client.Create(ri, opts...)
	if err != nil {
		return nil, err
	}

	created := &m.ProductPlanUnit{}

	err = created.FromInstance(cri)
	if err != nil {
		return nil, err
	}

	return created, err
}

// Update - updates a resource
func (c *ProductPlanUnitClient) Update(res *m.ProductPlanUnit, opts ...v1.UpdateOption) (*m.ProductPlanUnit, error) {
	ri, err := res.AsInstance()
	if err != nil {
		return nil, err
	}
	resource, err := c.client.Update(ri, opts...)
	if err != nil {
		return nil, err
	}

	updated := &m.ProductPlanUnit{}

	// Updates the resource in place
	err = updated.FromInstance(resource)
	if err != nil {
		return nil, err
	}

	return updated, nil
}
