/*
 * This file is automatically generated
 */

package catalog

import (
	"fmt"

	v1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/clients/api/v1"
	apiv1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/api/v1"
	m "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/catalog/v1alpha1"
)

type PublishedProductMergeFunc func(*m.PublishedProduct, *m.PublishedProduct) (*m.PublishedProduct, error)

// PublishedProductMerge builds a merge option for an update operation
func PublishedProductMerge(f PublishedProductMergeFunc) v1.UpdateOption {
	return v1.Merge(func(prev, new apiv1.Interface) (apiv1.Interface, error) {
		p, n := &m.PublishedProduct{}, &m.PublishedProduct{}

		switch t := prev.(type) {
		case *m.PublishedProduct:
			p = t
		case *apiv1.ResourceInstance:
			err := p.FromInstance(t)
			if err != nil {
				return nil, fmt.Errorf("merge: failed to unserialise prev resource: %w", err)
			}
		default:
			return nil, fmt.Errorf("merge: failed to unserialise prev resource, unxexpected resource type: %T", t)
		}

		switch t := new.(type) {
		case *m.PublishedProduct:
			n = t
		case *apiv1.ResourceInstance:
			err := n.FromInstance(t)
			if err != nil {
				return nil, fmt.Errorf("merge: failed to unserialize new resource: %w", err)
			}
		default:
			return nil, fmt.Errorf("merge: failed to unserialise new resource, unxexpected resource type: %T", t)
		}

		return f(p, n)
	})
}

// PublishedProductClient - rest client for PublishedProduct resources that have a defined resource scope
type PublishedProductClient struct {
	client v1.Scoped
}

// UnscopedPublishedProductClient - rest client for PublishedProduct resources that do not have a defined scope
type UnscopedPublishedProductClient struct {
	client v1.Unscoped
}

// NewPublishedProductClient - creates a client that is not scoped to any resource
func NewPublishedProductClient(c v1.Base) (*UnscopedPublishedProductClient, error) {

	client, err := c.ForKind(m.PublishedProductGVK())
	if err != nil {
		return nil, err
	}

	return &UnscopedPublishedProductClient{client}, nil

}

// WithScope - sets the resource scope for the client
func (c *UnscopedPublishedProductClient) WithScope(scope string) *PublishedProductClient {
	return &PublishedProductClient{
		c.client.WithScope(scope),
	}
}

// Get - gets a resource by name
func (c *UnscopedPublishedProductClient) Get(name string) (*m.PublishedProduct, error) {
	ri, err := c.client.Get(name)
	if err != nil {
		return nil, err
	}

	service := &m.PublishedProduct{}
	service.FromInstance(ri)

	return service, nil
}

// Update - updates a resource
func (c *UnscopedPublishedProductClient) Update(res *m.PublishedProduct, opts ...v1.UpdateOption) (*m.PublishedProduct, error) {
	ri, err := res.AsInstance()
	if err != nil {
		return nil, err
	}
	resource, err := c.client.Update(ri, opts...)
	if err != nil {
		return nil, err
	}

	updated := &m.PublishedProduct{}

	// Updates the resource in place
	err = updated.FromInstance(resource)
	if err != nil {
		return nil, err
	}

	return updated, nil
}

// List - gets a list of resources
func (c *PublishedProductClient) List(options ...v1.ListOptions) ([]*m.PublishedProduct, error) {
	riList, err := c.client.List(options...)
	if err != nil {
		return nil, err
	}

	result := make([]*m.PublishedProduct, len(riList))

	for i := range riList {
		result[i] = &m.PublishedProduct{}
		err := result[i].FromInstance(riList[i])
		if err != nil {
			return nil, err
		}
	}

	return result, nil
}

// Get - gets a resource by name
func (c *PublishedProductClient) Get(name string) (*m.PublishedProduct, error) {
	ri, err := c.client.Get(name)
	if err != nil {
		return nil, err
	}

	service := &m.PublishedProduct{}
	service.FromInstance(ri)

	return service, nil
}

// Delete - deletes a resource
func (c *PublishedProductClient) Delete(res *m.PublishedProduct) error {
	ri, err := res.AsInstance()

	if err != nil {
		return err
	}

	return c.client.Delete(ri)
}

// Create - creates a resource
func (c *PublishedProductClient) Create(res *m.PublishedProduct, opts ...v1.CreateOption) (*m.PublishedProduct, error) {
	ri, err := res.AsInstance()

	if err != nil {
		return nil, err
	}

	cri, err := c.client.Create(ri, opts...)
	if err != nil {
		return nil, err
	}

	created := &m.PublishedProduct{}

	err = created.FromInstance(cri)
	if err != nil {
		return nil, err
	}

	return created, err
}

// Update - updates a resource
func (c *PublishedProductClient) Update(res *m.PublishedProduct, opts ...v1.UpdateOption) (*m.PublishedProduct, error) {
	ri, err := res.AsInstance()
	if err != nil {
		return nil, err
	}
	resource, err := c.client.Update(ri, opts...)
	if err != nil {
		return nil, err
	}

	updated := &m.PublishedProduct{}

	// Updates the resource in place
	err = updated.FromInstance(resource)
	if err != nil {
		return nil, err
	}

	return updated, nil
}
