/*
 * This file is automatically generated
 */

package catalog

import (
	"fmt"

	v1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/clients/api/v1"
	apiv1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/api/v1"
	m "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/catalog/v1alpha1"
)

type ReleaseTagMergeFunc func(*m.ReleaseTag, *m.ReleaseTag) (*m.ReleaseTag, error)

// ReleaseTagMerge builds a merge option for an update operation
func ReleaseTagMerge(f ReleaseTagMergeFunc) v1.UpdateOption {
	return v1.Merge(func(prev, new apiv1.Interface) (apiv1.Interface, error) {
		p, n := &m.ReleaseTag{}, &m.ReleaseTag{}

		switch t := prev.(type) {
		case *m.ReleaseTag:
			p = t
		case *apiv1.ResourceInstance:
			err := p.FromInstance(t)
			if err != nil {
				return nil, fmt.Errorf("merge: failed to unserialise prev resource: %w", err)
			}
		default:
			return nil, fmt.Errorf("merge: failed to unserialise prev resource, unxexpected resource type: %T", t)
		}

		switch t := new.(type) {
		case *m.ReleaseTag:
			n = t
		case *apiv1.ResourceInstance:
			err := n.FromInstance(t)
			if err != nil {
				return nil, fmt.Errorf("merge: failed to unserialize new resource: %w", err)
			}
		default:
			return nil, fmt.Errorf("merge: failed to unserialise new resource, unxexpected resource type: %T", t)
		}

		return f(p, n)
	})
}

// ReleaseTagClient - rest client for ReleaseTag resources that have a defined resource scope
type ReleaseTagClient struct {
	client v1.Scoped
}

// UnscopedReleaseTagClient - rest client for ReleaseTag resources that do not have a defined scope
type UnscopedReleaseTagClient struct {
	client v1.Unscoped
}

// NewReleaseTagClient - creates a client that is not scoped to any resource
func NewReleaseTagClient(c v1.Base) (*UnscopedReleaseTagClient, error) {

	client, err := c.ForKind(m.ReleaseTagGVK())
	if err != nil {
		return nil, err
	}

	return &UnscopedReleaseTagClient{client}, nil

}

// WithScope - sets the resource scope for the client
func (c *UnscopedReleaseTagClient) WithScope(scope string) *ReleaseTagClient {
	return &ReleaseTagClient{
		c.client.WithScope(scope),
	}
}

// Get - gets a resource by name
func (c *UnscopedReleaseTagClient) Get(name string) (*m.ReleaseTag, error) {
	ri, err := c.client.Get(name)
	if err != nil {
		return nil, err
	}

	service := &m.ReleaseTag{}
	service.FromInstance(ri)

	return service, nil
}

// Update - updates a resource
func (c *UnscopedReleaseTagClient) Update(res *m.ReleaseTag, opts ...v1.UpdateOption) (*m.ReleaseTag, error) {
	ri, err := res.AsInstance()
	if err != nil {
		return nil, err
	}
	resource, err := c.client.Update(ri, opts...)
	if err != nil {
		return nil, err
	}

	updated := &m.ReleaseTag{}

	// Updates the resource in place
	err = updated.FromInstance(resource)
	if err != nil {
		return nil, err
	}

	return updated, nil
}

// List - gets a list of resources
func (c *ReleaseTagClient) List(options ...v1.ListOptions) ([]*m.ReleaseTag, error) {
	riList, err := c.client.List(options...)
	if err != nil {
		return nil, err
	}

	result := make([]*m.ReleaseTag, len(riList))

	for i := range riList {
		result[i] = &m.ReleaseTag{}
		err := result[i].FromInstance(riList[i])
		if err != nil {
			return nil, err
		}
	}

	return result, nil
}

// Get - gets a resource by name
func (c *ReleaseTagClient) Get(name string) (*m.ReleaseTag, error) {
	ri, err := c.client.Get(name)
	if err != nil {
		return nil, err
	}

	service := &m.ReleaseTag{}
	service.FromInstance(ri)

	return service, nil
}

// Delete - deletes a resource
func (c *ReleaseTagClient) Delete(res *m.ReleaseTag) error {
	ri, err := res.AsInstance()

	if err != nil {
		return err
	}

	return c.client.Delete(ri)
}

// Create - creates a resource
func (c *ReleaseTagClient) Create(res *m.ReleaseTag, opts ...v1.CreateOption) (*m.ReleaseTag, error) {
	ri, err := res.AsInstance()

	if err != nil {
		return nil, err
	}

	cri, err := c.client.Create(ri, opts...)
	if err != nil {
		return nil, err
	}

	created := &m.ReleaseTag{}

	err = created.FromInstance(cri)
	if err != nil {
		return nil, err
	}

	return created, err
}

// Update - updates a resource
func (c *ReleaseTagClient) Update(res *m.ReleaseTag, opts ...v1.UpdateOption) (*m.ReleaseTag, error) {
	ri, err := res.AsInstance()
	if err != nil {
		return nil, err
	}
	resource, err := c.client.Update(ri, opts...)
	if err != nil {
		return nil, err
	}

	updated := &m.ReleaseTag{}

	// Updates the resource in place
	err = updated.FromInstance(resource)
	if err != nil {
		return nil, err
	}

	return updated, nil
}
