@startuml
participant Environment as env
participant SDK as sdk 
participant Agent as agent

'Provision Credential
group Credential Provisioning
env -> sdk: Credential Create Event
activate sdk
sdk --> sdk: isPending
sdk -> env: Get refereneced Managed Application
sdk -> env: Get refereneced Credential Request Definition

sdk -> agent: CredentialProvision
activate agent

agent --> sdk: Get Application Name  - GetApplicationName()
agent --> sdk: Get details on Application  - GetApplicationDetailsValue(key)
agent --> sdk: Get credential request data - GetCredentialData()
agent --> agent: Handle provisioning of Credential
note over agent: Set credential data using Credential Builder
note over agent: Add properties necessary to deprovision

agent -> sdk: success
activate sdk #green
note right sdk: Get encryption data from Managed Application
sdk -> sdk: Encrypt fields based on Credential Request Definition

sdk -> env: Update Credential Success
deactivate sdk
note left sdk: Add credential data, with encrypted fields
note left sdk: Add properties from agent to resource

agent -> sdk: fail
deactivate agent
activate sdk #red

sdk -> env: Update Credential Fail
deactivate sdk

deactivate sdk
end

'Deprovision Credential
group Credential Deprovisioning
env -> sdk: Credential Update Event
activate sdk
sdk --> sdk: isDeleting
sdk <-> env: Get all properties

sdk -> agent: CredentialDeprovision
activate agent

agent --> sdk: Get details on Credential  - GetCredentialDetailsValue(key)
agent --> agent: Handle deprovisioning of Credential

agent -> sdk: success
activate sdk #green

sdk -> env: Update Credential, allowing resource removal
deactivate sdk

agent -> sdk: fail
deactivate agent
activate sdk #red

sdk -> env: UpdateCredential Fail
deactivate sdk

deactivate sdk
end

'Update Credential
group Credentail Updating
env -> sdk: Credential Update Event
activate sdk
sdk --> sdk: isPending and (isRotate or isStateUpdate)
sdk -> env: Get refereneced Managed Application
sdk -> env: Get refereneced Credential Request Definition
sdk --> sdk: Set Credential Action

sdk -> agent: CredentialUpdate
activate agent

agent --> sdk: Get Application Name  - GetApplicationName()
agent --> sdk: Get details on Application  - GetApplicationDetailsValue(key)
agent --> sdk: Get credential request data - GetCredentialData()
agent --> sdk: Get details on Credential  - GetDetailsValue(key)
agent --> sdk: Get update action  - GetCredentialAction()
agent --> agent: Handle updating of Credential
note over agent: Update credential data using Credential Builder
note over agent: Update properties necessary to deprovision

agent -> sdk: success
activate sdk #green
note right sdk: Get encryption data from Managed Application
sdk -> sdk: Encrypt fields based on Credential Request Definition

sdk -> env: Update Credential Success
deactivate sdk
note left sdk: Add credential data, with encrypted fields
note left sdk: Add properties from agent to resource

agent -> sdk: fail
deactivate agent
activate sdk #red

sdk -> env: Update Credential Fail
deactivate sdk

deactivate sdk
end
@enduml
