/*
 * This file is automatically generated
 */

package catalog

import (
	"encoding/json"

	apiv1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/api/v1"

	"github.com/Axway/agent-sdk/pkg/util/log"
)

var (
	AssetRequestCtx log.ContextField = "assetRequest"

	_AssetRequestGVK = apiv1.GroupVersionKind{
		GroupKind: apiv1.GroupKind{
			Group: "catalog",
			Kind:  "AssetRequest",
		},
		APIVersion: "v1alpha1",
	}

	AssetRequestScopes = []string{"Application"}
)

const (
	AssetRequestResourceName               = "assetrequests"
	AssetRequest_embeddedSubResourceName   = "_embedded"
	AssetRequestApprovalSubResourceName    = "approval"
	AssetRequestDataSubResourceName        = "data"
	AssetRequestMarketplaceSubResourceName = "marketplace"
	AssetRequestReferencesSubResourceName  = "references"
	AssetRequestStatusSubResourceName      = "status"
)

func AssetRequestGVK() apiv1.GroupVersionKind {
	return _AssetRequestGVK
}

func init() {
	apiv1.RegisterGVK(_AssetRequestGVK, AssetRequestScopes[0], AssetRequestResourceName)
	log.RegisterContextField(AssetRequestCtx)
}

// AssetRequest Resource
type AssetRequest struct {
	apiv1.ResourceMeta
	_embedded   interface{}             `json:"_embedded"`
	Approval    AssetRequestApproval    `json:"approval"`
	Data        interface{}             `json:"data"`
	Marketplace AssetRequestMarketplace `json:"marketplace"`
	Owner       *apiv1.Owner            `json:"owner"`
	References  AssetRequestReferences  `json:"references"`
	Spec        AssetRequestSpec        `json:"spec"`
	// Status      AssetRequestStatus      `json:"status"`
	Status *apiv1.ResourceStatus `json:"status"`
}

// NewAssetRequest creates an empty *AssetRequest
func NewAssetRequest(name, scopeName string) *AssetRequest {
	return &AssetRequest{
		ResourceMeta: apiv1.ResourceMeta{
			Name:             name,
			GroupVersionKind: _AssetRequestGVK,
			Metadata: apiv1.Metadata{
				Scope: apiv1.MetadataScope{
					Name: scopeName,
					Kind: AssetRequestScopes[0],
				},
			},
		},
	}
}

// AssetRequestFromInstanceArray converts a []*ResourceInstance to a []*AssetRequest
func AssetRequestFromInstanceArray(fromArray []*apiv1.ResourceInstance) ([]*AssetRequest, error) {
	newArray := make([]*AssetRequest, 0)
	for _, item := range fromArray {
		res := &AssetRequest{}
		err := res.FromInstance(item)
		if err != nil {
			return make([]*AssetRequest, 0), err
		}
		newArray = append(newArray, res)
	}

	return newArray, nil
}

// AsInstance converts a AssetRequest to a ResourceInstance
func (res *AssetRequest) AsInstance() (*apiv1.ResourceInstance, error) {
	meta := res.ResourceMeta
	meta.GroupVersionKind = AssetRequestGVK()
	res.ResourceMeta = meta

	m, err := json.Marshal(res)
	if err != nil {
		return nil, err
	}

	instance := apiv1.ResourceInstance{}
	err = json.Unmarshal(m, &instance)
	if err != nil {
		return nil, err
	}

	return &instance, nil
}

// FromInstance converts a ResourceInstance to a AssetRequest
func (res *AssetRequest) FromInstance(ri *apiv1.ResourceInstance) error {
	if ri == nil {
		res = nil
		return nil
	}
	var err error
	rawResource := ri.GetRawResource()
	if rawResource == nil {
		rawResource, err = json.Marshal(ri)
		if err != nil {
			return err
		}
	}
	err = json.Unmarshal(rawResource, res)
	return err
}

// MarshalJSON custom marshaller to handle sub resources
func (res *AssetRequest) MarshalJSON() ([]byte, error) {
	m, err := json.Marshal(&res.ResourceMeta)
	if err != nil {
		return nil, err
	}

	var out map[string]interface{}
	err = json.Unmarshal(m, &out)
	if err != nil {
		return nil, err
	}

	out["_embedded"] = res._embedded
	out["approval"] = res.Approval
	out["data"] = res.Data
	out["marketplace"] = res.Marketplace
	out["owner"] = res.Owner
	out["references"] = res.References
	out["spec"] = res.Spec
	out["status"] = res.Status

	return json.Marshal(out)
}

// UnmarshalJSON custom unmarshaller to handle sub resources
func (res *AssetRequest) UnmarshalJSON(data []byte) error {
	var err error

	aux := &apiv1.ResourceInstance{}
	err = json.Unmarshal(data, aux)
	if err != nil {
		return err
	}

	res.ResourceMeta = aux.ResourceMeta
	res.Owner = aux.Owner

	// ResourceInstance holds the spec as a map[string]interface{}.
	// Convert it to bytes, then convert to the spec type for the resource.
	sr, err := json.Marshal(aux.Spec)
	if err != nil {
		return err
	}

	err = json.Unmarshal(sr, &res.Spec)
	if err != nil {
		return err
	}

	// marshalling subresource _embedded
	if v, ok := aux.SubResources["_embedded"]; ok {
		sr, err = json.Marshal(v)
		if err != nil {
			return err
		}

		delete(aux.SubResources, "_embedded")
		err = json.Unmarshal(sr, &res._embedded)
		if err != nil {
			return err
		}
	}

	// marshalling subresource Approval
	if v, ok := aux.SubResources["approval"]; ok {
		sr, err = json.Marshal(v)
		if err != nil {
			return err
		}

		delete(aux.SubResources, "approval")
		err = json.Unmarshal(sr, &res.Approval)
		if err != nil {
			return err
		}
	}

	// marshalling subresource Data
	if v, ok := aux.SubResources["data"]; ok {
		sr, err = json.Marshal(v)
		if err != nil {
			return err
		}

		delete(aux.SubResources, "data")
		err = json.Unmarshal(sr, &res.Data)
		if err != nil {
			return err
		}
	}

	// marshalling subresource Marketplace
	if v, ok := aux.SubResources["marketplace"]; ok {
		sr, err = json.Marshal(v)
		if err != nil {
			return err
		}

		delete(aux.SubResources, "marketplace")
		err = json.Unmarshal(sr, &res.Marketplace)
		if err != nil {
			return err
		}
	}

	// marshalling subresource References
	if v, ok := aux.SubResources["references"]; ok {
		sr, err = json.Marshal(v)
		if err != nil {
			return err
		}

		delete(aux.SubResources, "references")
		err = json.Unmarshal(sr, &res.References)
		if err != nil {
			return err
		}
	}

	// marshalling subresource Status
	if v, ok := aux.SubResources["status"]; ok {
		sr, err = json.Marshal(v)
		if err != nil {
			return err
		}

		delete(aux.SubResources, "status")
		// err = json.Unmarshal(sr, &res.Status)
		res.Status = &apiv1.ResourceStatus{}
		err = json.Unmarshal(sr, res.Status)
		if err != nil {
			return err
		}
	}

	return nil
}

// PluralName returns the plural name of the resource
func (res *AssetRequest) PluralName() string {
	return AssetRequestResourceName
}
