/*
 * This file is automatically generated
 */

package catalog

import (
	"encoding/json"

	apiv1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/api/v1"

	"github.com/Axway/agent-sdk/pkg/util/log"
)

var (
	CategoryVisibilityCtx log.ContextField = "categoryVisibility"

	_CategoryVisibilityGVK = apiv1.GroupVersionKind{
		GroupKind: apiv1.GroupKind{
			Group: "catalog",
			Kind:  "CategoryVisibility",
		},
		APIVersion: "v1alpha1",
	}

	CategoryVisibilityScopes = []string{"Marketplace"}
)

const (
	CategoryVisibilityResourceName = "categoryvisibility"
)

func CategoryVisibilityGVK() apiv1.GroupVersionKind {
	return _CategoryVisibilityGVK
}

func init() {
	apiv1.RegisterGVK(_CategoryVisibilityGVK, CategoryVisibilityScopes[0], CategoryVisibilityResourceName)
	log.RegisterContextField(CategoryVisibilityCtx)
}

// CategoryVisibility Resource
type CategoryVisibility struct {
	apiv1.ResourceMeta
	Owner *apiv1.Owner           `json:"owner"`
	Spec  CategoryVisibilitySpec `json:"spec"`
}

// NewCategoryVisibility creates an empty *CategoryVisibility
func NewCategoryVisibility(name, scopeName string) *CategoryVisibility {
	return &CategoryVisibility{
		ResourceMeta: apiv1.ResourceMeta{
			Name:             name,
			GroupVersionKind: _CategoryVisibilityGVK,
			Metadata: apiv1.Metadata{
				Scope: apiv1.MetadataScope{
					Name: scopeName,
					Kind: CategoryVisibilityScopes[0],
				},
			},
		},
	}
}

// CategoryVisibilityFromInstanceArray converts a []*ResourceInstance to a []*CategoryVisibility
func CategoryVisibilityFromInstanceArray(fromArray []*apiv1.ResourceInstance) ([]*CategoryVisibility, error) {
	newArray := make([]*CategoryVisibility, 0)
	for _, item := range fromArray {
		res := &CategoryVisibility{}
		err := res.FromInstance(item)
		if err != nil {
			return make([]*CategoryVisibility, 0), err
		}
		newArray = append(newArray, res)
	}

	return newArray, nil
}

// AsInstance converts a CategoryVisibility to a ResourceInstance
func (res *CategoryVisibility) AsInstance() (*apiv1.ResourceInstance, error) {
	meta := res.ResourceMeta
	meta.GroupVersionKind = CategoryVisibilityGVK()
	res.ResourceMeta = meta

	m, err := json.Marshal(res)
	if err != nil {
		return nil, err
	}

	instance := apiv1.ResourceInstance{}
	err = json.Unmarshal(m, &instance)
	if err != nil {
		return nil, err
	}
	instance.SubResourceHashes = res.SubResourceHashes
	return &instance, nil
}

// FromInstance converts a ResourceInstance to a CategoryVisibility
func (res *CategoryVisibility) FromInstance(ri *apiv1.ResourceInstance) error {
	if ri == nil {
		res = nil
		return nil
	}
	var err error
	rawResource := ri.GetRawResource()
	if rawResource == nil {
		rawResource, err = json.Marshal(ri)
		if err != nil {
			return err
		}
	}
	err = json.Unmarshal(rawResource, res)
	if err != nil {
		return err
	}
	res.SubResourceHashes = ri.SubResourceHashes
	return err
}

// MarshalJSON custom marshaller to handle sub resources
func (res *CategoryVisibility) MarshalJSON() ([]byte, error) {
	m, err := json.Marshal(&res.ResourceMeta)
	if err != nil {
		return nil, err
	}

	var out map[string]interface{}
	err = json.Unmarshal(m, &out)
	if err != nil {
		return nil, err
	}

	out["owner"] = res.Owner
	out["spec"] = res.Spec

	return json.Marshal(out)
}

// UnmarshalJSON custom unmarshaller to handle sub resources
func (res *CategoryVisibility) UnmarshalJSON(data []byte) error {
	var err error

	aux := &apiv1.ResourceInstance{}
	err = json.Unmarshal(data, aux)
	if err != nil {
		return err
	}

	res.ResourceMeta = aux.ResourceMeta
	res.Owner = aux.Owner

	// ResourceInstance holds the spec as a map[string]interface{}.
	// Convert it to bytes, then convert to the spec type for the resource.
	sr, err := json.Marshal(aux.Spec)
	if err != nil {
		return err
	}

	err = json.Unmarshal(sr, &res.Spec)
	if err != nil {
		return err
	}

	return nil
}

// PluralName returns the plural name of the resource
func (res *CategoryVisibility) PluralName() string {
	return CategoryVisibilityResourceName
}
