/*
 * This file is automatically generated
 */

package v1alpha1

import (
	"encoding/json"

	apiv1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/api/v1"
)

var (
	_DocumentGVK = apiv1.GroupVersionKind{
		GroupKind: apiv1.GroupKind{
			Group: "catalog",
			Kind:  "Document",
		},
		APIVersion: "v1alpha1",
	}

	DocumentScopes = []string{"Product", "ProductRelease"}
)

const DocumentResourceName = "documents"

func DocumentGVK() apiv1.GroupVersionKind {
	return _DocumentGVK
}

func init() {
	apiv1.RegisterGVK(_DocumentGVK, DocumentScopes[0], DocumentResourceName)
}

// Document Resource
type Document struct {
	apiv1.ResourceMeta

	Icon interface{} `json:"icon"`

	Owner *apiv1.Owner `json:"owner"`

	Spec DocumentSpec `json:"spec"`

	Status DocumentStatus `json:"status"`
}

// FromInstance converts a ResourceInstance to a Document
func (res *Document) FromInstance(ri *apiv1.ResourceInstance) error {
	if ri == nil {
		res = nil
		return nil
	}

	var err error
	rawResource := ri.GetRawResource()
	if rawResource == nil {
		rawResource, err = json.Marshal(ri)
		if err != nil {
			return err
		}
	}

	err = json.Unmarshal(rawResource, res)
	return err
}

// DocumentFromInstanceArray converts a []*ResourceInstance to a []*Document
func DocumentFromInstanceArray(fromArray []*apiv1.ResourceInstance) ([]*Document, error) {
	newArray := make([]*Document, 0)
	for _, item := range fromArray {
		res := &Document{}
		err := res.FromInstance(item)
		if err != nil {
			return make([]*Document, 0), err
		}
		newArray = append(newArray, res)
	}

	return newArray, nil
}

// AsInstance converts a Document to a ResourceInstance
func (res *Document) AsInstance() (*apiv1.ResourceInstance, error) {
	meta := res.ResourceMeta
	meta.GroupVersionKind = DocumentGVK()
	res.ResourceMeta = meta

	m, err := json.Marshal(res)
	if err != nil {
		return nil, err
	}

	instance := apiv1.ResourceInstance{}
	err = json.Unmarshal(m, &instance)
	if err != nil {
		return nil, err
	}

	return &instance, nil
}
