/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package catalog

// PublishedDocumentResourceSpecDocumentResource  (catalog.v1alpha1.PublishedDocumentResource)
type PublishedDocumentResourceSpecDocumentResource struct {
	Name string `json:"name"`
}
