/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package catalog

// SubscriptionInvoiceSpec struct for SubscriptionInvoiceSpec
type SubscriptionInvoiceSpec struct {
	Cost   SubscriptionInvoiceSpecCost     `json:"cost,omitempty"`
	Period SubscriptionInvoiceSpecPeriod   `json:"period,omitempty"`
	Quotas []SubscriptionInvoiceSpecQuotas `json:"quotas,omitempty"`
}
