/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package catalog

// AssetSpecAutoRelease Defines if an asset should create releases everytime there is an update to the resources.
type AssetSpecAutoRelease struct {
	ReleaseType string `json:"releaseType"`
	// Set true to suspend auto-release until asset state changes to active or deprecated. This property will be automatically removed once activated.
	RequiresInitialActivation bool                                 `json:"requiresInitialActivation,omitempty"`
	PreviousReleases          AssetSpecAutoReleasePreviousReleases `json:"previousReleases,omitempty"`
}
