/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1alpha1

// SubscriptionSpecPlanSetup struct for SubscriptionSpecPlanSetup
type SubscriptionSpecPlanSetup struct {
	// data requested by the Product owner (matching the Plan.spec.subscription.form field).
	Form map[string]interface{} `json:"form,omitempty"`
}
