/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package catalog

// ProductPlanSpecBillingInvoices Invoice actions to be performed. (catalog.v1alpha1.ProductPlan)
type ProductPlanSpecBillingInvoices struct {
	// Actions on paid subscription to be performed based on invoices.
	Actions []ProductPlanSpecBillingInvoicesActions `json:"actions"`
}
