/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package catalog

// SubscriptionJobSpec  (catalog.v1alpha1.SubscriptionJob)
type SubscriptionJobSpec struct {
	// GENERATE: The following code has been modified after code generation
	Action      interface{}                    `json:"action"`
	When        SubscriptionJobSpecWhen        `json:"when,omitempty"`
	PostExecute SubscriptionJobSpecPostExecute `json:"postExecute,omitempty"`
}
