/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package catalog

// SubscriptionInvoiceMarketplaceResource The Marketplace Subscription Invoice resource details.
type SubscriptionInvoiceMarketplaceResource struct {
	Owner SubscriptionInvoiceMarketplaceResourceOwner `json:"owner,omitempty"`
}
