/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package catalog

// SubscriptionInvoiceMarketplace Details about the marketplace Subscription invoice.
type SubscriptionInvoiceMarketplace struct {
	// The name of the Marketplace.
	Name     string                                 `json:"name"`
	Resource SubscriptionInvoiceMarketplaceResource `json:"resource"`
}
