/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package catalog

// AssistedSearchState Current state of the integration. The integration can get to be disabled if resources quota is reached.
type AssistedSearchState struct {
	Name string `json:"name,omitempty"`
	// Additional info on the state.
	Reason string `json:"reason,omitempty"`
}
