/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package catalog

// PublishedProductSpecGroupByAssetTitle struct for PublishedProductSpecGroupByAssetTitle
type PublishedProductSpecGroupByAssetTitle struct {
	Type string `json:"type"`
}
