/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1alpha1

// SubscriptionRequest the model 'SubscriptionRequest'
type SubscriptionRequest string

// List of SubscriptionRequest
const (
	// GENERATE: The following code has been modified after code generation
	SubscriptionRequestPROVISION SubscriptionRequest = "provision"
	// GENERATE: The following code has been modified after code generation
	SubscriptionRequestRENEW SubscriptionRequest = "renew"
)
