/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package catalog

// AssetSpecAutoReleasePreviousReleases struct for AssetSpecAutoReleasePreviousReleases
type AssetSpecAutoReleasePreviousReleases struct {
	// Updates all prior non-archived releases to the desired state.
	UpdateState string `json:"updateState,omitempty"`
}
