/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package catalog

// PublishedProductReferences  (catalog.v1alpha1.PublishedProduct)
type PublishedProductReferences struct {
	Release PublishedProductReferencesRelease `json:"release"`
}
