/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package catalog

// SubscriptionInvoiceBillingPaymentTypeStripeCustomer struct for SubscriptionInvoiceBillingPaymentTypeStripeCustomer
type SubscriptionInvoiceBillingPaymentTypeStripeCustomer struct {
	Id string `json:"id"`
}
