/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package catalog

// AssetStatusMeta struct for AssetStatusMeta
type AssetStatusMeta struct {
	AssetResource string `json:"assetResource,omitempty"`
}
