/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package catalog

// CredentialSpec  (catalog.v1alpha1.Credential)
type CredentialSpec struct {
	// Reference to Credential Request Definition resource
	CredentialRequestDefinition string `json:"credentialRequestDefinition"`
	// data matching the credential request definition schema. (catalog.v1alpha1.Credential)
	Data  map[string]interface{} `json:"data"`
	State CredentialSpecState    `json:"state,omitempty"`
}
