/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package catalog

// ApplicationState the model 'ApplicationState'
type ApplicationState string

// List of ApplicationState
const (
	// GENERATE: The following code has been modified after code generation
	ApplicationStateARCHIVED ApplicationState = "archived"
	ARCHIVING                ApplicationState = "archiving"
)
