/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1alpha1

// ProductSpecAssets struct for ProductSpecAssets
type ProductSpecAssets struct {
	Name    string             `json:"name"`
	Filters ProductSpecFilters `json:"filters,omitempty"`
}
