/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package catalog

// StageVisibilitySpec struct for StageVisibilitySpec
type StageVisibilitySpec struct {
	// Defines where the visibility settings apply.
	Stages []StageVisibilitySpecStages `json:"stages"`
	// Determines if the list of subjects should be excluded from the stage visibility.
	Exclude bool `json:"exclude,omitempty"`
	// GENERATE: The following code has been modified after code generation
	Subjects []interface{} `json:"subjects,omitempty"`
}
