/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package catalog

// AuthorizationProfileSpec  (catalog.v1alpha1.AuthorizationProfile)
type AuthorizationProfileSpec struct {
	// Description of AuthorizationProfile that can be used to access Asset.
	Description string `json:"description,omitempty"`
}
