/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package catalog

// SubscriptionInvoiceSpecCost The invoice generated cost
type SubscriptionInvoiceSpecCost struct {
	// The computed cost of the entire invoice, including plan and quota items costs.
	Total float64                         `json:"total,omitempty"`
	Plan  SubscriptionInvoiceSpecCostPlan `json:"plan,omitempty"`
}
