/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package catalog

// AssetRequestMarketplaceResourceOwner Owner of the Access Request. (catalog.v1alpha1.AssetRequest)
type AssetRequestMarketplaceResourceOwner struct {
	// The type of the owner.
	Type string `json:"type,omitempty"`
	// Id of the owner of the resource.
	Id           string                                           `json:"id,omitempty"`
	Organization AssetRequestMarketplaceResourceOwnerOrganization `json:"organization"`
	User         AssetRequestMarketplaceResourceOwnerUser         `json:"user,omitempty"`
}
