/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package catalog

// ReleaseTagSpecPreviousReleases struct for ReleaseTagSpecPreviousReleases
type ReleaseTagSpecPreviousReleases struct {
	// Updates all prior non-archived releases to the desired state.  The 'archived' state is currently available only for Product ReleaseTags.
	UpdateState string `json:"updateState,omitempty"`
}
