/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package catalog

// MarketplaceSpec struct for MarketplaceSpec
type MarketplaceSpec struct {
	// description of the Marketplace.
	Description string `json:"description,omitempty"`
}
