/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package catalog

// ConsumerProductPlanVisibilitySpecPlans  (catalog.v1alpha1.ConsumerProductPlanVisibility)
type ConsumerProductPlanVisibilitySpecPlans struct {
	Name string `json:"name"`
}
