/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1alpha1

// AssetRequestState struct for AssetRequestState
type AssetRequestState struct {
	Name string `json:"name"`
	// Description of the phase.
	Message string `json:"message,omitempty"`
}
