/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package catalog

// ApplicationProfileMarketplace Details about the marketplace Application Profile. (catalog.v1alpha1.ApplicationProfile)
type ApplicationProfileMarketplace struct {
	// The name of the Marketplace.
	Name     string                                `json:"name"`
	Resource ApplicationProfileMarketplaceResource `json:"resource"`
}
