/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package catalog

// SubscriptionInvoiceBilling  (catalog.v1alpha1.SubscriptionInvoice)
type SubscriptionInvoiceBilling struct {
	// GENERATE: The following code has been modified after code generation
	Payment interface{} `json:"payment,omitempty"`
}
