/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package catalog

// StageSpec struct for StageSpec
type StageSpec struct {
	// description of the stage
	Description string `json:"description,omitempty"`
}
