/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package catalog

// AssetResourceReferences struct for AssetResourceReferences
type AssetResourceReferences struct {
	// Reference to API Service Revision resource
	ApiServiceRevision string `json:"apiServiceRevision,omitempty"`
	// Reference to API Service Instance resource
	ApiServiceInstance string `json:"apiServiceInstance,omitempty"`
}
