/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package catalog

// ProductPlanReferences  (catalog.v1alpha1.ProductPlan)
type ProductPlanReferences struct {
	Product ProductPlanReferencesProduct `json:"product,omitempty"`
}
