/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package catalog

// AssetRequestDefinitionApplicationprofile A reference to the application profile defined as a requirement for provisioned asset requests.
type AssetRequestDefinitionApplicationprofile struct {
	// The name of the application profile definition.
	Name string `json:"name,omitempty"`
}
