/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package catalog

// AssetRequestDefinitionSpecProvisionPolicies Defines the policies applied on the AccessRequests generated using this definition.
type AssetRequestDefinitionSpecProvisionPolicies struct {
	// Defines on if AssetRequests using this definition can be moved from their current Subscription to a new one.
	Transferable bool `json:"transferable,omitempty"`
}
