/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package catalog

// AssetResourceOverviewMarkdownRef struct for AssetResourceOverviewMarkdownRef
type AssetResourceOverviewMarkdownRef struct {
	Kind    string `json:"kind"`
	Content string `json:"content"`
}
