/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1alpha1

// PublishedProductSpec struct for PublishedProductSpec
type PublishedProductSpec struct {
	Product PublishedProductSpecProduct `json:"product,omitempty"`
}
