/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package catalog

// CredentialPolicies  (catalog.v1alpha1.Credential)
type CredentialPolicies struct {
	Expiry CredentialPoliciesExpiry `json:"expiry,omitempty"`
}
