/*
 * This file is automatically generated
 */

package v1alpha1

import (
	"encoding/json"

	apiv1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/api/v1"
)

var (
	_ProductPlanGVK = apiv1.GroupVersionKind{
		GroupKind: apiv1.GroupKind{
			Group: "catalog",
			Kind:  "ProductPlan",
		},
		APIVersion: "v1alpha1",
	}

	ProductPlanScopes = []string{""}
)

const ProductPlanResourceName = "productplans"

func ProductPlanGVK() apiv1.GroupVersionKind {
	return _ProductPlanGVK
}

func init() {
	apiv1.RegisterGVK(_ProductPlanGVK, ProductPlanScopes[0], ProductPlanResourceName)
}

// ProductPlan Resource
type ProductPlan struct {
	apiv1.ResourceMeta

	Owner *apiv1.Owner `json:"owner"`

	References ProductPlanReferences `json:"references"`

	Spec ProductPlanSpec `json:"spec"`

	State ProductPlanState `json:"state"`
}

// FromInstance converts a ResourceInstance to a ProductPlan
func (res *ProductPlan) FromInstance(ri *apiv1.ResourceInstance) error {
	if ri == nil {
		res = nil
		return nil
	}

	var err error
	rawResource := ri.GetRawResource()
	if rawResource == nil {
		rawResource, err = json.Marshal(ri)
		if err != nil {
			return err
		}
	}

	err = json.Unmarshal(rawResource, res)
	return err
}

// ProductPlanFromInstanceArray converts a []*ResourceInstance to a []*ProductPlan
func ProductPlanFromInstanceArray(fromArray []*apiv1.ResourceInstance) ([]*ProductPlan, error) {
	newArray := make([]*ProductPlan, 0)
	for _, item := range fromArray {
		res := &ProductPlan{}
		err := res.FromInstance(item)
		if err != nil {
			return make([]*ProductPlan, 0), err
		}
		newArray = append(newArray, res)
	}

	return newArray, nil
}

// AsInstance converts a ProductPlan to a ResourceInstance
func (res *ProductPlan) AsInstance() (*apiv1.ResourceInstance, error) {
	meta := res.ResourceMeta
	meta.GroupVersionKind = ProductPlanGVK()
	res.ResourceMeta = meta

	m, err := json.Marshal(res)
	if err != nil {
		return nil, err
	}

	instance := apiv1.ResourceInstance{}
	err = json.Unmarshal(m, &instance)
	if err != nil {
		return nil, err
	}

	return &instance, nil
}
