/*
 * This file is automatically generated
 */

package v1alpha1

import (
	"encoding/json"

	apiv1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/api/v1"
)

var (
	_ReleaseTagGVK = apiv1.GroupVersionKind{
		GroupKind: apiv1.GroupKind{
			Group: "catalog",
			Kind:  "ReleaseTag",
		},
		APIVersion: "v1alpha1",
	}
)

const (
	ReleaseTagScope = "Asset"

	ReleaseTagResourceName = "releasetags"
)

func ReleaseTagGVK() apiv1.GroupVersionKind {
	return _ReleaseTagGVK
}

func init() {
	apiv1.RegisterGVK(_ReleaseTagGVK, ReleaseTagScope, ReleaseTagResourceName)
}

// ReleaseTag Resource
type ReleaseTag struct {
	apiv1.ResourceMeta

	// GENERATE: The following code has been modified after code generation
	// 	Owner struct{} `json:"owner"`
	Owner struct{} `json:"owner,omitempty"`

	References ReleaseTagReferences `json:"references"`

	Spec ReleaseTagSpec `json:"spec"`

	Status ReleaseTagStatus `json:"status"`
}

// FromInstance converts a ResourceInstance to a ReleaseTag
func (res *ReleaseTag) FromInstance(ri *apiv1.ResourceInstance) error {
	if ri == nil {
		res = nil
		return nil
	}

	m, err := json.Marshal(ri.Spec)
	if err != nil {
		return err
	}

	spec := &ReleaseTagSpec{}
	err = json.Unmarshal(m, spec)
	if err != nil {
		return err
	}

	*res = ReleaseTag{ResourceMeta: ri.ResourceMeta, Spec: *spec}

	return err
}

// ReleaseTagFromInstanceArray converts a []*ResourceInstance to a []*ReleaseTag
func ReleaseTagFromInstanceArray(fromArray []*apiv1.ResourceInstance) ([]*ReleaseTag, error) {
	newArray := make([]*ReleaseTag, 0)
	for _, item := range fromArray {
		res := &ReleaseTag{}
		err := res.FromInstance(item)
		if err != nil {
			return make([]*ReleaseTag, 0), err
		}
		newArray = append(newArray, res)
	}

	return newArray, nil
}

// AsInstance converts a ReleaseTag to a ResourceInstance
func (res *ReleaseTag) AsInstance() (*apiv1.ResourceInstance, error) {
	m, err := json.Marshal(res.Spec)
	if err != nil {
		return nil, err
	}

	spec := map[string]interface{}{}
	err = json.Unmarshal(m, &spec)
	if err != nil {
		return nil, err
	}

	meta := res.ResourceMeta
	meta.GroupVersionKind = ReleaseTagGVK()

	return &apiv1.ResourceInstance{ResourceMeta: meta, Spec: spec}, nil
}
