/*
 * This file is automatically generated
 */

package catalog

import (
	"encoding/json"

	apiv1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/api/v1"

	"github.com/Axway/agent-sdk/pkg/util/log"
)

var (
	SubscriptionRequestDefinitionCtx log.ContextField = "subscriptionRequestDefinition"

	_SubscriptionRequestDefinitionGVK = apiv1.GroupVersionKind{
		GroupKind: apiv1.GroupKind{
			Group: "catalog",
			Kind:  "SubscriptionRequestDefinition",
		},
		APIVersion: "v1alpha1",
	}

	SubscriptionRequestDefinitionScopes = []string{""}
)

const (
	SubscriptionRequestDefinitionResourceName = "subscriptionrequestdefinitions"
)

func SubscriptionRequestDefinitionGVK() apiv1.GroupVersionKind {
	return _SubscriptionRequestDefinitionGVK
}

func init() {
	apiv1.RegisterGVK(_SubscriptionRequestDefinitionGVK, SubscriptionRequestDefinitionScopes[0], SubscriptionRequestDefinitionResourceName)
	log.RegisterContextField(SubscriptionRequestDefinitionCtx)
}

// SubscriptionRequestDefinition Resource
type SubscriptionRequestDefinition struct {
	apiv1.ResourceMeta
	Owner *apiv1.Owner                      `json:"owner"`
	Spec  SubscriptionRequestDefinitionSpec `json:"spec"`
}

// NewSubscriptionRequestDefinition creates an empty *SubscriptionRequestDefinition
func NewSubscriptionRequestDefinition(name string) *SubscriptionRequestDefinition {
	return &SubscriptionRequestDefinition{
		ResourceMeta: apiv1.ResourceMeta{
			Name:             name,
			GroupVersionKind: _SubscriptionRequestDefinitionGVK,
		},
	}
}

// SubscriptionRequestDefinitionFromInstanceArray converts a []*ResourceInstance to a []*SubscriptionRequestDefinition
func SubscriptionRequestDefinitionFromInstanceArray(fromArray []*apiv1.ResourceInstance) ([]*SubscriptionRequestDefinition, error) {
	newArray := make([]*SubscriptionRequestDefinition, 0)
	for _, item := range fromArray {
		res := &SubscriptionRequestDefinition{}
		err := res.FromInstance(item)
		if err != nil {
			return make([]*SubscriptionRequestDefinition, 0), err
		}
		newArray = append(newArray, res)
	}

	return newArray, nil
}

// AsInstance converts a SubscriptionRequestDefinition to a ResourceInstance
func (res *SubscriptionRequestDefinition) AsInstance() (*apiv1.ResourceInstance, error) {
	meta := res.ResourceMeta
	meta.GroupVersionKind = SubscriptionRequestDefinitionGVK()
	res.ResourceMeta = meta

	m, err := json.Marshal(res)
	if err != nil {
		return nil, err
	}

	instance := apiv1.ResourceInstance{}
	err = json.Unmarshal(m, &instance)
	if err != nil {
		return nil, err
	}
	for key, val := range res.SubResourceHashes {
		instance.SubResourceHashes[key] = val
	}
	return &instance, nil
}

// FromInstance converts a ResourceInstance to a SubscriptionRequestDefinition
func (res *SubscriptionRequestDefinition) FromInstance(ri *apiv1.ResourceInstance) error {
	if ri == nil {
		res = nil
		return nil
	}
	var err error
	rawResource := ri.GetRawResource()
	if rawResource == nil {
		rawResource, err = json.Marshal(ri)
		if err != nil {
			return err
		}
	}
	err = json.Unmarshal(rawResource, res)
	if err != nil {
		return err
	}
	for key, val := range ri.SubResourceHashes {
		res.SubResourceHashes[key] = val
	}
	return err
}

// MarshalJSON custom marshaller to handle sub resources
func (res *SubscriptionRequestDefinition) MarshalJSON() ([]byte, error) {
	m, err := json.Marshal(&res.ResourceMeta)
	if err != nil {
		return nil, err
	}

	var out map[string]interface{}
	err = json.Unmarshal(m, &out)
	if err != nil {
		return nil, err
	}

	out["owner"] = res.Owner
	out["spec"] = res.Spec

	return json.Marshal(out)
}

// UnmarshalJSON custom unmarshaller to handle sub resources
func (res *SubscriptionRequestDefinition) UnmarshalJSON(data []byte) error {
	var err error

	aux := &apiv1.ResourceInstance{}
	err = json.Unmarshal(data, aux)
	if err != nil {
		return err
	}

	res.ResourceMeta = aux.ResourceMeta
	res.Owner = aux.Owner

	// ResourceInstance holds the spec as a map[string]interface{}.
	// Convert it to bytes, then convert to the spec type for the resource.
	sr, err := json.Marshal(aux.Spec)
	if err != nil {
		return err
	}

	err = json.Unmarshal(sr, &res.Spec)
	if err != nil {
		return err
	}

	return nil
}

// PluralName returns the plural name of the resource
func (res *SubscriptionRequestDefinition) PluralName() string {
	return SubscriptionRequestDefinitionResourceName
}
