/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package catalog

// MarketplaceBilling Billing options for the Marketplace. (catalog.v1.Marketplace)
type MarketplaceBilling struct {
	Payment MarketplaceBillingPayment `json:"payment,omitempty"`
}
