/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package catalog

// ProductPlanVisibilitySpecTagRef struct for ProductPlanVisibilitySpecTagRef
type ProductPlanVisibilitySpecTagRef struct {
	Type string `json:"type"`
	// Value of a platform team tag.
	Value string `json:"value"`
}
