/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package catalog

// ApplicationMarketplaceResourceOwnerUser User Id. (catalog.v1.Application)
type ApplicationMarketplaceResourceOwnerUser struct {
	// Id of the user as an owner.
	Id string `json:"id,omitempty"`
}
