/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package catalog

// SubscriptionJobSpecPlanMigration struct for SubscriptionJobSpecPlanMigration
type SubscriptionJobSpecPlanMigration struct {
	Type string `json:"type"`
	// The Product Plan to which to migrate the Subscription.
	ProductPlan string `json:"productPlan"`
	// Description on why the subscription was migrated.
	Reason string `json:"reason,omitempty"`
	// The Product Plan Job which triggered the migration.
	ProductPlanJob string `json:"productPlanJob,omitempty"`
}
