/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package catalog

// ProductSpec  (catalog.v1.Product)
type ProductSpec struct {
	// Description of the Product.
	Description    string   `json:"description,omitempty"`
	SupportContact string   `json:"supportContact,omitempty"`
	Categories     []string `json:"categories,omitempty"`
	// Defines all the Assets that the Product will be built from.
	Assets      []ProductSpecAssets     `json:"assets,omitempty"`
	AutoRelease *ProductSpecAutoRelease `json:"autoRelease,omitempty"`
}
