/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package catalog

// CategoryVisibilitySpec  (catalog.v1.CategoryVisibility)
type CategoryVisibilitySpec struct {
	Category string `json:"category"`
	// Defines if the Category is featured in the marketplace.
	Featured bool `json:"featured"`
}
