/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package catalog

// ProductPlanJobSpecSubscriptionsMigration struct for ProductPlanJobSpecSubscriptionsMigration
type ProductPlanJobSpecSubscriptionsMigration struct {
	Type string `json:"type"`
	// The Product Plan to which to migrate the existing Product Subscriptions.
	ProductPlan string `json:"productPlan"`
	// Description on why the subscriptions was migrated.
	Reason string `json:"reason,omitempty"`
	// Filter the subscriptions that are wanted to be migrated.
	Filters []ProductPlanJobSpecSubscriptionsMigrationFilters `json:"filters,omitempty"`
}
