/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package catalog

// WebhookSpecQueryLocation struct for WebhookSpecQueryLocation
type WebhookSpecQueryLocation struct {
	// Defines the location of the secret.
	In string `json:"in"`
	// The name of the query parameter.
	Name string `json:"name"`
}
