/*
 * This file is automatically generated
 */

package catalog

import (
	"encoding/json"
	"fmt"

	apiv1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/api/v1"

	"github.com/Axway/agent-sdk/pkg/util/log"
)

var (
	ResourceCtx log.ContextField = "resource"

	_ResourceGVK = apiv1.GroupVersionKind{
		GroupKind: apiv1.GroupKind{
			Group: "catalog",
			Kind:  "Resource",
		},
		APIVersion: "v1",
	}

	ResourceScopes = []string{"Product", "ProductRelease"}
)

const (
	ResourceResourceName             = "resources"
	Resource_embeddedSubResourceName = "_embedded"
)

func ResourceGVK() apiv1.GroupVersionKind {
	return _ResourceGVK
}

func init() {
	apiv1.RegisterGVK(_ResourceGVK, ResourceScopes[0], ResourceResourceName)
	log.RegisterContextField(ResourceCtx)
}

// Resource Resource
type Resource struct {
	apiv1.ResourceMeta
	_embedded interface{}  `json:"_embedded"`
	Owner     *apiv1.Owner `json:"owner"`
	Spec      ResourceSpec `json:"spec"`
}

// NewResource creates an empty *Resource
func NewResource(name, scopeKind, scopeName string) (*Resource, error) {
	validScope := false
	for _, s := range ResourceScopes {
		if scopeKind == s {
			validScope = true
			break
		}
	}
	if !validScope {
		return nil, fmt.Errorf("scope '%s' not valid for Resource kind", scopeKind)
	}

	return &Resource{
		ResourceMeta: apiv1.ResourceMeta{
			Name:             name,
			GroupVersionKind: _ResourceGVK,
			Metadata: apiv1.Metadata{
				Scope: apiv1.MetadataScope{
					Name: scopeName,
					Kind: scopeKind,
				},
			},
		},
	}, nil
}

// ResourceFromInstanceArray converts a []*ResourceInstance to a []*Resource
func ResourceFromInstanceArray(fromArray []*apiv1.ResourceInstance) ([]*Resource, error) {
	newArray := make([]*Resource, 0)
	for _, item := range fromArray {
		res := &Resource{}
		err := res.FromInstance(item)
		if err != nil {
			return make([]*Resource, 0), err
		}
		newArray = append(newArray, res)
	}

	return newArray, nil
}

// AsInstance converts a Resource to a ResourceInstance
func (res *Resource) AsInstance() (*apiv1.ResourceInstance, error) {
	meta := res.ResourceMeta
	meta.GroupVersionKind = ResourceGVK()
	res.ResourceMeta = meta

	m, err := json.Marshal(res)
	if err != nil {
		return nil, err
	}

	instance := apiv1.ResourceInstance{}
	err = json.Unmarshal(m, &instance)
	if err != nil {
		return nil, err
	}

	return &instance, nil
}

// FromInstance converts a ResourceInstance to a Resource
func (res *Resource) FromInstance(ri *apiv1.ResourceInstance) error {
	if ri == nil {
		res = nil
		return nil
	}
	var err error
	rawResource := ri.GetRawResource()
	if rawResource == nil {
		rawResource, err = json.Marshal(ri)
		if err != nil {
			return err
		}
	}
	err = json.Unmarshal(rawResource, res)
	return err
}

// MarshalJSON custom marshaller to handle sub resources
func (res *Resource) MarshalJSON() ([]byte, error) {
	m, err := json.Marshal(&res.ResourceMeta)
	if err != nil {
		return nil, err
	}

	var out map[string]interface{}
	err = json.Unmarshal(m, &out)
	if err != nil {
		return nil, err
	}

	out["_embedded"] = res._embedded
	out["owner"] = res.Owner
	out["spec"] = res.Spec

	return json.Marshal(out)
}

// UnmarshalJSON custom unmarshaller to handle sub resources
func (res *Resource) UnmarshalJSON(data []byte) error {
	var err error

	aux := &apiv1.ResourceInstance{}
	err = json.Unmarshal(data, aux)
	if err != nil {
		return err
	}

	res.ResourceMeta = aux.ResourceMeta
	res.Owner = aux.Owner

	// ResourceInstance holds the spec as a map[string]interface{}.
	// Convert it to bytes, then convert to the spec type for the resource.
	sr, err := json.Marshal(aux.Spec)
	if err != nil {
		return err
	}

	err = json.Unmarshal(sr, &res.Spec)
	if err != nil {
		return err
	}

	// marshalling subresource _embedded
	if v, ok := aux.SubResources["_embedded"]; ok {
		sr, err = json.Marshal(v)
		if err != nil {
			return err
		}

		delete(aux.SubResources, "_embedded")
		err = json.Unmarshal(sr, &res._embedded)
		if err != nil {
			return err
		}
	}

	return nil
}

// PluralName returns the plural name of the resource
func (res *Resource) PluralName() string {
	return ResourceResourceName
}
