/*
 * This file is automatically generated
 */

package v1alpha1

import (
	"fmt"

	v1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/clients/api/v1"
	apiv1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/api/v1"
	m "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/management/v1alpha1"
)

type AccessRequestDefinitionMergeFunc func(*m.AccessRequestDefinition, *m.AccessRequestDefinition) (*m.AccessRequestDefinition, error)

// AccessRequestDefinitionMerge builds a merge option for an update operation
func AccessRequestDefinitionMerge(f AccessRequestDefinitionMergeFunc) v1.UpdateOption {
	return v1.Merge(func(prev, new apiv1.Interface) (apiv1.Interface, error) {
		p, n := &m.AccessRequestDefinition{}, &m.AccessRequestDefinition{}

		switch t := prev.(type) {
		case *m.AccessRequestDefinition:
			p = t
		case *apiv1.ResourceInstance:
			err := p.FromInstance(t)
			if err != nil {
				return nil, fmt.Errorf("merge: failed to unserialise prev resource: %w", err)
			}
		default:
			return nil, fmt.Errorf("merge: failed to unserialise prev resource, unxexpected resource type: %T", t)
		}

		switch t := new.(type) {
		case *m.AccessRequestDefinition:
			n = t
		case *apiv1.ResourceInstance:
			err := n.FromInstance(t)
			if err != nil {
				return nil, fmt.Errorf("merge: failed to unserialize new resource: %w", err)
			}
		default:
			return nil, fmt.Errorf("merge: failed to unserialise new resource, unxexpected resource type: %T", t)
		}

		return f(p, n)
	})
}

// AccessRequestDefinitionClient - rest client for AccessRequestDefinition resources that have a defined resource scope
type AccessRequestDefinitionClient struct {
	client v1.Scoped
}

// UnscopedAccessRequestDefinitionClient - rest client for AccessRequestDefinition resources that do not have a defined scope
type UnscopedAccessRequestDefinitionClient struct {
	client v1.Unscoped
}

// NewAccessRequestDefinitionClient - creates a client that is not scoped to any resource
func NewAccessRequestDefinitionClient(c v1.Base) (*UnscopedAccessRequestDefinitionClient, error) {

	client, err := c.ForKind(m.AccessRequestDefinitionGVK())
	if err != nil {
		return nil, err
	}

	return &UnscopedAccessRequestDefinitionClient{client}, nil

}

// WithScope - sets the resource scope for the client
func (c *UnscopedAccessRequestDefinitionClient) WithScope(scope string) *AccessRequestDefinitionClient {
	return &AccessRequestDefinitionClient{
		c.client.WithScope(scope),
	}
}

// Get - gets a resource by name
func (c *UnscopedAccessRequestDefinitionClient) Get(name string) (*m.AccessRequestDefinition, error) {
	ri, err := c.client.Get(name)
	if err != nil {
		return nil, err
	}

	service := &m.AccessRequestDefinition{}
	service.FromInstance(ri)

	return service, nil
}

// Update - updates a resource
func (c *UnscopedAccessRequestDefinitionClient) Update(res *m.AccessRequestDefinition, opts ...v1.UpdateOption) (*m.AccessRequestDefinition, error) {
	ri, err := res.AsInstance()
	if err != nil {
		return nil, err
	}
	resource, err := c.client.Update(ri, opts...)
	if err != nil {
		return nil, err
	}

	updated := &m.AccessRequestDefinition{}

	// Updates the resource in place
	err = updated.FromInstance(resource)
	if err != nil {
		return nil, err
	}

	return updated, nil
}

// List - gets a list of resources
func (c *AccessRequestDefinitionClient) List(options ...v1.ListOptions) ([]*m.AccessRequestDefinition, error) {
	riList, err := c.client.List(options...)
	if err != nil {
		return nil, err
	}

	result := make([]*m.AccessRequestDefinition, len(riList))

	for i := range riList {
		result[i] = &m.AccessRequestDefinition{}
		err := result[i].FromInstance(riList[i])
		if err != nil {
			return nil, err
		}
	}

	return result, nil
}

// Get - gets a resource by name
func (c *AccessRequestDefinitionClient) Get(name string) (*m.AccessRequestDefinition, error) {
	ri, err := c.client.Get(name)
	if err != nil {
		return nil, err
	}

	service := &m.AccessRequestDefinition{}
	service.FromInstance(ri)

	return service, nil
}

// Delete - deletes a resource
func (c *AccessRequestDefinitionClient) Delete(res *m.AccessRequestDefinition) error {
	ri, err := res.AsInstance()

	if err != nil {
		return err
	}

	return c.client.Delete(ri)
}

// Create - creates a resource
func (c *AccessRequestDefinitionClient) Create(res *m.AccessRequestDefinition, opts ...v1.CreateOption) (*m.AccessRequestDefinition, error) {
	ri, err := res.AsInstance()

	if err != nil {
		return nil, err
	}

	cri, err := c.client.Create(ri, opts...)
	if err != nil {
		return nil, err
	}

	created := &m.AccessRequestDefinition{}

	err = created.FromInstance(cri)
	if err != nil {
		return nil, err
	}

	return created, err
}

// Update - updates a resource
func (c *AccessRequestDefinitionClient) Update(res *m.AccessRequestDefinition, opts ...v1.UpdateOption) (*m.AccessRequestDefinition, error) {
	ri, err := res.AsInstance()
	if err != nil {
		return nil, err
	}
	resource, err := c.client.Update(ri, opts...)
	if err != nil {
		return nil, err
	}

	updated := &m.AccessRequestDefinition{}

	// Updates the resource in place
	err = updated.FromInstance(resource)
	if err != nil {
		return nil, err
	}

	return updated, nil
}
