/*
 * This file is automatically generated
 */

package v1alpha1

import (
	"fmt"

	v1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/clients/api/v1"
	apiv1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/api/v1"
	"github.com/Axway/agent-sdk/pkg/apic/apiserver/models/management/v1alpha1"
)

type AmplifyConfigMergeFunc func(*v1alpha1.AmplifyConfig, *v1alpha1.AmplifyConfig) (*v1alpha1.AmplifyConfig, error)

// Merge builds a merge option for an update operation
func AmplifyConfigMerge(f AmplifyConfigMergeFunc) v1.UpdateOption {
	return v1.Merge(func(prev, new apiv1.Interface) (apiv1.Interface, error) {
		p, n := &v1alpha1.AmplifyConfig{}, &v1alpha1.AmplifyConfig{}

		switch t := prev.(type) {
		case *v1alpha1.AmplifyConfig:
			p = t
		case *apiv1.ResourceInstance:
			err := p.FromInstance(t)
			if err != nil {
				return nil, fmt.Errorf("merge: failed to unserialise prev resource: %w", err)
			}
		default:
			return nil, fmt.Errorf("merge: failed to unserialise prev resource, unxexpected resource type: %T", t)
		}

		switch t := new.(type) {
		case *v1alpha1.AmplifyConfig:
			n = t
		case *apiv1.ResourceInstance:
			err := n.FromInstance(t)
			if err != nil {
				return nil, fmt.Errorf("merge: failed to unserialize new resource: %w", err)
			}
		default:
			return nil, fmt.Errorf("merge: failed to unserialise new resource, unxexpected resource type: %T", t)
		}

		return f(p, n)
	})
}

// AmplifyConfigClient -
type AmplifyConfigClient struct {
	client v1.Scoped
}

// UnscopedAmplifyConfigClient -
type UnscopedAmplifyConfigClient struct {
	client v1.Unscoped
}

// NewAmplifyConfigClient -
func NewAmplifyConfigClient(c v1.Base) (*UnscopedAmplifyConfigClient, error) {

	client, err := c.ForKind(v1alpha1.AmplifyConfigGVK())
	if err != nil {
		return nil, err
	}

	return &UnscopedAmplifyConfigClient{client}, nil

}

// WithScope -
func (c *UnscopedAmplifyConfigClient) WithScope(scope string) *AmplifyConfigClient {
	return &AmplifyConfigClient{
		c.client.WithScope(scope),
	}
}

// Get -
func (c *UnscopedAmplifyConfigClient) Get(name string) (*v1alpha1.AmplifyConfig, error) {
	ri, err := c.client.Get(name)
	if err != nil {
		return nil, err
	}

	service := &v1alpha1.AmplifyConfig{}
	service.FromInstance(ri)

	return service, nil
}

// Update -
func (c *UnscopedAmplifyConfigClient) Update(res *v1alpha1.AmplifyConfig, opts ...v1.UpdateOption) (*v1alpha1.AmplifyConfig, error) {
	ri, err := res.AsInstance()
	if err != nil {
		return nil, err
	}
	resource, err := c.client.Update(ri, opts...)
	if err != nil {
		return nil, err
	}

	updated := &v1alpha1.AmplifyConfig{}

	// Updates the resource in place
	err = updated.FromInstance(resource)
	if err != nil {
		return nil, err
	}

	return updated, nil
}

// List -
func (c *AmplifyConfigClient) List(options ...v1.ListOptions) ([]*v1alpha1.AmplifyConfig, error) {
	riList, err := c.client.List(options...)
	if err != nil {
		return nil, err
	}

	result := make([]*v1alpha1.AmplifyConfig, len(riList))

	for i := range riList {
		result[i] = &v1alpha1.AmplifyConfig{}
		err := result[i].FromInstance(riList[i])
		if err != nil {
			return nil, err
		}
	}

	return result, nil
}

// Get -
func (c *AmplifyConfigClient) Get(name string) (*v1alpha1.AmplifyConfig, error) {
	ri, err := c.client.Get(name)
	if err != nil {
		return nil, err
	}

	service := &v1alpha1.AmplifyConfig{}
	service.FromInstance(ri)

	return service, nil
}

// Delete -
func (c *AmplifyConfigClient) Delete(res *v1alpha1.AmplifyConfig) error {
	ri, err := res.AsInstance()

	if err != nil {
		return err
	}

	return c.client.Delete(ri)
}

// Create -
func (c *AmplifyConfigClient) Create(res *v1alpha1.AmplifyConfig, opts ...v1.CreateOption) (*v1alpha1.AmplifyConfig, error) {
	ri, err := res.AsInstance()

	if err != nil {
		return nil, err
	}

	cri, err := c.client.Create(ri, opts...)
	if err != nil {
		return nil, err
	}

	created := &v1alpha1.AmplifyConfig{}

	err = created.FromInstance(cri)
	if err != nil {
		return nil, err
	}

	return created, err
}

// Update -
func (c *AmplifyConfigClient) Update(res *v1alpha1.AmplifyConfig, opts ...v1.UpdateOption) (*v1alpha1.AmplifyConfig, error) {
	ri, err := res.AsInstance()
	if err != nil {
		return nil, err
	}
	resource, err := c.client.Update(ri, opts...)
	if err != nil {
		return nil, err
	}

	updated := &v1alpha1.AmplifyConfig{}

	// Updates the resource in place
	err = updated.FromInstance(resource)
	if err != nil {
		return nil, err
	}

	return updated, nil
}
