/*
 * This file is automatically generated
 */

package v1alpha1

import (
	v1 "git.ecd.axway.org/apigov/apic_agents_sdk/pkg/apic/apiserver/clients/api/v1"
	"git.ecd.axway.org/apigov/apic_agents_sdk/pkg/apic/apiserver/models/management/v1alpha1"
)

// AWSDiscoveryAgentClient -
type AWSDiscoveryAgentClient struct {
	client v1.Scoped
}

// UnscopedAWSDiscoveryAgentClient -
type UnscopedAWSDiscoveryAgentClient struct {
	client v1.Unscoped
}

// NewAWSDiscoveryAgentClient -
func NewAWSDiscoveryAgentClient(c v1.Base) (*UnscopedAWSDiscoveryAgentClient, error) {

	client, err := c.ForKind(v1alpha1.AWSDiscoveryAgentGVK())
	if err != nil {
		return nil, err
	}

	return &UnscopedAWSDiscoveryAgentClient{client}, nil

}

// WithScope -
func (c *UnscopedAWSDiscoveryAgentClient) WithScope(scope string) *AWSDiscoveryAgentClient {
	return &AWSDiscoveryAgentClient{
		c.client.WithScope(scope),
	}
}

// List -
func (c *AWSDiscoveryAgentClient) List(options ...v1.ListOptions) ([]*v1alpha1.AWSDiscoveryAgent, error) {
	riList, err := c.client.List(options...)
	if err != nil {
		return nil, err
	}

	result := make([]*v1alpha1.AWSDiscoveryAgent, len(riList))

	for i := range riList {
		result[i] = &v1alpha1.AWSDiscoveryAgent{}
		err := result[i].FromInstance(riList[i])
		if err != nil {
			return nil, err
		}
	}

	return result, nil
}

// Get -
func (c *AWSDiscoveryAgentClient) Get(name string) (*v1alpha1.AWSDiscoveryAgent, error) {
	ri, err := c.client.Get(name)
	if err != nil {
		return nil, err
	}

	service := &v1alpha1.AWSDiscoveryAgent{}
	service.FromInstance(ri)

	return service, nil
}

// Delete -
func (c *AWSDiscoveryAgentClient) Delete(res *v1alpha1.AWSDiscoveryAgent) error {
	ri, err := res.AsInstance()

	if err != nil {
		return err
	}

	return c.client.Delete(ri)
}

// Create -
func (c *AWSDiscoveryAgentClient) Create(res *v1alpha1.AWSDiscoveryAgent) (*v1alpha1.AWSDiscoveryAgent, error) {
	ri, err := res.AsInstance()

	if err != nil {
		return nil, err
	}

	cri, err := c.client.Create(ri)
	if err != nil {
		return nil, err
	}

	created := &v1alpha1.AWSDiscoveryAgent{}

	err = created.FromInstance(cri)
	if err != nil {
		return nil, err
	}

	return created, err
}

// Update -
func (c *AWSDiscoveryAgentClient) Update(res *v1alpha1.AWSDiscoveryAgent) (*v1alpha1.AWSDiscoveryAgent, error) {
	ri, err := res.AsInstance()
	if err != nil {
		return nil, err
	}
	resource, err := c.client.Update(ri)
	if err != nil {
		return nil, err
	}

	updated := &v1alpha1.AWSDiscoveryAgent{}

	// Updates the resource in place
	err = updated.FromInstance(resource)
	if err != nil {
		return nil, err
	}

	return updated, nil
}
