/*
 * This file is automatically generated
 */

package management

import (
	"fmt"

	v1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/clients/api/v1"
	apiv1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/api/v1"
	m "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/management/v1alpha1"
)

type ComplianceRuntimeResultMergeFunc func(*m.ComplianceRuntimeResult, *m.ComplianceRuntimeResult) (*m.ComplianceRuntimeResult, error)

// ComplianceRuntimeResultMerge builds a merge option for an update operation
func ComplianceRuntimeResultMerge(f ComplianceRuntimeResultMergeFunc) v1.UpdateOption {
	return v1.Merge(func(prev, new apiv1.Interface) (apiv1.Interface, error) {
		p, n := &m.ComplianceRuntimeResult{}, &m.ComplianceRuntimeResult{}

		switch t := prev.(type) {
		case *m.ComplianceRuntimeResult:
			p = t
		case *apiv1.ResourceInstance:
			err := p.FromInstance(t)
			if err != nil {
				return nil, fmt.Errorf("merge: failed to unserialise prev resource: %w", err)
			}
		default:
			return nil, fmt.Errorf("merge: failed to unserialise prev resource, unxexpected resource type: %T", t)
		}

		switch t := new.(type) {
		case *m.ComplianceRuntimeResult:
			n = t
		case *apiv1.ResourceInstance:
			err := n.FromInstance(t)
			if err != nil {
				return nil, fmt.Errorf("merge: failed to unserialize new resource: %w", err)
			}
		default:
			return nil, fmt.Errorf("merge: failed to unserialise new resource, unxexpected resource type: %T", t)
		}

		return f(p, n)
	})
}

// ComplianceRuntimeResultClient - rest client for ComplianceRuntimeResult resources that have a defined resource scope
type ComplianceRuntimeResultClient struct {
	client v1.Scoped
}

// UnscopedComplianceRuntimeResultClient - rest client for ComplianceRuntimeResult resources that do not have a defined scope
type UnscopedComplianceRuntimeResultClient struct {
	client v1.Unscoped
}

// NewComplianceRuntimeResultClient - creates a client that is not scoped to any resource
func NewComplianceRuntimeResultClient(c v1.Base) (*UnscopedComplianceRuntimeResultClient, error) {

	client, err := c.ForKind(m.ComplianceRuntimeResultGVK())
	if err != nil {
		return nil, err
	}

	return &UnscopedComplianceRuntimeResultClient{client}, nil

}

// WithScope - sets the resource scope for the client
func (c *UnscopedComplianceRuntimeResultClient) WithScope(scope string) *ComplianceRuntimeResultClient {
	return &ComplianceRuntimeResultClient{
		c.client.WithScope(scope),
	}
}

// Get - gets a resource by name
func (c *UnscopedComplianceRuntimeResultClient) Get(name string) (*m.ComplianceRuntimeResult, error) {
	ri, err := c.client.Get(name)
	if err != nil {
		return nil, err
	}

	service := &m.ComplianceRuntimeResult{}
	service.FromInstance(ri)

	return service, nil
}

// Update - updates a resource
func (c *UnscopedComplianceRuntimeResultClient) Update(res *m.ComplianceRuntimeResult, opts ...v1.UpdateOption) (*m.ComplianceRuntimeResult, error) {
	ri, err := res.AsInstance()
	if err != nil {
		return nil, err
	}
	resource, err := c.client.Update(ri, opts...)
	if err != nil {
		return nil, err
	}

	updated := &m.ComplianceRuntimeResult{}

	// Updates the resource in place
	err = updated.FromInstance(resource)
	if err != nil {
		return nil, err
	}

	return updated, nil
}

// List - gets a list of resources
func (c *ComplianceRuntimeResultClient) List(options ...v1.ListOptions) ([]*m.ComplianceRuntimeResult, error) {
	riList, err := c.client.List(options...)
	if err != nil {
		return nil, err
	}

	result := make([]*m.ComplianceRuntimeResult, len(riList))

	for i := range riList {
		result[i] = &m.ComplianceRuntimeResult{}
		err := result[i].FromInstance(riList[i])
		if err != nil {
			return nil, err
		}
	}

	return result, nil
}

// Get - gets a resource by name
func (c *ComplianceRuntimeResultClient) Get(name string) (*m.ComplianceRuntimeResult, error) {
	ri, err := c.client.Get(name)
	if err != nil {
		return nil, err
	}

	service := &m.ComplianceRuntimeResult{}
	service.FromInstance(ri)

	return service, nil
}

// Delete - deletes a resource
func (c *ComplianceRuntimeResultClient) Delete(res *m.ComplianceRuntimeResult) error {
	ri, err := res.AsInstance()

	if err != nil {
		return err
	}

	return c.client.Delete(ri)
}

// Create - creates a resource
func (c *ComplianceRuntimeResultClient) Create(res *m.ComplianceRuntimeResult, opts ...v1.CreateOption) (*m.ComplianceRuntimeResult, error) {
	ri, err := res.AsInstance()

	if err != nil {
		return nil, err
	}

	cri, err := c.client.Create(ri, opts...)
	if err != nil {
		return nil, err
	}

	created := &m.ComplianceRuntimeResult{}

	err = created.FromInstance(cri)
	if err != nil {
		return nil, err
	}

	return created, err
}

// Update - updates a resource
func (c *ComplianceRuntimeResultClient) Update(res *m.ComplianceRuntimeResult, opts ...v1.UpdateOption) (*m.ComplianceRuntimeResult, error) {
	ri, err := res.AsInstance()
	if err != nil {
		return nil, err
	}
	resource, err := c.client.Update(ri, opts...)
	if err != nil {
		return nil, err
	}

	updated := &m.ComplianceRuntimeResult{}

	// Updates the resource in place
	err = updated.FromInstance(resource)
	if err != nil {
		return nil, err
	}

	return updated, nil
}
