/*
 * This file is automatically generated
 */

package v1alpha1

import (
	"fmt"

	v1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/clients/api/v1"
	apiv1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/api/v1"
	m "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/management/v1alpha1"
)

type ConsumerSubscriptionDefinitionMergeFunc func(*m.ConsumerSubscriptionDefinition, *m.ConsumerSubscriptionDefinition) (*m.ConsumerSubscriptionDefinition, error)

// ConsumerSubscriptionDefinitionMerge builds a merge option for an update operation
func ConsumerSubscriptionDefinitionMerge(f ConsumerSubscriptionDefinitionMergeFunc) v1.UpdateOption {
	return v1.Merge(func(prev, new apiv1.Interface) (apiv1.Interface, error) {
		p, n := &m.ConsumerSubscriptionDefinition{}, &m.ConsumerSubscriptionDefinition{}

		switch t := prev.(type) {
		case *m.ConsumerSubscriptionDefinition:
			p = t
		case *apiv1.ResourceInstance:
			err := p.FromInstance(t)
			if err != nil {
				return nil, fmt.Errorf("merge: failed to unserialise prev resource: %w", err)
			}
		default:
			return nil, fmt.Errorf("merge: failed to unserialise prev resource, unxexpected resource type: %T", t)
		}

		switch t := new.(type) {
		case *m.ConsumerSubscriptionDefinition:
			n = t
		case *apiv1.ResourceInstance:
			err := n.FromInstance(t)
			if err != nil {
				return nil, fmt.Errorf("merge: failed to unserialize new resource: %w", err)
			}
		default:
			return nil, fmt.Errorf("merge: failed to unserialise new resource, unxexpected resource type: %T", t)
		}

		return f(p, n)
	})
}

// ConsumerSubscriptionDefinitionClient - rest client for ConsumerSubscriptionDefinition resources that have a defined resource scope
type ConsumerSubscriptionDefinitionClient struct {
	client v1.Scoped
}

// UnscopedConsumerSubscriptionDefinitionClient - rest client for ConsumerSubscriptionDefinition resources that do not have a defined scope
type UnscopedConsumerSubscriptionDefinitionClient struct {
	client v1.Unscoped
}

// NewConsumerSubscriptionDefinitionClient - creates a client that is not scoped to any resource
func NewConsumerSubscriptionDefinitionClient(c v1.Base) (*UnscopedConsumerSubscriptionDefinitionClient, error) {

	client, err := c.ForKind(m.ConsumerSubscriptionDefinitionGVK())
	if err != nil {
		return nil, err
	}

	return &UnscopedConsumerSubscriptionDefinitionClient{client}, nil

}

// WithScope - sets the resource scope for the client
func (c *UnscopedConsumerSubscriptionDefinitionClient) WithScope(scope string) *ConsumerSubscriptionDefinitionClient {
	return &ConsumerSubscriptionDefinitionClient{
		c.client.WithScope(scope),
	}
}

// Get - gets a resource by name
func (c *UnscopedConsumerSubscriptionDefinitionClient) Get(name string) (*m.ConsumerSubscriptionDefinition, error) {
	ri, err := c.client.Get(name)
	if err != nil {
		return nil, err
	}

	service := &m.ConsumerSubscriptionDefinition{}
	service.FromInstance(ri)

	return service, nil
}

// Update - updates a resource
func (c *UnscopedConsumerSubscriptionDefinitionClient) Update(res *m.ConsumerSubscriptionDefinition, opts ...v1.UpdateOption) (*m.ConsumerSubscriptionDefinition, error) {
	ri, err := res.AsInstance()
	if err != nil {
		return nil, err
	}
	resource, err := c.client.Update(ri, opts...)
	if err != nil {
		return nil, err
	}

	updated := &m.ConsumerSubscriptionDefinition{}

	// Updates the resource in place
	err = updated.FromInstance(resource)
	if err != nil {
		return nil, err
	}

	return updated, nil
}

// List - gets a list of resources
func (c *ConsumerSubscriptionDefinitionClient) List(options ...v1.ListOptions) ([]*m.ConsumerSubscriptionDefinition, error) {
	riList, err := c.client.List(options...)
	if err != nil {
		return nil, err
	}

	result := make([]*m.ConsumerSubscriptionDefinition, len(riList))

	for i := range riList {
		result[i] = &m.ConsumerSubscriptionDefinition{}
		err := result[i].FromInstance(riList[i])
		if err != nil {
			return nil, err
		}
	}

	return result, nil
}

// Get - gets a resource by name
func (c *ConsumerSubscriptionDefinitionClient) Get(name string) (*m.ConsumerSubscriptionDefinition, error) {
	ri, err := c.client.Get(name)
	if err != nil {
		return nil, err
	}

	service := &m.ConsumerSubscriptionDefinition{}
	service.FromInstance(ri)

	return service, nil
}

// Delete - deletes a resource
func (c *ConsumerSubscriptionDefinitionClient) Delete(res *m.ConsumerSubscriptionDefinition) error {
	ri, err := res.AsInstance()

	if err != nil {
		return err
	}

	return c.client.Delete(ri)
}

// Create - creates a resource
func (c *ConsumerSubscriptionDefinitionClient) Create(res *m.ConsumerSubscriptionDefinition, opts ...v1.CreateOption) (*m.ConsumerSubscriptionDefinition, error) {
	ri, err := res.AsInstance()

	if err != nil {
		return nil, err
	}

	cri, err := c.client.Create(ri, opts...)
	if err != nil {
		return nil, err
	}

	created := &m.ConsumerSubscriptionDefinition{}

	err = created.FromInstance(cri)
	if err != nil {
		return nil, err
	}

	return created, err
}

// Update - updates a resource
func (c *ConsumerSubscriptionDefinitionClient) Update(res *m.ConsumerSubscriptionDefinition, opts ...v1.UpdateOption) (*m.ConsumerSubscriptionDefinition, error) {
	ri, err := res.AsInstance()
	if err != nil {
		return nil, err
	}
	resource, err := c.client.Update(ri, opts...)
	if err != nil {
		return nil, err
	}

	updated := &m.ConsumerSubscriptionDefinition{}

	// Updates the resource in place
	err = updated.FromInstance(resource)
	if err != nil {
		return nil, err
	}

	return updated, nil
}
