/*
 * This file is automatically generated
 */

package management

import (
	"fmt"

	v1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/clients/api/v1"
	apiv1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/api/v1"
	m "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/management/v1alpha1"
)

type DataplaneMergeFunc func(*m.Dataplane, *m.Dataplane) (*m.Dataplane, error)

// DataplaneMerge builds a merge option for an update operation
func DataplaneMerge(f DataplaneMergeFunc) v1.UpdateOption {
	return v1.Merge(func(prev, new apiv1.Interface) (apiv1.Interface, error) {
		p, n := &m.Dataplane{}, &m.Dataplane{}

		switch t := prev.(type) {
		case *m.Dataplane:
			p = t
		case *apiv1.ResourceInstance:
			err := p.FromInstance(t)
			if err != nil {
				return nil, fmt.Errorf("merge: failed to unserialise prev resource: %w", err)
			}
		default:
			return nil, fmt.Errorf("merge: failed to unserialise prev resource, unxexpected resource type: %T", t)
		}

		switch t := new.(type) {
		case *m.Dataplane:
			n = t
		case *apiv1.ResourceInstance:
			err := n.FromInstance(t)
			if err != nil {
				return nil, fmt.Errorf("merge: failed to unserialize new resource: %w", err)
			}
		default:
			return nil, fmt.Errorf("merge: failed to unserialise new resource, unxexpected resource type: %T", t)
		}

		return f(p, n)
	})
}

// DataplaneClient - rest client for Dataplane resources that have a defined resource scope
type DataplaneClient struct {
	client v1.Scoped
}

// UnscopedDataplaneClient - rest client for Dataplane resources that do not have a defined scope
type UnscopedDataplaneClient struct {
	client v1.Unscoped
}

// NewDataplaneClient - creates a client that is not scoped to any resource
func NewDataplaneClient(c v1.Base) (*UnscopedDataplaneClient, error) {

	client, err := c.ForKind(m.DataplaneGVK())
	if err != nil {
		return nil, err
	}

	return &UnscopedDataplaneClient{client}, nil

}

// WithScope - sets the resource scope for the client
func (c *UnscopedDataplaneClient) WithScope(scope string) *DataplaneClient {
	return &DataplaneClient{
		c.client.WithScope(scope),
	}
}

// Get - gets a resource by name
func (c *UnscopedDataplaneClient) Get(name string) (*m.Dataplane, error) {
	ri, err := c.client.Get(name)
	if err != nil {
		return nil, err
	}

	service := &m.Dataplane{}
	service.FromInstance(ri)

	return service, nil
}

// Update - updates a resource
func (c *UnscopedDataplaneClient) Update(res *m.Dataplane, opts ...v1.UpdateOption) (*m.Dataplane, error) {
	ri, err := res.AsInstance()
	if err != nil {
		return nil, err
	}
	resource, err := c.client.Update(ri, opts...)
	if err != nil {
		return nil, err
	}

	updated := &m.Dataplane{}

	// Updates the resource in place
	err = updated.FromInstance(resource)
	if err != nil {
		return nil, err
	}

	return updated, nil
}

// List - gets a list of resources
func (c *DataplaneClient) List(options ...v1.ListOptions) ([]*m.Dataplane, error) {
	riList, err := c.client.List(options...)
	if err != nil {
		return nil, err
	}

	result := make([]*m.Dataplane, len(riList))

	for i := range riList {
		result[i] = &m.Dataplane{}
		err := result[i].FromInstance(riList[i])
		if err != nil {
			return nil, err
		}
	}

	return result, nil
}

// Get - gets a resource by name
func (c *DataplaneClient) Get(name string) (*m.Dataplane, error) {
	ri, err := c.client.Get(name)
	if err != nil {
		return nil, err
	}

	service := &m.Dataplane{}
	service.FromInstance(ri)

	return service, nil
}

// Delete - deletes a resource
func (c *DataplaneClient) Delete(res *m.Dataplane) error {
	ri, err := res.AsInstance()

	if err != nil {
		return err
	}

	return c.client.Delete(ri)
}

// Create - creates a resource
func (c *DataplaneClient) Create(res *m.Dataplane, opts ...v1.CreateOption) (*m.Dataplane, error) {
	ri, err := res.AsInstance()

	if err != nil {
		return nil, err
	}

	cri, err := c.client.Create(ri, opts...)
	if err != nil {
		return nil, err
	}

	created := &m.Dataplane{}

	err = created.FromInstance(cri)
	if err != nil {
		return nil, err
	}

	return created, err
}

// Update - updates a resource
func (c *DataplaneClient) Update(res *m.Dataplane, opts ...v1.UpdateOption) (*m.Dataplane, error) {
	ri, err := res.AsInstance()
	if err != nil {
		return nil, err
	}
	resource, err := c.client.Update(ri, opts...)
	if err != nil {
		return nil, err
	}

	updated := &m.Dataplane{}

	// Updates the resource in place
	err = updated.FromInstance(resource)
	if err != nil {
		return nil, err
	}

	return updated, nil
}
