/*
 * This file is automatically generated
 */

package v1alpha1

import (
	"context"

	v1 "git.ecd.axway.int/apigov/apic_agents_sdk/pkg/apic/apiserver/clients/api/v1"
	"git.ecd.axway.int/apigov/apic_agents_sdk/pkg/apic/apiserver/models/management/v1alpha1"
)

// MeshServiceClient -
type MeshServiceClient struct {
	client v1.Scoped
}

// UnscopedMeshServiceClient -
type UnscopedMeshServiceClient struct {
	client v1.Unscoped
}

// NewMeshServiceClient -

func NewMeshServiceClient(c v1.Base) (*UnscopedMeshServiceClient, error) {

	client, err := c.ForKind(v1alpha1.MeshServiceGVK())
	if err != nil {
		return nil, err
	}

	return &UnscopedMeshServiceClient{client}, nil

}

// WithScope -
func (c *UnscopedMeshServiceClient) WithScope(scope string) *MeshServiceClient {
	return &MeshServiceClient{
		c.client.WithScope(scope),
	}
}

// List -
func (c *MeshServiceClient) List(ctx context.Context, options ...v1.ListOptions) ([]*v1alpha1.MeshService, error) {
	riList, err := c.client.List(ctx, options...)
	if err != nil {
		return nil, err
	}

	result := make([]*v1alpha1.MeshService, len(riList))

	for i := range riList {
		result[i] = &v1alpha1.MeshService{}
		err := result[i].FromInstance(riList[i])
		if err != nil {
			return nil, err
		}
	}

	return result, nil
}

// Get -
func (c *MeshServiceClient) Get(ctx context.Context, name string) (*v1alpha1.MeshService, error) {
	ri, err := c.client.Get(ctx, name)
	if err != nil {
		return nil, err
	}

	service := &v1alpha1.MeshService{}
	service.FromInstance(ri)

	return service, nil
}

// Delete -
func (c *MeshServiceClient) Delete(ctx context.Context, res *v1alpha1.MeshService) error {
	ri, err := res.AsInstance()

	if err != nil {
		return err
	}

	return c.client.Delete(ctx, ri)
}

// Create -
func (c *MeshServiceClient) Create(ctx context.Context, res *v1alpha1.MeshService) (*v1alpha1.MeshService, error) {
	ri, err := res.AsInstance()

	if err != nil {
		return nil, err
	}

	cri, err := c.client.Create(ctx, ri)
	if err != nil {
		return nil, err
	}

	created := &v1alpha1.MeshService{}

	err = created.FromInstance(cri)
	if err != nil {
		return nil, err
	}

	return created, err
}

// Update -
func (c *MeshServiceClient) Update(ctx context.Context, res *v1alpha1.MeshService) (*v1alpha1.MeshService, error) {
	ri, err := res.AsInstance()
	if err != nil {
		return nil, err
	}
	resource, err := c.client.Update(ctx, ri)
	if err != nil {
		return nil, err
	}
	updated := &v1alpha1.MeshService{}

	// Updates the resource in place
	err = updated.FromInstance(resource)
	if err != nil {
		return nil, err
	}

	return updated, nil
}
