/*
 * This file is automatically generated
 */

package v1alpha1

import (
	v1 "git.ecd.axway.int/apigov/apic_agents_sdk/pkg/apic/apiserver/clients/api/v1"
	"git.ecd.axway.int/apigov/apic_agents_sdk/pkg/apic/apiserver/models/management/v1alpha1"
)

// MeshWorkloadClient -
type MeshWorkloadClient struct {
	client *v1.Client
}

// NewMeshWorkloadClient -
func NewMeshWorkloadClient(cb *v1.ClientBase) (*MeshWorkloadClient, error) {
	client, err := cb.ForKind(v1alpha1.MeshWorkloadGVK())
	if err != nil {
		return nil, err
	}

	return &MeshWorkloadClient{client}, nil
}

// WithScope -
func (c *MeshWorkloadClient) WithScope(scope string) *MeshWorkloadClient {
	return &MeshWorkloadClient{
		c.client.WithScope(scope),
	}
}

// SetQuery -
func (c *MeshWorkloadClient) SetQuery(query string) {
	c.client.SetQuery(query)
}

// List -
func (c *MeshWorkloadClient) List() ([]*v1alpha1.MeshWorkload, error) {
	riList, err := c.client.List()
	if err != nil {
		return nil, err
	}

	result := make([]*v1alpha1.MeshWorkload, len(riList))

	for i := range riList {
		result[i] = &v1alpha1.MeshWorkload{}
		err := result[i].FromInstance(riList[i])
		if err != nil {
			return nil, err
		}
	}

	return result, nil
}

// Get -
func (c *MeshWorkloadClient) Get(name string) (*v1alpha1.MeshWorkload, error) {
	ri, err := c.client.Get(name)
	if err != nil {
		return nil, err
	}

	service := &v1alpha1.MeshWorkload{}
	service.FromInstance(ri)

	return service, nil
}

// Delete -
func (c *MeshWorkloadClient) Delete(res *v1alpha1.MeshWorkload) error {
	ri, err := res.AsInstance()

	if err != nil {
		return err
	}

	return c.client.Delete(ri)
}

// Create -
func (c *MeshWorkloadClient) Create(res *v1alpha1.MeshWorkload) (*v1alpha1.MeshWorkload, error) {
	ri, err := res.AsInstance()

	if err != nil {
		return nil, err
	}

	cri, err := c.client.Create(ri)
	if err != nil {
		return nil, err
	}

	created := &v1alpha1.MeshWorkload{}

	err = created.FromInstance(cri)
	if err != nil {
		return nil, err
	}

	return created, err
}

// Update -
func (c *MeshWorkloadClient) Update(res *v1alpha1.MeshWorkload) (*v1alpha1.MeshWorkload, error) {
	ri, err := res.AsInstance()
	if err != nil {
		return nil, err
	}
	resource, err := c.client.Update(ri)
	updated := &v1alpha1.MeshWorkload{}

	// Updates the resource in place
	err = updated.FromInstance(resource)
	if err != nil {
		return nil, err
	}

	return updated, nil
}
