/*
 * This file is automatically generated
 */

package v1alpha1

import (
	"fmt"

	v1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/clients/api/v1"
	apiv1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/api/v1"
	"github.com/Axway/agent-sdk/pkg/apic/apiserver/models/management/v1alpha1"
)

type MeshWorkloadMergeFunc func(*v1alpha1.MeshWorkload, *v1alpha1.MeshWorkload) (*v1alpha1.MeshWorkload, error)

// Merge builds a merge option for an update operation
func MeshWorkloadMerge(f MeshWorkloadMergeFunc) v1.UpdateOption {
	return v1.Merge(func(prev, new apiv1.Interface) (apiv1.Interface, error) {
		p, n := &v1alpha1.MeshWorkload{}, &v1alpha1.MeshWorkload{}

		switch t := prev.(type) {
		case *v1alpha1.MeshWorkload:
			p = t
		case *apiv1.ResourceInstance:
			err := p.FromInstance(t)
			if err != nil {
				return nil, fmt.Errorf("merge: failed to unserialise prev resource: %w", err)
			}
		default:
			return nil, fmt.Errorf("merge: failed to unserialise prev resource, unxexpected resource type: %T", t)
		}

		switch t := new.(type) {
		case *v1alpha1.MeshWorkload:
			n = t
		case *apiv1.ResourceInstance:
			err := n.FromInstance(t)
			if err != nil {
				return nil, fmt.Errorf("merge: failed to unserialize new resource: %w", err)
			}
		default:
			return nil, fmt.Errorf("merge: failed to unserialise new resource, unxexpected resource type: %T", t)
		}

		return f(p, n)
	})
}

// MeshWorkloadClient -
type MeshWorkloadClient struct {
	client v1.Scoped
}

// UnscopedMeshWorkloadClient -
type UnscopedMeshWorkloadClient struct {
	client v1.Unscoped
}

// NewMeshWorkloadClient -
func NewMeshWorkloadClient(c v1.Base) (*UnscopedMeshWorkloadClient, error) {

	client, err := c.ForKind(v1alpha1.MeshWorkloadGVK())
	if err != nil {
		return nil, err
	}

	return &UnscopedMeshWorkloadClient{client}, nil

}

// WithScope -
func (c *UnscopedMeshWorkloadClient) WithScope(scope string) *MeshWorkloadClient {
	return &MeshWorkloadClient{
		c.client.WithScope(scope),
	}
}

// Get -
func (c *UnscopedMeshWorkloadClient) Get(name string) (*v1alpha1.MeshWorkload, error) {
	ri, err := c.client.Get(name)
	if err != nil {
		return nil, err
	}

	service := &v1alpha1.MeshWorkload{}
	service.FromInstance(ri)

	return service, nil
}

// Update -
func (c *UnscopedMeshWorkloadClient) Update(res *v1alpha1.MeshWorkload, opts ...v1.UpdateOption) (*v1alpha1.MeshWorkload, error) {
	ri, err := res.AsInstance()
	if err != nil {
		return nil, err
	}
	resource, err := c.client.Update(ri, opts...)
	if err != nil {
		return nil, err
	}

	updated := &v1alpha1.MeshWorkload{}

	// Updates the resource in place
	err = updated.FromInstance(resource)
	if err != nil {
		return nil, err
	}

	return updated, nil
}

// List -
func (c *MeshWorkloadClient) List(options ...v1.ListOptions) ([]*v1alpha1.MeshWorkload, error) {
	riList, err := c.client.List(options...)
	if err != nil {
		return nil, err
	}

	result := make([]*v1alpha1.MeshWorkload, len(riList))

	for i := range riList {
		result[i] = &v1alpha1.MeshWorkload{}
		err := result[i].FromInstance(riList[i])
		if err != nil {
			return nil, err
		}
	}

	return result, nil
}

// Get -
func (c *MeshWorkloadClient) Get(name string) (*v1alpha1.MeshWorkload, error) {
	ri, err := c.client.Get(name)
	if err != nil {
		return nil, err
	}

	service := &v1alpha1.MeshWorkload{}
	service.FromInstance(ri)

	return service, nil
}

// Delete -
func (c *MeshWorkloadClient) Delete(res *v1alpha1.MeshWorkload) error {
	ri, err := res.AsInstance()

	if err != nil {
		return err
	}

	return c.client.Delete(ri)
}

// Create -
func (c *MeshWorkloadClient) Create(res *v1alpha1.MeshWorkload, opts ...v1.CreateOption) (*v1alpha1.MeshWorkload, error) {
	ri, err := res.AsInstance()

	if err != nil {
		return nil, err
	}

	cri, err := c.client.Create(ri, opts...)
	if err != nil {
		return nil, err
	}

	created := &v1alpha1.MeshWorkload{}

	err = created.FromInstance(cri)
	if err != nil {
		return nil, err
	}

	return created, err
}

// Update -
func (c *MeshWorkloadClient) Update(res *v1alpha1.MeshWorkload, opts ...v1.UpdateOption) (*v1alpha1.MeshWorkload, error) {
	ri, err := res.AsInstance()
	if err != nil {
		return nil, err
	}
	resource, err := c.client.Update(ri, opts...)
	if err != nil {
		return nil, err
	}

	updated := &v1alpha1.MeshWorkload{}

	// Updates the resource in place
	err = updated.FromInstance(resource)
	if err != nil {
		return nil, err
	}

	return updated, nil
}
