/*
 * This file is automatically generated
 */

package management

import (
	"fmt"

	v1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/clients/api/v1"
	apiv1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/api/v1"
	m "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/management/v1alpha1"
)

type VirtualHostMergeFunc func(*m.VirtualHost, *m.VirtualHost) (*m.VirtualHost, error)

// VirtualHostMerge builds a merge option for an update operation
func VirtualHostMerge(f VirtualHostMergeFunc) v1.UpdateOption {
	return v1.Merge(func(prev, new apiv1.Interface) (apiv1.Interface, error) {
		p, n := &m.VirtualHost{}, &m.VirtualHost{}

		switch t := prev.(type) {
		case *m.VirtualHost:
			p = t
		case *apiv1.ResourceInstance:
			err := p.FromInstance(t)
			if err != nil {
				return nil, fmt.Errorf("merge: failed to unserialise prev resource: %w", err)
			}
		default:
			return nil, fmt.Errorf("merge: failed to unserialise prev resource, unxexpected resource type: %T", t)
		}

		switch t := new.(type) {
		case *m.VirtualHost:
			n = t
		case *apiv1.ResourceInstance:
			err := n.FromInstance(t)
			if err != nil {
				return nil, fmt.Errorf("merge: failed to unserialize new resource: %w", err)
			}
		default:
			return nil, fmt.Errorf("merge: failed to unserialise new resource, unxexpected resource type: %T", t)
		}

		return f(p, n)
	})
}

// VirtualHostClient - rest client for VirtualHost resources that have a defined resource scope
type VirtualHostClient struct {
	client v1.Scoped
}

// UnscopedVirtualHostClient - rest client for VirtualHost resources that do not have a defined scope
type UnscopedVirtualHostClient struct {
	client v1.Unscoped
}

// NewVirtualHostClient - creates a client that is not scoped to any resource
func NewVirtualHostClient(c v1.Base) (*UnscopedVirtualHostClient, error) {

	client, err := c.ForKind(m.VirtualHostGVK())
	if err != nil {
		return nil, err
	}

	return &UnscopedVirtualHostClient{client}, nil

}

// WithScope - sets the resource scope for the client
func (c *UnscopedVirtualHostClient) WithScope(scope string) *VirtualHostClient {
	return &VirtualHostClient{
		c.client.WithScope(scope),
	}
}

// Get - gets a resource by name
func (c *UnscopedVirtualHostClient) Get(name string) (*m.VirtualHost, error) {
	ri, err := c.client.Get(name)
	if err != nil {
		return nil, err
	}

	service := &m.VirtualHost{}
	service.FromInstance(ri)

	return service, nil
}

// Update - updates a resource
func (c *UnscopedVirtualHostClient) Update(res *m.VirtualHost, opts ...v1.UpdateOption) (*m.VirtualHost, error) {
	ri, err := res.AsInstance()
	if err != nil {
		return nil, err
	}
	resource, err := c.client.Update(ri, opts...)
	if err != nil {
		return nil, err
	}

	updated := &m.VirtualHost{}

	// Updates the resource in place
	err = updated.FromInstance(resource)
	if err != nil {
		return nil, err
	}

	return updated, nil
}

// List - gets a list of resources
func (c *VirtualHostClient) List(options ...v1.ListOptions) ([]*m.VirtualHost, error) {
	riList, err := c.client.List(options...)
	if err != nil {
		return nil, err
	}

	result := make([]*m.VirtualHost, len(riList))

	for i := range riList {
		result[i] = &m.VirtualHost{}
		err := result[i].FromInstance(riList[i])
		if err != nil {
			return nil, err
		}
	}

	return result, nil
}

// Get - gets a resource by name
func (c *VirtualHostClient) Get(name string) (*m.VirtualHost, error) {
	ri, err := c.client.Get(name)
	if err != nil {
		return nil, err
	}

	service := &m.VirtualHost{}
	service.FromInstance(ri)

	return service, nil
}

// Delete - deletes a resource
func (c *VirtualHostClient) Delete(res *m.VirtualHost) error {
	ri, err := res.AsInstance()

	if err != nil {
		return err
	}

	return c.client.Delete(ri)
}

// Create - creates a resource
func (c *VirtualHostClient) Create(res *m.VirtualHost, opts ...v1.CreateOption) (*m.VirtualHost, error) {
	ri, err := res.AsInstance()

	if err != nil {
		return nil, err
	}

	cri, err := c.client.Create(ri, opts...)
	if err != nil {
		return nil, err
	}

	created := &m.VirtualHost{}

	err = created.FromInstance(cri)
	if err != nil {
		return nil, err
	}

	return created, err
}

// Update - updates a resource
func (c *VirtualHostClient) Update(res *m.VirtualHost, opts ...v1.UpdateOption) (*m.VirtualHost, error) {
	ri, err := res.AsInstance()
	if err != nil {
		return nil, err
	}
	resource, err := c.client.Update(ri, opts...)
	if err != nil {
		return nil, err
	}

	updated := &m.VirtualHost{}

	// Updates the resource in place
	err = updated.FromInstance(resource)
	if err != nil {
		return nil, err
	}

	return updated, nil
}
