/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package definitions

import (
	// GENERATE: The following code has been modified after code generation
	//
	//	"time"
	time "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/api/v1"
)

// ComponentSpecLatest  (definitions.v1alpha1.Component)
type ComponentSpecLatest struct {
	Version          string    `json:"version"`
	ReleaseDate      time.Time `json:"releaseDate"`
	EndOfSupportDate time.Time `json:"endOfSupportDate,omitempty"`
}
