/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package definitions

// ResourceDefinitionSpecReferencesFrom struct for ResourceDefinitionSpecReferencesFrom
type ResourceDefinitionSpecReferencesFrom struct {
	// Defines the subResource which is referring to the resource. Omit for non subResource references.
	SubResourceName string `json:"subResourceName,omitempty"`
}
