/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1alpha1

// ResourceDefinitionSpec struct for ResourceDefinitionSpec
type ResourceDefinitionSpec struct {
	// Value used in the endpoint path for accessing the resource.
	Plural string `json:"plural"`
	// Defines the kind of the resource. The server infers this from the endpoint the client submits the request to.
	Kind         string                             `json:"kind"`
	Scope        ResourceDefinitionSpecScope        `json:"scope,omitempty"`
	QueryParams  []string                           `json:"queryParams,omitempty"`
	SubResources ResourceDefinitionSpecSubResources `json:"subResources,omitempty"`
	References   ResourceDefinitionSpecReferences   `json:"references,omitempty"`
}
