/*
 * API Server specification.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: SNAPSHOT
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1alpha1

// ResourceDefinitionSpecSubResources Describes the subresources that the current resource might have.
type ResourceDefinitionSpecSubResources struct {
	Names []string `json:"names,omitempty"`
}
