
name: Release SDK

# run this action if there is a push of a new tag of the form v.n.n.n on main branch
# on:
#   release:
#     types: [published]
# need to figure this out. The above should have worked but caused ONLY the release action to run
# adding the below only to keep the action but to make it not ever run
on:
  push:
    branches:
      - APIGOV-DALE
      - APIGOV-dale
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release SDK
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set version variables
        id: vars
        run: |
          # The full GITHUB_REF is refs/tags/vn.n.n
          echo "github_ref ${GITHUB_REF}"

          # temp
          GH_REF="/refs/tags/v1.2.3"

          # this mess parses GITHUB_REF into its major/minor/patch parts
          MAJOR_VER=$(echo ${GH_REF#*v} | cut -d. -f1)
          echo "MAJOR_VER $MAJOR_VER"
          MINOR_VER=$(echo ${GH_REF#*v} | cut -d. -f2)
          echo "MINOR_VER $MINOR_VER"
          PATCH_VER=$(echo ${GH_REF#*v} | cut -d. -f3)
          echo "PATCH_VER $PATCH_VER"
          declare -i PATCH_VER
          PATCH_VER+=1
          echo "PATCH_VER now $PATCH_VER"
          echo ::set-output name=major_ver::${MAJOR_VER}
          echo ::set-output name=minor_ver::${MINOR_VER}
          echo ::set-output name=patch_ver::${PATCH_VER}
          echo ::set-output name=new_ver::v$MAJOR_VER}.${MINOR_VER}.${PATCH_VER}
          # echo "INT - update to new release v${MAJOR_VER}.${MINOR_VER}.${PATCH_VER}"

          # let x=echo $({FOO#refs/*/} | cut -d. -f3)
          # echo "$x"
          # echo ::set-output name=major2_ver::${x}
          # echo ::set-output name=major_ver::${GITHUB_REF#refs/*/} | cut -d. -f1
          # echo ::set-output name=minor_ver::${GITHUB_REF#refs/*/} | cut -d. -f2
          # echo ::set-output name=patch_ver::${GITHUB_REF#refs/*/} | cut -d. -f3
          # echo ::set-output name=next_ver::$$( ${{ steps.vars.outputs.patch_ver }} + 1)
          echo ::set-output name=new_ver::v${{ steps.vars.outputs.major_ver }}.${{ steps.vars.outputs.minor_ver }}.${{ steps.vars.outputs.patch_ver }}
      - name: Update version file
        working-directory: ./build/scripts
        # This passes vn.n.n to the shellscript.
        run: |
          # MAJOR=${{ steps.vars.outputs.major_ver }}
          # MINOR=${{ steps.vars.outputs.minor_ver }}
          # PATCH=${{ steps.vars.outputs.patch_ver }}
          # echo "${MAJOR}"
          # echo "${MINOR}"
          # echo "${PATCH}"

          NEXT_VERSION=${{ steps.vars.outputs.next_ver }}
          echo ${NEXT_VERSION}
          # ./promote.sh ${NEXT_VERSION}
      # - name: Create pull request
      #   uses: peter-evans/create-pull-request@v4
      #   with:
      #     branch: APIGOV-updateversion
      #     commit-message: INT - update to new release ${NEXT_VERSION}
      #     title: INT - update to new release ${NEXT_VERSION}
      #     base: main
      #     delete-branch: true

     