
name: Release SDK

# run this action if there is a push of a new tag of the form v.n.n.n on main branch
# on:
#   release:
#     types: [published]
# need to figure this out. The above should have worked but caused ONLY the release action to run
# adding the below only to keep the action but to make it not ever run
on:
  push:
    branches:
      - APIGOV-DALE
      - APIGOV-dale
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release SDK
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Update version file
        working-directory: ./build/scripts
        # This passes vn.n.n to the shellscript. The full GITHUB_REF is refs/tags/vn.n.n
        run: |
          echo "${GITHUB_REF}"
          echo "${GITHUB_REF_NAME}"
          echo "INT - update to new release ${GITHUB_REF_NAME}"

     