
name: Release SDK

# run this action if there is a push of a new tag of the form v.n.n.n on main branch
# on:
#   release:
#     types: [published]
# need to figure this out. The above should have worked but caused ONLY the release action to run
# adding the below only to keep the action but to make it not ever run
on:
  push:
    branches:
      - APIGOV-DALE
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release SDK
    defaults:
      run:
        working-directory: .
    steps:
    - uses: actions/checkout@v2
    - name: Update version file
      working-directory: ./build/scripts
      # This passes vn.n.n to the shellscript. The full GITHUB_REF is refs/tags/vn.n.n
      run: ./promote.sh ${GITHUB_REF}   