
name: Release SDK

# run this action if there is a push of a new tag of the form v.n.n.n on main branch
# on:
#   release:
#     types: [published]
# need to figure this out. The above should have worked but caused ONLY the release action to run
# adding the below only to keep the action but to make it not ever run
on:
  push:
    branches:
      - APIGOV-DALE
      - APIGOV-dale
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release SDK
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout main
        id: vars
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Update version file
        working-directory: ./build/scripts
        # This passes vn.n.n to the shellscript. The full GITHUB_REF is refs/tags/vn.n.n
        run: |
          echo "github_ref ${GITHUB_REF}"
          echo "github_ref_name ${GITHUB_REF_NAME}"
          echo "github.refname ${{  github.ref_name }}"
          echo "INT - update to new release ${GITHUB_REF_NAME}"

          echo "tag ${GITHUB_REF#refs/*/}"
          echo "tag ${GITHUB_REF#refs/*/}"
          export FOO="/refs/tags/v1.2.3"
          echo "foo ${FOO#refs/*/}"
          echo ::set-output name=major_ver::${FOO#refs/*/} | cut -d. -f1
          echo "major ${{ steps.vars.outputs.major_ver }}"
          echo ::set-output name=minor_ver::${FOO#refs/*/} | cut -d. -f2
          echo "minor ${{ steps.vars.outputs.minor_ver }}"
          echo ::set-output name=patch_ver::${FOO#refs/*/} | cut -d. -f3
          echo "patch ${{ steps.vars.outputs.patch_ver }}"
          # echo ::set-output name=major_ver::${GITHUB_REF#refs/*/} | cut -d. -f1
          # echo ::set-output name=minor_ver::${GITHUB_REF#refs/*/} | cut -d. -f2
          # echo ::set-output name=patch_ver::${GITHUB_REF#refs/*/} | cut -d. -f3
          echo ::set-output name=next_ver::${{ steps.vars.outputs.patch_ver }} + 1
          echo "here1"
          echo "next ${{ steps.vars.outputs.patch_ver }}"
          echo "here2"
          echo ::set-output name=new_ver::v${{ steps.vars.outputs.major_ver }}.${{ steps.vars.outputs.minor_ver }}.${{ steps.vars.outputs.next_ver }}
          echo "next ${{ steps.vars.outputs.new_ver }}"

      #     ./promote.sh ${GITHUB_REF}
      # - name: Create pull request
      #   uses: peter-evans/create-pull-request@v4
      #   with:
      #     branch: APIGOV-updateversion
      #     commit-message: INT - update to new release ${GITHUB_REF_NAME}
      #     title: INT - update to new release ${GITHUB_REF_NAME}
      #     base: main
      #     delete-branch: true

     