
name: Release SDK
# run this action if there is a push of a new tag of the form v.n.n.n
on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release discovery
    defaults:
      run:
        working-directory: .
    steps:
    - uses: actions/checkout@v2
    # - name: Unshallow Fetch
    #   run: git fetch --prune --unshallow
    # - uses: actions/setup-go@v2
    #   with:
    #     go-version: '^1.16.0'
    - name: Update version file
      run: cat ./version